ROCm/pytorch

tools/amd_build/pyHIPIFY/hipify-python.py

Address even more comments

---

.jenkins/pytorch/build.sh

conditions.
The most expensive single step seems to be linking anyways.

half the number of jobs for now to make sure we do not run into OOM

---

tools/amd_build/pyHIPIFY/hipify-python.py

Adding more comments to the find_closure_group function.

Updating comments for find_closure_group.

---

tools/amd_build/disabled_features.yaml

Enabled functions set_rngstate_kernel, THCRandom_setRNGState in THCTensorRandom.cu

enable set_rngstate function.

---

aten/src/THC/THCNumerics.cuh

Not adapted to hip-clang, but I believe there is more to be done.

Silence warning - derived from our fork's PR #192

---

caffe2/operators/hip/conv_op_miopen.cc

These changes along with MIOpen 1.5 group conv API fixes completes the updating of MIOpen conv operator

[Caffe2] MIOpen dims change check

---

tools/amd_build/pyHIPIFY/hipify-python.py

* Remove duplicate math transpilation function
* Modify regex to expand matches to more __device__ functions
* Try a different tack. Apply math transpilations only to .cu and .cuh files
* Undo change that's not required anymore since we're not using regex to detect device functions

Remove duplicate math transpilation function (ROCm 233)

---

caffe2/python/convnet_benchmarks.py

This change makes the model more comparable to other benchmarking models we use

Performance script fix

---

test/test_sparse.py
test/test_torch.py

Enables 18 more test_sparse tests.

Enable more test_sparse tests passing with whiterabbit

---

caffe2/python/utils.py

enable GetGPUMemoryUsageStats for HIP

[caffe2] print HIP memory usage

---

.jenkins/pytorch/test.sh
aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/native/Convolution.cpp
aten/src/ATen/native/Normalization.cpp
aten/src/ATen/native/miopen/BatchNorm_miopen.cpp
aten/src/ATen/native/miopen/Conv_miopen.cpp

* figure out edge cases
* enable groups

Enable MIOpen properly

---

test/test_cuda.py
test/test_nn.py

Changes I made to run tests using Python 3.6.

Update test scripts to run on Python 3.6

---

modules/detectron/ps_roi_pool_op.cu
modules/detectron/select_smooth_l1_loss_op.cu
modules/detectron/sigmoid_focal_loss_op.cu
modules/detectron/smooth_l1_loss_op.cu
modules/detectron/softmax_focal_loss_op.cu

fix for https://github.com/ROCmSoftwarePlatform/pytorch/issues/297

fix detectron support for HIP

---

caffe2/operators/rnn/hip/recurrent_op_miopen.cc
caffe2/python/operator_test/cudnn_recurrent_test.py

Fixed usage of APIs. (miopenGetRNNLayerParam & miopenGetRNNLayerBias)

[Caffe2] Fixed MIOpen RNN Segfault issue and enabled RNN test

---

aten/src/THC/THCBlas.cu
aten/src/THC/generic/THCTensorMathBlas.cu

Use the upcoming gemm_ex interface from rocBLAS both in regular hgemm

---

aten/src/ATen/cuda/CUDAApplyUtils.cuh
aten/src/ATen/native/cuda/Dropout.cu
aten/src/ATen/native/cuda/RNN.cu
aten/src/ATen/native/cuda/TensorTransformations.cu
aten/src/THC/THCReduce.cuh
aten/src/THCUNN/SpatialCrossMapLRN.cu

https://github.com/pytorch/pytorch/pull/15228

Cherry pick: Launch bounds rocm

---

aten/src/THC/THCReduceAll.cuh
aten/src/THCUNN/MultiLabelMarginCriterion.cu
aten/src/THCUNN/SpatialClassNLLCriterion.cu

* Add launch bounds annotation required for ROCm 2.0 / gfx906.

More launch bounds

---

.jenkins/caffe2/test.sh
aten/src/ATen/native/cuda/Embedding.cu
aten/src/ATen/native/cuda/EmbeddingBag.cu
aten/src/ATen/native/cuda/Unique.cu
aten/src/THC/generic/THCTensorMode.cu
aten/src/THCUNN/generic/LookupTable.cu
caffe2/operators/generate_proposals_op.cu
caffe2/operators/reduce_front_back_max_ops.cu
caffe2/operators/rmac_regions_op.cu
cmake/Dependencies.cmake
cmake/public/LoadHIP.cmake
docker/caffe2/jenkins/common/install_rocm.sh
test/test_sparse.py
test/test_torch.py
tools/amd_build/pyHIPIFY/cuda_to_hip_mappings.py

will be reverted once upstream lands this enablement.
CI will be broken as docker images not updated. This branch is for internal testing.

Enable rocThrust and friends - this is a copy of the upstream PR and

---

tools/amd_build/build_amd.py

Reverts ROCmSoftwarePlatform/pytorch#419

Revert "Fix build_amd.py for hip-clang"

---

tools/amd_build/build_amd.py

Fix build_amd.py for hip-clang

---

aten/src/ATen/function_wrapper.py
aten/src/ATen/native_parse.py
aten/src/ATen/preprocess_declarations.py

add cuda_bfloat16 type

---

aten/src/ATen/native/Convolution.cpp

Enabled transpose convolutions with MIOpen.

[Pytorch] Enable MIOpen Convolution transpose

---

aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/native/Convolution.cpp

* Enabled 3D Conv support with MIOpen.

[Pytorch] Enable MIOpen 3D convolutions.

---

caffe2/operators/hip/conv_op_miopen.hip
caffe2/python/operator_test/conv_test.py

1. Enabled conv3d support.
2. Enabled a test case for the same.

[Caffe2] Enable MIOpen Conv3D Operator.

---

caffe2/operators/hip/spatial_batch_norm_op_miopen.hip
caffe2/python/operator_test/spatial_bn_op_test.py

* Enable 3D Batchnormalizations in caffe2

[Caffe2] Enable MIOpen 3D batchnormalizations.

---

torch/csrc/jit/OVERVIEW.md

Summary: Pull Request resolved: https://github.com/pytorch/pytorch/pull/33925
Differential Revision: D20171970
Pulled By: vincentqb
fbshipit-source-id: 5c1a8553760f74cecebaea7e88463b767ab81211

IFU 20200302 #2: Fix typo (#33925)

---

test/test_jit.py

Summary: Pull Request resolved: https://github.com/pytorch/pytorch/pull/35968
Pulled By: driazati
Differential Revision: D20845617
fbshipit-source-id: 1b1cedb9c5c721f7f7edf94b91fbbb97d249bc2a

Fix flake8 (#35968)

---

aten/src/ATen/native/TensorShape.cpp
test/quantization/test_quantized_tensor.py
torch/csrc/jit/tensorexpr/kernel.cpp

IFU 20200513 part2

---

.github/workflows/ifu_testing.yml

rename IFU action, update for rocm 3.9

rename IFU action, update for rocm 3.9

---

aten/src/ATen/native/cuda/Shape.cu

This reverts commit 20f52cdd761cebe3274f371e149f392227961ef6 which caused perf regression in testing
@jeffdaily

Revert the commit to pass struct to kernel

---

.github/workflows/ifu_testing.yml

update ifu_testing.yml github action to rocm3.10_internal_testing

update ifu_testing.yml github action to rocm3.10_internal_testing

---

aten/src/THC/THCAtomics.cuh

Update the atomicAddNoRet return type.

update atomicAddNoReturn intrinsic return type

---

aten/src/THC/THCAtomics.cuh
cmake/Dependencies.cmake
cmake/public/test_atomic.hip

Also add hipcc compiler check for fp32 atomic return type.

use HIP_VERSION for float atomic add check

---

test/test_linalg.py
test/test_nn.py

Summary: Pull Request resolved: https://github.com/pytorch/pytorch/pull/56279
Test Plan: Imported from OSS
Reviewed By: albanD
Differential Revision: D27916606
Pulled By: soulitzer
fbshipit-source-id: 60c07024f6eb818f4aa6730a5f9ff90d7bc2b80f
Fixes #{issue number}

Disable flaky tests (#56279)

---

.circleci/docker/common/install_rocm.sh

In preparation for ROCm 4.2 release changing the apt repo name from xenial to ubuntu.

ubuntu version check in install_rocm.sh

---

test/test_cuda_primary_ctx.py
torch/csrc/autograd/engine.cpp

Includes the commits from https://github.com/pytorch/pytorch/pull/71146 w.r.t https://ontrack-internal.amd.com/browse/SWDEV-290884. 
cc: @amathews-amd, @jithunnair-amd

Add hasPrimaryContext() commits

---

.circleci/docker/common/install_rocm.sh

Enable MAGMA for --amdgpu-target=gfx940
cc: @jithunnair-amd

Magma for gfx940

---

.circleci/docker/common/install_conda.sh

Cherrypick from https://github.com/pytorch/pytorch/pull/72433
Pulled only circleci installation
Fixes https://ontrack-internal.amd.com/browse/SWDEV-322263

Fix librosa version

---

.circleci/docker/build.sh
.circleci/docker/centos-rocm/Dockerfile
.circleci/docker/common/install_base.sh
.circleci/docker/common/install_conda.sh
.circleci/docker/ubuntu-cuda/Dockerfile

Fixes 
- https://ontrack-internal.amd.com/browse/SWDEV-323126
- https://ontrack-internal.amd.com/browse/SWDEV-324383

partial IFU of just .circleci/docker directory

---

test/test_spectral_ops.py
torch/functional.py

Cherry-pick from PT upstream
https://github.com/pytorch/pytorch/pull/72833/
Fixes https://ontrack-internal.amd.com/browse/SWDEV-322263

Update stft tests to support latest librosa

---

.circleci/docker/build.sh
.circleci/docker/centos-rocm/Dockerfile
.circleci/docker/common/install_base.sh
.circleci/docker/common/install_conda.sh
test/test_spectral_ops.py
torch/functional.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-324383

Fix numpy and librosa issues for rocm5.0_internal_testing

---

aten/src/ATen/Context.cpp
aten/src/ATen/Context.h
aten/src/ATen/cuda/CUDABlas.cpp
torch/csrc/autograd/function.h

Cherry-picked into release/1.11 branch

rocblas alt impl during backward pass only

---

.circleci/docker/common/install_rocm.sh

Add amdgpu version support for ROCm5.1

---

.circleci/docker/common/install_rocm.sh

add fix to match the new rpm repo structure for rocm5.1

---

.circleci/docker/common/install_rocm.sh

Add ROCm5.1.1/AMDGPU support

---

tools/amd_build/build_amd.py
torch/utils/cpp_extension.py
torch/utils/hipify/hipify_python.py

These commits are required to build DeepSpeed without the hipify errors
https://github.com/ROCmSoftwarePlatform/pytorch/commit/a41829d9edd576775b68ca330799158960a8b766
https://github.com/ROCmSoftwarePlatform/pytorch/commit/663c7184629a0a721df540b74bcb78b1a66d0310
cc: @jeffdaily

Add hipify commits to rocm5.2 internal testing branch

---

aten/src/ATen/native/cuda/Indexing.cu
aten/src/ATen/native/cuda/MultinomialKernel.cu
aten/src/ATen/native/cuda/RangeFactories.cu
aten/src/ATen/native/cuda/Repeat.cu
aten/src/ATen/native/cuda/Sorting.cu
aten/src/ATen/native/cuda/TensorModeKernel.cu
aten/src/ATen/native/cuda/TensorTopK.cu
aten/src/ATen/native/sparse/cuda/SparseCUDAApplyUtils.cuh
aten/src/ATen/native/sparse/cuda/SparseCUDATensor.cu

Import the remaining navi changes

Rocm5.2 internal testing navi fix

---

test/test_optim.py

ROCm: Fix test_nadam

---

.circleci/docker/common/install_rocm.sh

Add ROCm5.1.3/AMDGPU support

---

test/test_torch.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-336376

[test_large_cumprod_cuda_float16]: Increase system memory requirement

---

.circleci/docker/common/install_rocm.sh

Add ROCm5.2.1/AMDGPU support

---

torch/utils/data/datapipes/datapipe.pyi.in

Fixes https://ontrack-internal.amd.com/browse/SWDEV-344032

TestTypeHints: Add Union type

---

tools/amd_build/build_amd.py

Remove duplicated hipification process
* Findrccl.cmake
* aten/src/ATen/hip/HIPConfig.h

Dedup hipify

---

test/test_multiprocessing.py

[SOW MS3]: Enable test_multiprocessing

---

test/jit/test_cuda.py
torch/csrc/jit/cuda/cuda.h
torch/csrc/jit/python/python_sugared_value.cpp
torch/csrc/jit/python/python_sugared_value.h
torch/csrc/jit/runtime/register_cuda_ops.cpp

This PR fixes the following tests
test_jit test_stream_args (jit.test_cuda.TestCUDA)
test_jit test_event_args (jit.test_cuda.TestCUDA)

[SOW MS3] Enable/fix unit tests test_stream_args and test_event_args

---

torch/testing/_internal/distributed/distributed_test.py

[SOW MS3] Enable test_ddp_profiling_torch_profiler

---

torch/testing/_internal/common_modules.py

enables test_memory_format batchnorm test

remove test_memory_format_nn_batchnorm rocm skip

---

aten/src/ATen/Context.cpp
aten/src/ATen/Context.h
aten/src/ATen/cuda/detail/CUDAHooks.cpp
aten/src/ATen/cuda/detail/CUDAHooks.h
aten/src/ATen/detail/CUDAHooksInterface.h
aten/src/ATen/detail/HIPHooksInterface.h
aten/src/ATen/native/LinearAlgebraUtils.h
aten/src/ATen/native/cuda/linalg/BatchLinearAlgebra.cpp
aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.cpp
aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.h
test/test_linalg.py
torch/testing/_internal/common_device_type.py

Fixes PyTorch UT linalg.svd_memory_allocation with a few workarounds.

[SOW MS3] Enable test_svd_memory_allocation

---

torch/utils/data/datapipes/datapipe.pyi.in

Fix https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2342

[SOW MS3] Fix test_doc_examples

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/MemoryAccess.cuh
aten/src/ATen/native/cuda/ROCmLoops.cuh
aten/src/ATen/native/cuda/Reduce.cuh
aten/src/ATen/native/cuda/ScanKernels.cu
aten/src/ATen/native/cuda/jit_utils.cpp
c10/util/Load.h

Port actual commit code of PR 78957 + exclude
torch/testing/_internal/common_methods_invocations.py so that actual tests are not modified.

[SOW MS3] Fix test_non_standard_bool_values_any_cuda_bool

---

.circleci/docker/common/install_rocm.sh

Add ROCm5.2.3/AMDGPU support

---

.circleci/docker/common/install_rocm.sh

Add ROCm5.2.3/AMDGPU support for PyTorch 1.12.1

---

aten/src/ATen/native/cuda/linalg/CUDASolver.h

@jithunnair-amd 
Made an error in previous commit due to a "find & replace" operation

Fix CONST_QUALIFIER definition

---

test/test_linalg.py
test/test_meta.py
torch/testing/_internal/common_utils.py

Fixes https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2397

[SOW MS3] Set magma backend for meta tests

---

torch/utils/data/datapipes/datapipe.pyi.in

To fix SWDEV-355068
Fixes #https://ontrack-internal.amd.com/browse/SWDEV-355068
Relevant upstream commit: https://github.com/pytorch/pytorch/commit/2f5d4cf90cbb61ca44b0ee5fe7dc0b878039b6b4

TestTypeHints: Add default_collate

---

test/test_ops.py

- updated condition for test_out and test_out_warnings to switch to magma backend only for linalg.svdvals, default hipSolver
- Increase the tolerance for test_out_addbmm_cpu_float32
One of fixes for https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2490

[SOW MS3] Few updates to UT execution

---

.circleci/docker/ubuntu-rocm/Dockerfile

fix the issue of missing required gfx arches in release/1.10 branch

---

.circleci/docker/build.sh
.circleci/docker/common/install_base.sh

This reverts commit a0cb328535706cb08f6219a3fac4b8514a04165d.

Revert "Enable ninja for ROCm (#1115)"

---

.circleci/docker/common/install_rocm.sh

Add ROCm5.3/AMDGPU support

---

related_commits

- Updated torchvision commit similar to ROCm 5.4 branch
With this change related_commits file in master and rocm5.4_internal_testing are in sync.

Updates to torchaudio/torchvision to related_commits

---

.gitmodules
torch/csrc/autograd/init.cpp

Fixes https://ontrack-internal.amd.com/browse/SWDEV-361878 and other profiling bugs.

Update to kineto with fixes

---

test/test_cuda.py
torch/cuda/graphs.py

@dllehr-amd Please review the conflict resolution. The below file shows the conflicts that arose during cherry-pick:
[conflicts.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/10080418/conflicts.txt)

[1.10.1] Fix for test_graph_make_graphed_callables

---

aten/src/ATen/cuda/Atomic.cuh

Remove use of atomicAddNoRet for fp32 ROCm

---

test/inductor/test_torchinductor.py

These skips are needed and are being tracked by the triton team.
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3414

skipping inductor test temporarily

---

torch/utils/hipify/hipify_python.py

* [ROCM] making cuSOLVER public

---

test/test_unary_ufuncs.py

Refer #884
Fixes https://ontrack-internal.amd.com/browse/SWDEV-365695

[ROCm]: Adjust tolerance level for reciprocal test

---

test/dynamo/test_backends.py
test/dynamo/test_export.py
test/inductor/test_smoke.py
test/inductor/test_torchinductor.py
test/inductor/test_torchinductor_opinfo.py

Makes skips/unskips for dynamo and inductor UTs.

Additional UT skips/unskips for ROCm

---

test/test_unary_ufuncs.py

Adjust tolerance level for reciprocal test

---

.jenkins/pytorch/test.sh

call install_filelock before install_triton
To fix https://ontrack-internal.amd.com/browse/SWDEV-384803

call filelock function

---

test/test_unary_ufuncs.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-385058

test_unary_ufuncs: Import TEST_WITH_ROCM variable

---

test/test_nn.py

Fixes [SWDEV-388746](https://ontrack-internal.amd.com/browse/SWDEV-388746) by adding tolerance.

Added tolerance to test_Conv2d_groups_nobias_v2

---

test/profiler/test_memory_profiler.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-384835
Related upstream PR: https://github.com/pytorch/pytorch/pull/96752

Fixed test_memory_timeline in rocm5.6_internal_testing

---

aten/src/ATen/cuda/CUDASparse.h
aten/src/ATen/cuda/CUDASparseDescriptors.h

conditionally enable hipsparse const descriptors

---

tools/testing/test_selections.py

Limiting the num_procs to 8

---

aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.cpp

It seems after some point we are not longer calling our math library functions for `lstsq` kernel.
Tested with the following command:
```
export PYTORCH_TEST_WITH_ROCM=1
export HSA_FORCE_FINE_GRAIN_PCIE=1  # See https://ontrack-internal.amd.com/browse/SWDEV-415634
#export HIP_VISIBLE_DEVICES=0,1  # for distributed UTs
export HIP_VISIBLE_DEVICES=0  # Required by all other single-GPU UTs, at least for now, See https://ontrack-internal.amd.com/browse/SWDEV-407054 for why
export PYTORCH_TESTING_DEVICE_ONLY_FOR="cuda" # to skip all CPU tests
python3 test/run_test.py -i test_linalg functorch/test_ops test_ops_fwd_gradients test_ops_gradients functorch/test_vmap --verbose -k 'lstsq'
```
All selected tests passed.
```
=============== 24 passed, 4 skipped, 9730 deselected in 13.79s …
```

Fix lstsq related regressions (part of SWDEV-392820)

---

.circleci/docker/centos-rocm/Dockerfile
.circleci/docker/common/install_rocm_magma.sh
.circleci/docker/ubuntu-rocm/Dockerfile
cmake/public/LoadHIP.cmake
torch/utils/hipify/cuda_to_hip_mappings.py

Verified CI jobs run successfully: http://rocm-ci.amd.com/job/mainline-framework-pytorch-ci/1276/

ROCm6.0 ecosystem supports in release/1.13 branch

---

test/profiler/test_memory_profiler.py

Fixes JIRA ticket SWDEV-416490
Upstream PR: 108010

Increased logging threshold for profiler matching

---

.circleci/docker/common/install_base.sh
.circleci/docker/common/install_conda.sh
cmake/Dependencies.cmake

- Fortran package installation moved after gcc
- Update libtinfo search code in cmake1
- Install libstdc++.so

Updates to build on Jammy

---

.ci/docker/common/install_rocm.sh

Support ROCm5.7 installation in Ubuntu22.04

---

aten/src/ATen/cuda/CUDABlas.cpp
aten/src/ATen/cuda/CUDABlas.h
aten/src/ATen/cuda/Exceptions.h
aten/src/ATen/native/cuda/linalg/BatchLinearAlgebra.cpp
aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.h
aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLibBlas.cpp
test/test_linalg.py
torch/utils/hipify/cuda_to_hip_mappings.py

Fixing the wrong cherry-picks by revert few commits
- https://github.com/ROCmSoftwarePlatform/pytorch/commit/5cf78070341d9818e9982e1d9d8448997681f034
- https://github.com/ROCmSoftwarePlatform/pytorch/commit/146e291f9dfa30818643223ec65f5207e2c41bb8
Updated changes
- https://github.com/ROCmSoftwarePlatform/pytorch/commit/e3a6481d69eee1fd2fe35b8f8fdbb35f43e0e0fb

Correcting the linalg batched cherry-picks

---

.circleci/docker/common/install_protobuf.sh
torch/utils/tensorboard/summary.py

PYTORCH_TEST_WITH_ROCM=1 python3 test/run_test.py -i test_tensorboard -v
This PR will fix the following errors:
ERROR [0.001s]: test_image_with_3_channel_batched (__main__.TestTensorBoardSummary)
ERROR [0.001s]: test_image_with_boxes (__main__.TestTensorBoardSummary)
ERROR [0.000s]: test_image_with_one_channel (__main__.TestTensorBoardSummary)
ERROR [0.000s]: test_image_with_one_channel_batched (__main__.TestTensorBoardSummary)
ERROR [0.001s]: test_image_without_channel (__main__.TestTensorBoardSummary)
ERROR [0.012s]: test_writer (__main__.TestTensorBoardWriter)

Updated ANTIALIAS to Resampling.LANCZOS

---

c10/cuda/CUDACachingAllocator.cpp

Unrecognized CachingAllocator option: release_lock_on_cudamalloc
Manual cherry-pick of https://github.com/pytorch/pytorch/pull/110715.

fix swdev-428661

---

test/inductor/test_inductor_freezing.py
test/inductor/test_pattern_matcher.py
test/inductor/test_torchinductor.py

Disable several inductor UTs as they were already disabled by upstream right after we branched off for rocm6.0 due to flakiness.

[SWDEV-418929] - Disable several inductor UTs

---

test/profiler/test_profiler.py
test/profiler/test_profiler_tree.py

Fixed following unit tests:
profiler/test_profiler.py: test_kineto (main.TestProfiler)
profiler/test_profiler_tree.py: test_profiler_experimental_tree (main.TestProfilerTree)

Additional fix for some unit tests

---

.ci/docker/centos-rocm/Dockerfile.centos.stream
.ci/docker/common/install_base.sh
.ci/docker/common/install_rocm.sh

- Add missing common_utils.sh
- Update the install vision part
- Move to amdgpu rhel 9.3 builds
- Update to pick python from conda path
- Add a missing package
- Add ROCM_PATH and magma
- Updated repo radeon path

[CS9] Updates to CentOS stream 9 build

---

torch/csrc/jit/codegen/fuser/codegen.cpp
torch/csrc/jit/codegen/fuser/cuda/resource_strings.h

[ROCm] int64_t added for JIT codegen

---

related_commits

Updating APEX version in related_commeit file to 1.0.0

Setting APEX version to 1.0.0

---

related_commits

Setting APEX version to 1.1.0

---

.circleci/docker/common/install_protobuf.sh

Install protobuf v3.20.2 for the consistency with other branches

---

torch/testing/_internal/distributed/distributed_test.py

Skips required to resolve SWDEV-371309. Same issue as https://github.com/ROCmSoftwarePlatform/pytorch/pull/1335 https://github.com/ROCmSoftwarePlatform/pytorch/pull/1302
Tracked on upstream issue: https://github.com/pytorch/pytorch/issues/111834

DDP hook skips on 1.13 branch 

---

test/distributed/fsdp/test_fsdp_overlap.py
test/test_nn.py
torch/testing/_internal/distributed/distributed_test.py

Fixes SWDEV-435187 and SWDEV-435180

Skipped known unit test failures

---

aten/src/ATen/Context.cpp
aten/src/ATen/Context.h
aten/src/ATen/autocast_mode.cpp
aten/src/ATen/autocast_mode.h
aten/src/ATen/core/TensorBase.h
aten/src/ATen/cuda/CUDABlas.cpp
aten/src/ATen/cuda/CUDABlas.h
aten/src/ATen/cuda/CUDAContext.h
aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/native/ConvUtils.h
aten/src/ATen/native/LinearAlgebra.cpp
aten/src/ATen/native/TensorShape.cpp
aten/src/ATen/native/cuda/Blas.cpp
aten/src/ATen/native/cuda/f8_hip_impl.cu
aten/src/ATen/native/cuda/f8_hip_impl.cuh
aten/src/ATen/native/miopen/Conv_miopen.cpp
aten/src/ATen/native/utils/ParamUtils.h
c10/core/TensorImpl.cpp
c10/core/TensorImpl.h
torch/csrc/autograd/FunctionsManual.cpp

Initial F8 support

---

related_commits

Update apex commit

---

related_commits

Moving APEX to the 1.3 version with HIPBLAS changes.

moving apex to 1.3

---

requirements.txt

For https://ontrack-internal.amd.com/browse/SWDEV-386378

Add ninja, pytest, scipy to requirements.txt for release/1.10.1

---

requirements.txt

For https://ontrack-internal.amd.com/browse/SWDEV-386378

add hypothesis ninja pytest scipy to requirements.txt for release/1.12

---

test/inductor/test_torchinductor_opinfo.py
torch/testing/_internal/common_utils.py

Fixes [SWDEV-448371](https://ontrack-internal.amd.com/browse/SWDEV-448371) and [SWDEV-448395](https://ontrack-internal.amd.com/browse/SWDEV-448395)

Converted NAVI check as a function

---

test/inductor/test_kernel_benchmark.py

Skip test_mm_triton_kernel_benchmark

---

test/inductor/test_torchinductor.py

[SWDEV-444963] skip test_roi_align

---

test/test_matmul_cuda.py

Bringing changes from https://github.com/ROCm/pytorch/commit/2ea2421b44e6e064d5c8407daba4152a6d706623#diff-3f31c52b48cfddf8f4617d809f7695b2e4a1c78656f8c4b5143a4b45d01fcf23.
to release/2.1

Skip test for fp16

---

test/inductor/test_max_autotune.py

[SWDEV-450461] test_max_autotune.py: Add missing HAS_CPU import

---

test/test_matmul_cuda.py

Getting PR https://github.com/ROCm/pytorch/pull/1255 to ROCM6.2_internal_testing

PR #1255 to rocm6.2 release

---

test/profiler/test_profiler.py
torch/testing/_internal/common_utils.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-440517 profiler/test_profiler.py::TestProfiler::test_oom_tracing in release/1.13 branch.

Added a fraction parameter for profiler_oom_tracing

---

test/distributed/_tensor/test_attention.py

The UT does not skip efficient attention operator on platforms that do not support efficient attention. Support of flash attention does not always ensure efficient attention is implemented.
Fixes #SWDEV-459621

Fix SWDEV-459621.

---

caffe2/CMakeLists.txt
torch/csrc/distributed/c10d/intra_node_comm.cpp
torch/csrc/distributed/c10d/intra_node_comm.cu

Required for https://ontrack-internal.amd.com/browse/SWDEV-464040

[ROCm] Intra-node all reduce initial implementation

---

related_commits

Include fixes from https://github.com/ROCm/apex/pull/133

[release/2.3] Update apex branch and commit

---

torch/cuda/__init__.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-468372 and https://ontrack-internal.amd.com/browse/SWDEV-469474
Will upstream along with some changes to AMDSMI handling to HIP_VISIBLE_DEVICES shortly

Support 6.2 AMDSMI API changes for clock speed

---

aten/src/ATen/cuda/CUDABlas.cpp
aten/src/ATen/native/hip/ck_gemm.h
aten/src/ATen/native/hip/ck_gemm.hip

CK gemm header

---

aten/src/ATen/cuda/CUDABlas.cpp
aten/src/ATen/native/hip/ck_gemm.h
aten/src/ATen/native/hip/ck_gemm.hip

Ck template

---

aten/src/ATen/cuda/CUDABlas.cpp
aten/src/ATen/native/hip/ck_gemm.hip
test/test_linalg.py

Includes rudimentary sanity test

Float CK GEMM backend - Initial prototype

---

requirements.txt
setup.py

(cherry picked from commit 1feb1a81136120c40dd0e68d38829109eb16af03)
limit sympy version to 1.12.1

[release/2.3] limit sympy version to 1.12.1 or lower

---

requirements.txt
setup.py

(cherry picked from commit 1feb1a81136120c40dd0e68d38829109eb16af03)
limit sympy version to 1.12.1

[release/2.1] limit sympy version to 1.12.1 or lower

---

requirements.txt
setup.py

(cherry picked from commit 1feb1a81136120c40dd0e68d38829109eb16af03)

[release/2.0] limit sympy version to 1.12.1 or lower

---

related_commits

Updating related commit to pull in Megatron supported seq-length >= 2k

updating apex commit

---

related_commits

[NO CP] Update the apex commit

---

.ci/docker/build.sh

Requested by @kiran-thumma for http://rocm-ci.amd.com/job/mainline-framework-pytorch-2.3-ub24-py3.12-ci/

Add Ubuntu 24.04 support to docker build script

---

test/test_linalg.py

Only run CK tests on ROCm

---

test/distributed/test_c10d_nccl.py

SWDEV-475455 and SWDEV-473434. 
NCCl Scan was initiated a bit early.

nccl dump wait delay

---

test/distributed/test_c10d_nccl.py

Nccl scan time issue 2.3

---

torch/testing/_internal/distributed/distributed_test.py

skip test_DistributedDataParallel

---

test/test_nn.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-466009

[release/2.3] Fix for SWDEV-466009 

---

test/test_nn.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-466009

[release/2.2] Fix for SWDEV-466009

---

test/distributed/test_c10d_gloo.py

Fixes SWDEV-440592's [comment](https://ontrack-internal.amd.com/browse/SWDEV-440592?focusedId=16795173&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16795173)

Skip test_reduce_stress_cuda

---

test/dynamo/test_structured_trace.py
test/test_fx.py

Imported skipIfRocm in certain test suites

---

requirements.txt

Cherry pick https://github.com/pytorch/pytorch/pull/133235
Fixes SWDEV-473498

[SWDEV-473498] Pin sympy for >=python3.9

---

.automation_scripts/parse_xml_results.py
.automation_scripts/run_pytorch_unit_tests.py
test/run_test.py

Fixes SWDEV-475071: https://ontrack-internal.amd.com/browse/SWDEV-475071

Several issues fix of QA helper script

---

.ci/docker/requirements-ci.txt

this PR add tlparse==0.3.7 into requirementss-ci.txt 
fix dynamo/test_structured_trace.py
Error message: FileNotFoundError: [Errno 2] No such file or directory: 'tlparse'
Fixes: https://ontrack-internal.amd.com/browse/SWDEV-480494

[rocm6.2_internal_testing] revert revert add tlparse into requirements-ci.txt

---

torch/testing/_internal/distributed/nn/api/remote_module_test.py

[release/2.3] Fixed error string assertion in test_invalid_devices

---

test/distributed/test_c10d_gloo.py

Skip unit test

---

torch/testing/_internal/distributed/nn/api/remote_module_test.py

[release/2.2] Fixed error string assertion in test_invalid_devices

---

torch/testing/_internal/distributed/nn/api/remote_module_test.py

[release/2.4] Fixed error string assertion in test_invalid_devices

---

torch/testing/_internal/distributed/nn/api/remote_module_test.py

[release/2.1] Fixed error string assertion in test_invalid_devices

---

aten/src/ATen/native/transformers/hip/flash_attn/flash_api.hip

Fix faulty conflict merge when cherry-picking https://github.com/ROCm/pytorch/commit/aea038675ddb56a473066ca7d0ef80d345ce2123 to rocm6.3_internal_testing

[rocm6.3_internal_testing] Fix SWDEV-459623 - 2

---

aten/src/ATen/native/cuda/Reduce.cuh

Release version of upstream PR [137737](https://github.com/pytorch/pytorch/pull/137737).
This has added support for GPUs with smaller number of CUs.  
Will upstream the smaller CU optimization later, once it is baked in release branch.

Performance tuning sum reduce for 1D and 2D tensors

---

tools/testing/target_determination/heuristics/historical_class_failure_correlation.py

Extract qualified_test_class with correct format only

---

aten/src/ATen/native/cuda/Indexing.cu

On ROCm, hipification converts std::min to ::min, but ::min is not returning the right result. This impacts index_add_ operation on a large tensor, we end up picking the large values instead of max supported block size (128). This leads to GPU accessing memory out of bounds.
While we wait for ::min to be fixed, we can use < operator to compare instead of relying on ::min.
Example Code w/ failure:
```
D=6144
hidden_states = torch.zeros([16384, 6144],           device="cuda:0", dtype=torch.bfloat16)
index         = torch.randint(0, 16384, (1, 32, 16384), device="cuda:0", dtype=torch.int64)
output        = torch.empty([1, 32, 16384, 6144],    device="cuda:0", dtype=torch.bfloat16)
hidden_states.index_add_(0, index.view(-1), output.view(-1, D))
```
``` …
```

[release/2.4][ROCm] Fix largeIndexBlockSize

---

aten/src/ATen/cuda/tunable/GemmCommon.h

Fixes #139116.  Also fixes other unreported issues with torch.bmm due to incorrect size calculations. Pull Request resolved: https://github.com/pytorch/pytorch/pull/139137 Approved by: https://github.com/yoyoyocmu

[release/2.4] TunableOp use dense size calculations as minimum sizes (#139137)

---

test/distributed/test_c10d_nccl.py

FBCODE internally uses ncclCommCreateFromRanks in nccl version 2.21+, which doesn't include inactive ranks in the split and therefore the expected count at this point is 0 for all ranks.
However, externally even for nccl version 2.21+, we use ncclCommSplit, which includes all ranks in the split, the inactive ones are used with NOCOLOR. Therefore, rank 0 will have a split of 0 as it has not done a comm yet and rank 1 will have a split of 1 (inactive though).
This change allows the UT to run for both cases.
This change was brought into release/2.4 branch via https://github.com/ROCm/pytorch/commit/8830b812081150be7e27641fb14be31efbf7dc1e

[release/2.4][SWDEV-493252] Fix for test_c10d_nccl.py:test_comm_split_subgroup

---

aten/src/ATen/cuda/tunable/GemmCommon.h
test/test_linalg.py

Fixes #140278
Upstream PR: https://github.com/pytorch/pytorch/pull/140673
cc: @jeffdaily

[UP CP] TunableOp fix for batched MM with views.

---

test/test_transformers.py

skipping tests in `test_transformers.py` for release/2.4:
- test_flash_atteention_large_bf16_nan_values_cuda
- test_multiheadattention_fastpath_attn_mask_attn_mask_dim_2_key_padding_mask_dim_2_bool_cuda
- test_multiheadattention_fastpath_attn_mask_attn_mask_dim_3_key_padding_mask_dim1_bool_cuda
- test_multiheadattention_fastpath_attn_mask_attn_mask_dim_3_key_padding_mask_dim_2_bool_cuda
- test_transformerencoder_fastpath_use_torchscript_False_enable_nested_tensor_False_use_autocast_False_d_model_12_cuda
- test_transformerencoder_fastpath_use_torchscript_False_enable_nested_tensor_False_use_autocast_False_d_model_256_cuda
- test_transformerencoder_fastpath_use_torchscript_False_enable_nested_tensor_True_use_autocast_False_d_model_12_cuda
- …

[release/2.4] skip failed tests in test_transformers.py

---

test/nn/test_multihead_attention.py

Fix the unit test test_multihead_self_attn_two_masks_fast_path - specify add_bias_kv and need_weights parameters for torch.nn.MultiheadAttention so that it provide same output as torch.nn.functional.multi_head_attention_forward

[Release/2.4] Unit test - test_multihead_self_attn_two_masks_fast_path missing parameters

---

aten/src/ATen/native/cuda/layer_norm_kernel.cu
torch/cuda/__init__.py

Cherry pick amdsmi fix: https://github.com/pytorch/pytorch/commit/04f569a5246850b57748a86fd16a5bae02bd9d72
Cherry pick layer_norm accuracy fix: https://github.com/pytorch/pytorch/commit/001f7366a71cd19e4b460624ab76053225c8676e

[release/2.4] AMDSMI/layernorm cherry picks

---

aten/src/ATen/native/cuda/jit_utils.cpp
aten/src/ATen/native/cuda/thread_constants.h

Cherry-pick of https://github.com/ROCm/pytorch/pull/1734

[AUTOGENERATED] [release/2.5] Set thread work size to 8 for elementwise kernels

---

aten/src/ATen/native/cuda/Blas.cpp

Ported patch from https://patch-diff.githubusercontent.com/raw/pytorch/pytorch/pull/137604.patch

[release/2.5] [AMD] Unify cublaslt and hipblaslt path

---

aten/src/ATen/native/cuda/Reduce.cuh

Cherry-pick of https://github.com/ROCm/pytorch/pull/1646

[AUTOGENERATED] [release/2.5] Performance tuning sum reduce for 1D and 2D tensors

---

related_commits

Update related_commits to pick up apex version update

Update related_commits to pick up apex version update

---

aten/src/ATen/native/cuda/Reduce.cuh

Improve performance of reduce sum for 3D shapes.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/143137
Approved by: https://github.com/jeffdaily, https://github.com/eqy

[ROCm] Improve performance of reduce sum for 3D shapes (#143137)

---

aten/src/ATen/native/cuda/Reduce.cuh

Cherry-pick of https://github.com/ROCm/pytorch/pull/1839

[AUTOGENERATED] [release/2.5] [ROCm] Improve performance of reduce sum for 3D shapes (#143137)

---

cmake/External/aotriton.cmake

Bump AOTriton to 0.8.2b

---

torch/_inductor/autotune_process.py
torch/_inductor/kernel/conv.py
torch/_inductor/kernel/mm_common.py
torch/_inductor/runtime/triton_heuristics.py
torch/_inductor/select_algorithm.py

Reverts ROCm/pytorch#1826
Since this PR requires more than these cherry-picks and might require changes related to 2.6 PT as well. Reverting this for now.

Revert "Cherry-pick PR #143286 triton gemm tuning parameters. "

---

aten/src/ATen/native/cuda/Blas.cpp
test/test_linalg.py

Port the PR https://github.com/pytorch/pytorch/pull/138267 from upstream main to fix the error
"RuntimeError: Attempting to use hipBLASLt on a unsupported architecture!"

[release/2.5] Fix ADDMM hipBLASLt regression

---

aten/src/ATen/Context.cpp
aten/src/ATen/cuda/CUDABlas.cpp
test/dynamo/test_graph_region_tracker.py
test/dynamo/test_misc.py
test/test_cuda.py
torch/utils/hipify/cuda_to_hip_mappings.py

[reland][AMD] Turn on TF32 for aten::mm

---

aten/src/ATen/miopen/miopen-wrapper.h

missing miopen version.h

---

aten/src/ATen/native/cuda/Reduce.cuh

Tune 3D tensor sums when not using fastest dimension.

[ROCm] Tune 3d tensor sums when not using fastest dimension

---

test/test_ops.py

Skip non_standard_bool_values tests

---

test/test_ops.py

[rocm6.4_internal_testing] Skip non_standard_bool_values tests

---

related_commits

[Release/2.5] Update Apex commit to append git commit to apex wheel name

---

.github/scripts/build_triton_wheel.py
related_commits

Relates to:
https://github.com/ROCm/rocAutomation/pull/660/files
Validation:
http://ml-ci-internal.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/526/

[Release/2.0] triton git commit

---

.github/scripts/build_triton_wheel.py
related_commits

Relates to:
Validation:
http://ml-ci-internal.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/527/

[Release/2.2] triton git commit

---

.github/scripts/build_triton_wheel.py
related_commits

Relates to:
Validation:
http://ml-ci-internal.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/533/

[Release/2.3]triton git commit

---

.github/scripts/build_triton_wheel.py
related_commits

Relates to:
Validation:
http://ml-ci-internal.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/529/

[Release/2.4] triton git commit

---

aten/src/ATen/native/Normalization.cpp

env var PYTORCH_MIOPEN_SUGGEST_NHWC_BATCHNORM=1 enables NHWC batchnorm separately from convolution

add separate environment variable to enable NHWC batchnorm

---

aten/src/ATen/native/cuda/Indexing.cu

This reverts commit a6f1375d8e831c52e1a7b15d89763764e0ab7c90. 
We have a better fix that is being validated (https://github.com/pytorch/pytorch/pull/146420)

Revert "[ROCm] Indexing perf optimization via Unroll/WideFetch/IdxReuse/OneDupOpt (#1897)"

---

aten/src/ATen/native/cuda/TensorTopK.cpp
aten/src/ATen/native/cuda/TensorTopK.cu

mirroring https://github.com/pytorch/pytorch/pull/146387 for release/2.5
contains two PR's:
* https://github.com/pytorch/pytorch/pull/145536
* https://github.com/pytorch/pytorch/pull/146387

[release/2.5] [ROCm] TopK optimizations for AMD GPUs #146387

---

aten/src/ATen/native/cuda/Copy.cu

This PR cherry-picks all the aten::copy optimization from 2.5_perf_fix branch into 2.5 release branch. 
cc: @coderfeli

[release/2.5] aten::copy optimization.

---

aten/src/ATen/native/cuda/TensorTopK.cpp
aten/src/ATen/native/cuda/TensorTopK.cu

mirroring https://github.com/pytorch/pytorch/pull/146387 for release/2.6
contains two PR's:
https://github.com/pytorch/pytorch/pull/145536
https://github.com/pytorch/pytorch/pull/146387

[release/2.6] [ROCm] TopK optimizations for AMD GPUs #146387

---

test/test_linalg.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/1888

[AUTOGENERATED] [release/2.6] Cherry-pick PR-1888

---

related_commits

https://github.com/ROCm/apex/commit/b8ad311e75cd03d1c6510453745169121587266d

[rocm6.4_internal_testing] Update related_commits

---

aten/src/ATen/native/cuda/CUDALoops.cuh

strided kernel implementation was causing performance regression

[ROCm] Revert strided kernel implementation

---

aten/src/ATen/native/transformers/hip/flash_attn/flash_api.hip

Fix TORCH_CHECK for head dimensions

---

related_commits

Relates to https://github.com/ROCm/vision/commit/c77cacdac23de9b091bada794b945b5caaa642fe
Cherry pick of this https://github.com/pytorch/vision/pull/8982
https://ontrack-internal.amd.com/browse/SWDEV-522276
Validation::
http://rocm-ci.amd.com/job/pytorch2.0-manylinux-wheels_rel-6.4/22/

[release/2.0] Update related_commits for vision

---

aten/src/ATen/native/transformers/hip/flash_attn/aot/mha_all_aot.hip

Cherry-picked from https://github.com/ROCm/pytorch/pull/1953 into release/2.6
Fixes #SWDEV-514723

[Release/2.6] Fix TORCH_CHECK for head dimensions

---

related_commits

[Release 2.6] Fix wrong related commits 

---

related_commits

Porting Distributed_fused_ADAM and Distributed_fused_LAMB
Commit : https://github.com/ROCm/apex/commit/69ee42b272179fa3091211309d1f5e61b5167282

[release/2.6] Update related_commits

---

.ci/docker/centos-rocm/Dockerfile
.ci/docker/common/install_conda.sh
.ci/docker/ubuntu-rocm/Dockerfile

Cherry-pick of https://github.com/ROCm/pytorch/pull/2033

[AUTOGENERATED] [release/2.5] Use miniforge instead of miniconda; pin to CMake 3.x; install sqlite

---

aten/src/ATen/cuda/tunable/GemmHipblaslt.h
aten/src/ATen/cuda/tunable/GemmRocblas.h
aten/src/ATen/cuda/tunable/StreamTimer.cpp
aten/src/ATen/cuda/tunable/StreamTimer.h
aten/src/ATen/cuda/tunable/TunableGemm.h
aten/src/ATen/cuda/tunable/TunableOp.h

Cherry-pick of https://github.com/ROCm/pytorch/pull/2018

[AUTOGENERATED] [release/2.6][ROCm][TunableOp] Improve identification of fastest solution (#144942)

---

aten/src/ATen/cuda/tunable/TunableOp.h

Cherry-pick of https://github.com/ROCm/pytorch/pull/2017

[AUTOGENERATED] [release/2.6][ROCm][TunableOp] Fix TunableOp warmup environment variable. (#147412)

---

aten/src/ATen/native/cuda/DilatedMaxPool2d.cu

Cherry-pick of https://github.com/pytorch/pytorch/pull/151727

[ROCm] Maxpool forward NHWC Perf Improvement targeting Resnet scenarios

---

test/inductor/test_fused_attention.py
test/inductor/test_torchinductor.py
torch/_inductor/fx_passes/fuse_attention.py
torch/_meta_registrations.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2050

[AUTOGENERATED] [rocm6.4_internal_testing] [ROCm] Update meta_registration for efficient attention (#146979)

---

related_commits

updating following commit - 
1) Update distributed fused adam - integrate Pipeline operations and support different grad - https://github.com/ROCm/apex/commit/8870f33104efb9f7f307ee1374151b365d6823d4
2) Remove the condition of pytorch equal to 2.6 for building the NCCL allocator in release/1.7 branch -  https://github.com/ROCm/apex/commit/1fb3cc4c76c7a60a51ea94a1b30b2c38f4d82476
3) Optimize the memory for fused_weight_gradient_mlp_cuda module https://github.com/ROCm/apex/commit/cf311e7b94f5f700a1876ed06073d3e241a51700
Fixes [SWDEV-502615](https://ontrack-internal.amd.com/browse/SWDEV-502615)

[release/2.7] Update related_commits

---

aten/src/ATen/native/cuda/DilatedMaxPool2d.cu

Cherry-pick of https://github.com/pytorch/pytorch/pull/152267

[ROCm] Maxpool backward NHWC Perf Improvement targeting Resnet scenarios

---

related_commits

updating following commit - 
1) Update distributed fused adam - integrate Pipeline operations and support different grad - https://github.com/ROCm/apex/commit/09ffa0ad472ad4d8663668dfb282973908ccd9aa
2) [Update the condition for building the NCCL allocator, PyTorch should be greater than or equal to 2.6 (](https://github.com/ROCm/apex/commit/65f458408b3d55ecad2feb7c945c9608fad266fd)
3) Optimize the memory for fused_weight_gradient_mlp_cuda module https://github.com/ROCm/apex/commit/667af654f73d4aea00657659bfefcf95e725898b
Fixes [SWDEV-502615](https://ontrack-internal.amd.com/browse/SWDEV-502615)

[rocm6.5_internal_testing] Update related_commits

---

aten/src/ATen/native/cuda/DilatedMaxPool2d.cu

Cherry-pick of https://github.com/ROCm/pytorch/pull/2054

[AUTOGENERATED] [release/2.6] [ROCm] Maxpool forward NHWC Perf Improvement targeting Resnet scenarios

---

.ci/docker/common/install_conda.sh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2045

[AUTOGENERATED] [release/2.3] [release/2.4] Conditionalize versioning for conda

---

aten/src/ATen/native/cuda/DilatedMaxPool2d.cu

Cherry-pick of https://github.com/ROCm/pytorch/pull/2060

[AUTOGENERATED] [release/2.6] [ROCm] Maxpool backward NHWC Perf Improvement targeting Resnet scenarios

---

aten/src/ATen/native/cuda/DilatedMaxPool2d.cu

Cherry-pick of https://github.com/ROCm/pytorch/pull/2054

[AUTOGENERATED] [release/2.7] [ROCm] Maxpool forward NHWC Perf Improvement targeting Resnet scenarios

---

aten/src/ATen/native/cuda/DilatedMaxPool2d.cu

Cherry-pick of https://github.com/ROCm/pytorch/pull/2060

[AUTOGENERATED] [release/2.7] [ROCm] Maxpool backward NHWC Perf Improvement targeting Resnet scenarios

---

aten/src/ATen/native/cuda/DilatedMaxPool2d.cu

Cherry-pick of https://github.com/ROCm/pytorch/pull/2081

[AUTOGENERATED] [release/2.6] [ROCm] Update maxpool launch config

---

torch/_dynamo/graph_region_tracker.py

Fixes dynamo.test_graph_region_tracker - test_mismatched_global_state which expects the results to be topologically sorted.
Based on upstream PR: https://github.com/pytorch/pytorch/pull/143523
No CP needed for other branches.

[NO CP] [release/2.6] Implemented topological sort for graph_region_tracker to fix test_mismatched_global_state

---

aten/src/ATen/native/cuda/KernelUtils.cuh

This PR is a cherry-pick of upstream PR: https://github.com/pytorch/pytorch/pull/152841 + some missing commits from: https://github.com/pytorch/pytorch/pull/146264

[release/2.5] opportunistic fastatomics - coalesced access + fix build error with newer compilers

---

.ci/pytorch/common_utils.sh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2103

[AUTOGENERATED] [release/2.5] Remove --no-index and --no-deps flags

---

related_commits

Updated the release notes in readme - https://github.com/ROCm/apex/commit/85c7a80b76b2ebcec9b120fc6da01400f12905b8

[release/2.5] Update related_commits

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/MemoryAccess.cuh

* Use non-temporal loads to improve the in-place vectorized elemwise kernel performance on MI300

[ROCm] Improve in-place vectorized elemwise kernel performance on MI300

---

.ci/pytorch/common_utils.sh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2103 
Validation: http://rocm-ci.amd.com/blue/organizations/jenkins/framework-pytorch-2.3-ub24-py3.12-ci_rel-6.4/detail/framework-pytorch-2.3-ub24-py3.12-ci_rel-6.4/22/pipeline

[AUTOGENERATED] [release/2.3] Remove --no-index and --no-deps flags

---

aten/src/ATen/native/cuda/Blas.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2158 

[AUTOGENERATED] [release/2.7] [release/2.6] Change gfx110x BLAS preferred backend (Take 2)

---

.github/scripts/amd/package_triton_wheel.sh
.github/scripts/amd/patch_triton_wheel.sh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2130
Validation: http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder-lw/156/

[AUTOGENERATED] [release/2.5] Make triton build ROCm version agnostic

---

test/inductor/test_decompose_mem_bound_mm.py
torch/testing/_internal/common_utils.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2129 

[AUTOGENERATED] [release/2.7] test_decompose_mem_bound_mm.py tolerance increase for navi3x

---

test/inductor/test_decompose_mem_bound_mm.py
torch/testing/_internal/common_utils.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2129 

[AUTOGENERATED] [rocm6.5_internal_testing] test_decompose_mem_bound_mm.py tolerance increase for navi3x

---

aten/src/ATen/Context.cpp
aten/src/ATen/native/cuda/Blas.cpp

Ported from upstream https://patch-diff.githubusercontent.com/raw/pytorch/pytorch/pull/150250.patch and fixed patch error

ROCm: Add trailing comma for consistency in gfx architecture

---

.github/scripts/amd/package_triton_wheel.sh
.github/scripts/amd/patch_triton_wheel.sh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2130

[AUTOGENERATED] [rocm6.5_internal_testing] Make triton build ROCm version agnostic

---

aten/src/ATen/native/cuda/Reduce.cuh

[ROCm] Fix 3D tensor perf degradation with NHWC format

---

aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/miopen/Handle.h
aten/src/ATen/miopen/Types.h

Cherry-pick of https://github.com/ROCm/pytorch/pull/2176

[AUTOGENERATED] [2.6_commit8d72c03_reverted] [release/2.6] Exposing Some MIOpen Symbols

---

.ci/docker/build.sh
.ci/docker/common/install_rocm_magma.sh
.ci/docker/ubuntu-rocm/Dockerfile

Fixes 
- [swdev-532390](https://ontrack-internal.amd.com/browse/SWDEV-532390)
- [swdev-532156](https://ontrack-internal.amd.com/browse/SWDEV-532156)
hipblas - V2 removal PR - https://github.com/ROCm/hipBLAS/pull/982

Move to Magma private github repo

---

aten/src/ATen/native/cuda/Reduce.cuh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2175

[AUTOGENERATED] [release/2.5] [ROCm] Fix 3D tensor perf degradation with NHWC format

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/MemoryAccess.cuh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2185 

[AUTOGENERATED] [release/2.7] [ROCm] Improve vectorized elementwise kernel performance in MI300X

---

torch/testing/_internal/common_utils.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2181

[AUTOGENERATED] [rocm6.5_internal_testing] import 'Dict' to fix common_utils.py

---

aten/src/ATen/cuda/tunable/GemmHipblaslt.h

Fixes http://rocm-ci.amd.com/blue/organizations/jenkins/rocm-pytorch-manylinux-wheel-builder/detail/rocm-pytorch-manylinux-wheel-builder/2084/pipeline/130/
Validation:
http://rocm-ci.amd.com/job/mainline-pytorch2.5-manylinux-wheels/368/

[release/2.5] Change from hipblasDatatype_t to hipDataType

---

test/dynamo/test_activation_checkpointing.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-480138

[SWDEV-480138] - skip UT if no flash/cudnn attention

---

aten/src/ATen/native/ConvUtils.h
aten/src/ATen/native/Convolution.cpp
aten/src/ATen/native/Normalization.cpp
aten/src/ATen/native/miopen/Conv_miopen.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2209

[release/2.7] [SWDEV-535259] enable miopen channels last 3d for conv and batchnorm

---

test/test_nn.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2214

[AUTOGENERATED] [release/2.7] Add 3D batchnorm tests

---

aten/src/ATen/cuda/tunable/GemmHipblaslt.h

Cherry-pick of https://github.com/ROCm/pytorch/pull/2205 
Reopening this PR because of https://ontrack-internal.amd.com/browse/SWDEV-536013

[AUTOGENERATED] [release/2.4] [release/2.5] Change from hipblasDatatype_t to hipDataType

---

aten/src/ATen/native/cuda/SoftMax.cu

Backport PR https://github.com/pytorch/pytorch/pull/154778 (without adding the tests)

[Release/2.7] Backport softmax fixes from 2.8dev

---

test/inductor/test_cooperative_reductions.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2204

[AUTOGENERATED] [release/2.7] [release/2.6] [SWDEV-529824] Fix Float16 CooperativeReduction Test Failure

---

aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/miopen/Handle.h
aten/src/ATen/miopen/Types.h

Cherry-pick of https://github.com/ROCm/pytorch/pull/2219

[AUTOGENERATED] [rocm7.0_internal_testing] [rocm6.5_internal_testing] Exposing Some MIOpen Symbols (#2176) (#154545)

---

test/inductor/test_aot_inductor.py
test/inductor/test_torchinductor.py

fixes https://ontrack-internal.amd.com/browse/SWDEV-522391 for PT 2.7

[release/2.7] Fix SDPA skip logic

---

aten/src/ATen/native/cuda/Reduce.cuh

cherry-pick of https://github.com/pytorch/pytorch/commit/085f270a00b4452bbb005d6b3d448e9d0b9d6fa0 in rocm/pytorch:release/2.7

[ROCm] Enable more parallelism for multi-dimensional reductions

---

cmake/External/aotriton.cmake

[AOTriton] Support ROCM 7.0 ABI

---

cmake/External/aotriton.cmake

[release/2.6] [AOTriton] Support ROCM 7.0 ABI

---

aten/src/ATen/native/cuda/jit_utils.cpp

[rocm7.0_internal_testing] fix jit_utils.cpp

---

aten/src/ATen/native/cuda/jit_utils.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2319

[AUTOGENERATED] [release/2.7] fix jit_utils.cpp

---

aten/src/ATen/native/cuda/jit_utils.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2319

[AUTOGENERATED] [release/2.6] fix jit_utils.cpp

---

aten/src/ATen/native/cuda/jit_utils.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2319

[AUTOGENERATED] [release/2.5] fix jit_utils.cpp

---

aten/src/ATen/native/cuda/jit_utils.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2319

[AUTOGENERATED] [release/2.4] fix jit_utils.cpp

---

.ci/docker/requirements-ci.txt

Fixes http://rocm-ci.amd.com/blue/organizations/jenkins/pyt_whl_docker_mainline/detail/pyt_whl_docker_mainline/2165/pipeline/
Per:https://github.com/python-pillow/Pillow/issues/8075

[release/2.5] Upgrade pillow for 3.13

---

related_commits

Apex extensions import test - https://github.com/ROCm/apex/pull/245
Fixing the C10_warpsize issue. replacing the macros with at::cuda::warp_size() - https://github.com/ROCm/apex/pull/237
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-541725

[rocm7.0_internal_testing] Update related_commits

---

torch/__init__.py

Cherry-picked from upstream 30387ab2e485384ab2e67084a1e2c5569190ba92.

[ROCm] Adds initialization support for PyTorch when built from ROCm wheels. (#155285)

---

aten/src/ATen/cuda/CUDABlas.cpp
aten/src/ATen/cuda/CUDAContextLight.h
aten/src/ATen/cuda/CublasHandlePool.cpp
aten/src/ATen/cuda/tunable/GemmHipblaslt.h
benchmarks/dynamo/common.py

Cherry-pick of https://github.com/pytorch/pytorch/pull/156495.

hipblaslt persistent workspace

---

aten/src/ATen/native/cuda/layer_norm_kernel.cu
aten/src/ATen/native/sparse/cuda/SparseCUDAApplyUtils.cuh
c10/macros/Macros.h

Cherry-pick of https://github.com/ROCm/pytorch/pull/2328

[AUTOGENERATED] [release/2.5] Improve C10_WARP_SIZE compatibility

---

torch/utils/cpp_extension.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2374

[AUTOGENERATED] [release/2.6] [release/2.7] [ROCm] cpp_extension allow user to override default flags (#152432)

---

torch/utils/cpp_extension.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2374

[AUTOGENERATED] [rocm7.0_internal_testing] [release/2.7] [ROCm] cpp_extension allow user to override default flags (#152432)

---

test/inductor/test_torchinductor.py

Fixes [SWDEV-510889](https://ontrack-internal.amd.com/browse/SWDEV-510889)

[release/2.5] Added PLATFORM_SUPPORTS_MEM_EFF_ATTENTION skip logic for NAVI

---

aten/src/ATen/native/cuda/KernelUtils.cuh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2438

[AUTOGENERATED] [release/2.8] [ROCm] Use opportunistic fastatomics based on heuristics

---

related_commits

Commit Messages:
- Fixing Rocrand issue
Co-authored-by: Prachi Gupta <pracgupt@amd.com>
PRs:
- https://github.com/ROCm/apex/pull/266

[release/2.5] update related_commit

---

related_commits

Commit Messages:
- Fixing Rocrand issue
Co-authored-by: Prachi Gupta <pracgupt@amd.com>
PRs:
- https://github.com/ROCm/apex/pull/268

[release/2.7] update related_commit

---

torch/_inductor/runtime/coordinate_descent_tuner.py

https://github.com/ROCm/pytorch/pull/2421 didn't bring in all required changes to reland https://github.com/ROCm/pytorch/pull/2416

[release/2.7] [SWDEV-543214] Reland #2416 Fix warps runtime part 2

---

test/inductor/test_select_algorithm.py

Skip test__int_mm

---

torch/_inductor/runtime/coordinate_descent_tuner.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2442

[AUTOGENERATED] [release/2.6] [release/2.7] [SWDEV-543214] Reland #2416 Fix warps runtime part 2

---

test/inductor/test_flex_decoding.py
test/inductor/test_max_autotune.py
torch/testing/_internal/common_utils.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2450

[AUTOGENERATED] [rocm7.1_internal_testing] NAVI32 specific fixes

---

related_commits

Commit Messages:
- update the param_id calculation so that it works on both CPX and SPX modes (#271) (#272)
PRs:
- https://github.com/ROCm/apex/pull/272
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-548434

[rocm7.0_internal_testing] update related_commit

---

.gitmodules

[rocm7.1_internal_testing] Use upstream kineto

---

aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/native/miopen/RNN_miopen.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2440

[release/2.6] Fix test_rnn_check_device tests for P1 Jira SWDEV-542659

---

.github/scripts/build_triton_wheel.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2518

[AUTOGENERATED] [release/2.7] Change triton package name depending on rocm version

---

.github/scripts/build_triton_wheel.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2518

[AUTOGENERATED] [release/2.8] Change triton package name depending on rocm version

---

.ci/docker/requirements-ci.txt

Cherry-pick of https://github.com/ROCm/pytorch/pull/2535

[AUTOGENERATED] [release/2.7] Remove tb-nightly

---

.ci/docker/requirements-ci.txt

Cherry-pick of https://github.com/ROCm/pytorch/pull/2535

[AUTOGENERATED] [release/2.8] Remove tb-nightly

---

.ci/docker/requirements-ci.txt

Cherry-pick of https://github.com/ROCm/pytorch/pull/2535

[AUTOGENERATED] [rocm7.1_internal_testing] Remove tb-nightly

---

aten/src/ATen/native/cuda/Reduce.cuh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2554

[AUTOGENERATED] [rocm7.1_internal_testing] [ROCm] Unroll loads in global_reduce

---

README.md

[DO NOT MERGE] Test CI 2
