tools/amd_build/pyHIPIFY/constants.py
tools/amd_build/pyHIPIFY/cuda_to_hip_mappings.py

Highlight that these originated from hipify-clang.

Document constants and mappings.

---

tools/amd_build/pyHIPIFY/hipify-python.py

Add workarounds in pyHIPIFY for __forceinline__ and std:: math functions in HIP

---

docker/caffe2/jenkins/common/install_rocm.sh

Not to be merged until week28 PR has landed upstream.

cub-hip fixes have been merged to master.

---

.jenkins/pytorch/build.sh

This will reduce the number of cores used with sscache in order to handle the LLVM Out of memory error that many rocmnightly jobs have been experiencing so far.

Alleviating the LLVM Out of Memory Error.

---

tools/amd_build/pyHIPIFY/hipify-python.py

ROCm builds may fail fail on PyTorch/PyTorch master due to transpilation issues.

Escaping Inputs to regular expressions.

---

tools/amd_build/pyHIPIFY/hipify-python.py

I amended the transpiler with a fix for dynamic shared memory allocation when kernels are launched from the host side. These warnings will no longer show up on the console anymore.
https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_kernel_language.md#__shared__

Fix Dynamic Shared Memory.

---

caffe2/python/convnet_benchmarks.py
caffe2/python/core.py
rocm-docs/caffe2-build.md

Docs to build caffe2 and run benchmarks

Caffe2 docs

---

tools/build_pytorch_libs.sh

The hipcc linker_helper is stripping $ORIGIN from the RPATH.
RPATH must be set as intended or some symbols will not be found at runtime.

ROCM: Escape RPATH when linking with hipcc

---

caffe2/python/core.py
caffe2/python/operator_test/activation_ops_test.py
caffe2/python/operator_test/boolean_mask_test.py
caffe2/python/operator_test/ceil_op_test.py
caffe2/python/operator_test/conv_test.py
caffe2/python/operator_test/copy_ops_test.py
caffe2/python/operator_test/elementwise_op_broadcast_test.py

The PR contains changes to be able to run HIP flow for a few of the python operator tests

[Caffe2] Support for HIP in python operator tests

---

tools/amd_build/pyHIPIFY/cuda_to_hip_mappings.py
tools/amd_build/pyHIPIFY/hipify-python.py

To automatically replace mathematics functions inside device code, simply add to the MATH_TRANSPILATIONS dictionary in cuda_to_hip_mappings.py.

Automatically handle transpilations inside device code only

---

caffe2/db/CMakeLists.txt
tools/amd_build/build_caffe2_amd.py

Add `db` directory for hipifying.

[Caffe2] Add db directory for hipifying

---

aten/src/ATen/cudnn/Handles.h

Link ATen/cudnn/Handles.h to ATen/cudnn/Handle.h for backward comparability.  It may be referenced externally.

Restore cudnn/Handles.h for compatability

---

aten/src/ATen/cuda/CUDAConfig.h.in
aten/src/ATen/cuda/detail/CUDAHooks.cpp
aten/src/ATen/native/miopen/BatchNorm.cpp
aten/src/ATen/native/miopen/Conv.cpp
cmake/Dependencies.cmake

Changed references to MIOpen in defines to reference ROCM instead.

Miopen defines

---

aten/src/THC/THCNumerics.cuh
tools/amd_build/disabled_features.yaml

* remove a duplicate entry from disabled_features
* fix a long-time warning by doing the right thing (TM) according to C++11 and using fabs() for the double absolute function as opposed to the integer only (and nvcc it seems) abs() function

Small fixes

---

tools/amd_build/pyHIPIFY/hipify-python.py

Assert disabling logic isn't necessary at the moment. Ideally, should be kept to maintain correctness at runtime during assertion executions. Keeping the definition for disable_asserts in case this needs to be re-enabled in the future.

ROCm 1.8.2 correctly handles asserts.

---

aten/src/THC/THCSortUtils.cuh
docker/caffe2/jenkins/common/install_rocm.sh
test/test_nn.py

introduces a hcc compiler with two compiler fixes that are very relevant to us and a custom hip header that allows us to avoid static_casting a lot - note, this is not yet really disabling any auto-generated static_casts as there is a few cases where this does not work (associated with rocRAND). May happen later however.
Note - this does regress five unit tests which this PR disables. That being said however, we are able to enable *hundreds* of important unit tests with this once it has landed. Additionally, it is not clear ye what caused these regressions (the previous, buggy hcc may well have by "mistake" done the right thing).

Hcc and hip fix

---

aten/src/ATen/native/Convolution.cpp

MIOpen convolution are not supported on double.  Fall back to standard processing.

Disable MIOpen convolution on double tensors

---

aten/src/ATen/miopen/Descriptors.h

Enables group convolutions via MIOpen.
Requires MIOpen 1.5.

MIOpen: set group count in convolution descriptor

---

aten/src/THC/generic/THCTensorSort.cu
aten/src/THC/generic/THCTensorTopK.cu
test/test_torch.py

It is known to hang - use the Thrust fallback

Disable in-place sorting on ROCm.

---

caffe2/utils/conversions.h
caffe2/utils/fixed_divisor.h
caffe2/utils/math_utils.h

This reverts commit 0207b3fd902e8c71c55b7037c2861961ba3831a8.
@jithunnair-amd located this as the culprit for our woes.
@yxsamliu can you comment why we may not have `__HIP__` defined in the "old" setup?

Revert "Fix device function decls (#192)"

---

aten/src/ATen/native/Convolution.cpp
aten/src/ATen/native/Normalization.cpp

The previous maxdim check prevented MIOpen from running on over dimensioned tensors... or anything else.  This is a better.

Fix maxdim check.

---

aten/src/THC/THCTensorTopK.cuh
tools/amd_build/pyHIPIFY/hipify-python.py

Call only one math transpilation function which replaces only in __device__ functions.

Remove duplicate math transpilation function

---

caffe2/utils/conversions.h
caffe2/utils/fixed_divisor.h
caffe2/utils/math_utils.h

hip-clang needs `__device__` `__host__` to be consistent for both device and host compilation.

Fix device function declaration for hip-clang

---

caffe2/core/hip/context_hip.h
caffe2/utils/hip/math_hip.cc
tools/amd_build/pyHIPIFY/cuda_to_hip_mappings.py

Since upstream #9322 by @petrex , hipification resulted in illegal code.
The legal function cublasHandle_t cublas_handle() was hipified to the
clearly illegal rocblas_handle rocblas_handle(). It should not work and
correctly fails with gcc as the host compiler as it induces an
ambiguity.
Function now hipifies to rocblas_handle rocblashandle()
Fixes long standing issue we've observed in PyTorch when base compiler is gcc.

Fix illegal code in rocblas_handle rocblas_handle()

---

aten/src/ATen/native/cuda/Unique.cu
aten/src/THC/THCNumerics.cuh
aten/src/THC/THCTensorTopK.cuh
aten/src/THCUNN/LookupTable.cu
tools/amd_build/disabled_features.yaml

* enable Unique
* enable fp16 TopK
* enable previously disabled functions

Minor improvements cherry-pick

---

aten/src/ATen/native/cuda/Embedding.cu
test/common_nn.py

* Enable test_nn embedding tests and use correct warp size in Embedding.cu
* Fix embedding_backward_feature_kernel kernel for HIP

Enable test_nn embedding tests and use correct warp size in Embedding.cu (ROCm 285)

---

cmake/Dependencies.cmake
cmake/public/LoadHIP.cmake

rocfft should also be linked in to libcaffe2_hip.so. Combined build for caffe2 and pytorch means all dependencies should be linked in.

Refactor cmake files for loading ROCm libs

---

aten/src/ATen/native/cuda/LossCTC.cu

Summary:
ROCm 2.0's compiler requires launch_bounds annotations if flat work group sizes are larger than the default of 256.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/15400
Differential Revision: D13531239
Pulled By: ezyang
fbshipit-source-id: c0b40600a8c332823da6c7113c644d8dba424a9c

Cherry-pick: Add launch bounds needed for ROCm 2.0 (#15400)

---

aten/src/ATen/native/miopen/Conv_miopen.cpp

MiopenFindConvolution*Algorithm returns the exact workspace size required by the selected algorithm.  Caching this rather that re-querying improves performance.

MIOPEN: Performance. Cache workspace size in the BenchmarkCache.

---

test/test_jit.py
test/test_nn.py

Re-disabling flaky tests for ROCm

---

aten/src/ATen/core/aten_interned_strings.h
aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/native/Convolution.cpp
aten/src/ATen/native/miopen/Conv_miopen.cpp
aten/src/ATen/native/native_functions.yaml
tools/autograd/derivatives.yaml

1. Added Depthwise convolutions to go through via MIOpen.
2. Modified Descriptors.h (miopen) to pass miopen convolution modes.

[Pytorch] MIOpen depthwise convolutions

---

tools/amd_build/build_amd.py
tools/amd_build/pyHIPIFY/hipify_python.py

- With extra parentheses, hcc hits a bug. Although a fix is availble, it
won't be available until next major release. For hip-clang, as
hipKernelLaunchGGL is re-implemented using macro, that extra
parenthese is mandatory for explicitly-instantiated template kernel
function. As a temporary solution, add a new option
'--hip-clang-launch' to skip transforming the <<<>>> launch to
hipKernelLaunchGGL.

[hipify] Add '--hip-clang-launch' to favor <<<>>>-based launch.

---

test/common_nn.py

since double is now expected to work

Remove all uses of skip_double for ROCm tests

---

tools/amd_build/pyHIPIFY/hipify_python.py

- Revise the pattern from `\W<TRIE>\W` to `\W<TRIE>(?=\W)`, i.e. the
ending non-alphanum is changed to lookahead one so that the next
identifier could be matched and replaced in a most robust manner.
- The replace function is revised accordingly as there are only 2 groups
now.

[hipify] Fix identifier replacing.

---

test/test_cuda.py

PyTorch test sets a policy() method to assertLeaksNoCudaTensors.
Whenever a test is run, assertLeaksNoCudaTensors is called,
which in turn calls CudaMemoryLeakCheck, which in turn calls
initialize_cuda_context_rng, where it executes torch.randn
on each device, where a kernel is launched on each device.
Since the kernel may not finish on device 1, the assertion
self.assertTrue(s1.query()) fails.
The fix is to insert
torch.cuda.synchronize(d0)
torch.cuda.synchronize(d1)
at the beginning of the test so that previoulsy launched kernels finish before the real
test begins.

Fix TestCuda.test_events_wait

---

.jenkins/caffe2/build.sh
.jenkins/pytorch/build.sh
CMakeLists.txt
cmake/Dependencies.cmake
cmake/External/rccl.cmake
cmake/public/LoadHIP.cmake
tools/amd_build/pyHIPIFY/cuda_to_hip_mappings.py
tools/amd_build/pyHIPIFY/hipify_python.py

Build completed successfully for me with the following command after hipification:
`PYTORCH_ROCM_ARCH=gfx900 USE_GLOO=0 USE_NCCL=1 USE_SYSTEM_NCCL=1 USE_MKLDNN=0 USE_ROCM=1 MAX_JOBS=4 KMTHINLTO=1 python setup.py install 2>&1 | tee -a $build_log`
Note that hipification logic needed slight modification so as to enable desired substitutions.

Changes to enable rccl build

---

test/test_cuda.py

This is a similar issue as TestCuda.test_events_wait.
PyTorch test sets a policy() method to assertLeaksNoCudaTensors.
Whenever a test is run, assertLeaksNoCudaTensors is called,
which in turn calls CudaMemoryLeakCheck, which in turn calls
initialize_cuda_context_rng, where it executes torch.randn
on each device, where a kernel is launched on each device.
Since the kernel may not finish on device 0, the first asstion
self.assertTrue(s0.query()) fails.
The fix is to insert
torch.cuda.synchronize(d0)
torch.cuda.synchronize(d1)
at the beginning of the test so that previously launched kernels finish before the real
test begins.

Fix test TestCuda.test_streams_multi_gpu_query

---

aten/src/ATen/preprocess_declarations.py
aten/src/THC/CMakeLists.txt
aten/src/THC/generic/THCTensorMathPointwise.cu
aten/src/THC/generic/THCTensorMathPointwise.h
aten/src/THC/generic/THCTensorMathScan.cu
aten/src/THC/generic/THCTensorRandom.cu
aten/src/THC/generic/THCTensorRandom.h
torch/nn/modules/module.py

This PR removes the check to discard bfloat16 for cuda and enables bfloat16 by default for ops in THC.

Enable BFloat16 for ops in THC by default

---

test/test_autograd.py
tools/autograd/derivatives.yaml
tools/autograd/templates/Functions.cpp

Summary:
Another pull request to follow up issue https://github.com/pytorch/pytorch/issues/32531.
Here I implemented the backward operation for `torch.eig` with a condition that all the eigenvalues are real.
This pull request is independent of my another pull request https://github.com/pytorch/pytorch/issues/32932, which means that there is no dependency between this PR and my another PR.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/33090
Differential Revision: D19814347
Pulled By: albanD
fbshipit-source-id: 2fae30964e97987abb690544df8240aedeae56e8

IFU 20200210 #2: Backward operation of torch.eig for real eigenvalues (#33090)

---

aten/src/ATen/native/Normalization.cpp

* Enable Normalization.cpp to accept 5D tensors for MIOpen BatchNorm3D functions.

[Pytorch] Enable MIOpen 3D Batchnorms

---

docker/pytorch/cpu-only/Dockerfile

This Dockerfile will build PyTorch for CPU only with MKLDNN+BLIS and Torchvision.

Included Dockerfile for CPU only build with MKLDNN+BLIS

---

torch/__init__.py

Summary:
This reverts commit d7a7bcb0428273fa54a836b52e750608ebe7e4de.
The previous commit is not useful because torch_global_deps doesn't include any external dependencies.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/35355
Differential Revision: D20653036
Pulled By: ezyang
fbshipit-source-id: 6d2e2f90952ca865b27b649a6ff9114ada8ea78c

Revert "Load torch_global_deps for Windows (#35177)" (#35355)

---

aten/src/THC/THCAtomics.cuh

Revert the commit caused mGPU perf regression.

Rocm3.9 internal testing

---

torch/lib/c10d/NCCLUtils.hpp

This removes the workaround and realigns the file torch/lib/c10d/NCCLUtils.hpp with upstream.

ENABLE_NCCL_A2A workaround no longer needed

---

aten/src/THC/THCAtomics.cuh

The atomicAddNoRet_impl is missing the return type in declaration name. Although llvm automatically corrects this declaration, it is better to correct this here. Asm should be llvm.amdgcn.global.atomic.fadd.f32.p1f32.f32.

Fix missing .fp32 in atomicAddNoRet_impl decl

---

aten/src/ATen/native/Normalization.cpp

- Skipping MIOpen bnorm when H*W is not a multiple of 4 and picking
pyTorch native bnorm implementation
- Fix the SSD convergence
- Revert this change after proper fix from MIOpen
** verification test in progress

Temp workaround to skip MIOpen bnorm

---

aten/src/ATen/native/Normalization.cpp

This reverts commit 58cfa4b517a13b32f01429b490106d73320e36fc.
Fixes #{issue number}

Revert "Temp workaround to skip MIOpen bnorm"

---

aten/src/ATen/native/RNN.cpp
test/test_nn.py

Summary:
This PR enables using MIOpen for RNN FP16 on ROCM.
It does this by altering use_miopen to allow fp16.  In the special case where LSTMs use projections we use the default implementation, as it is not implemented in MIOpen at this time. We do send out a warning once to let the user know.
We then remove the various asserts that are no longer necessary since we handle the case.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/52475
Reviewed By: H-Huang
Differential Revision: D27449150
Pulled By: malfet
fbshipit-source-id: 06499adb94f28d4aad73fa52890d6ba361937ea6
Fixes #{issue number}

[ROCM] enable miopen for rnn f16 (#52475)

---

.github/workflows/ifu.yml
.github/workflows/ifu_testing.yml
cmake/Modules/Findblis.cmake
cmake/public/test_atomic.hip

Some files unique to our ROCm PyTorch fork had trailing spaces, resulting in CI failures caught by quick-checks action.

quick-checks: ensure no trailing spaces

---

.circleci/docker/common/install_rocm.sh

Summary:
Magma master branch is updated with all the fixes required for ROCm, so updating the magma build to the new commit for ROCm pyTorch builds.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/60900
Reviewed By: jbschlosser
Differential Revision: D29440587
Pulled By: malfet
fbshipit-source-id: 2ccdf48441dfff3d19c4a478e03ac11a843f8419
Fixes #{issue number}

[ROCm] Update the magma build to new commit (#60900)

---

test/test_spectral_ops.py

This disables failing spectral tests on rocm 4.5.
See the following Jiras.
https://ontrack-internal.amd.com/browse/SWDEV-301916
https://ontrack-internal.amd.com/browse/SWDEV-303271

Rocm4.5 internal testing disable spectral

---

test/test_spectral_ops.py

Skipping new test in spectral ops until rocfft fix is added. JIRA: https://ontrack-internal.amd.com/browse/SWDEV-305234

skip test_istft_round_trip_with_padding

---

aten/src/ATen/cuda/cub.cuh
test/test_torch.py

[ROCm] use hipCUB chained iterator
For inclusive_scan and exclusive_scan, use hipCUB / rocPRIM's chainted iterator.
Implemented for ROCm 5.0 and above.

[ROCm] use hipCUB chained iterator

---

related_commits

as https://ontrack-internal.amd.com/browse/SWDEV-300538 is fixed
Local testing with some pytorch microbenchmarking workloads reflected unchanged performance compared to ROCm fork commit.
@pruthvistony To be merged only for ROCm4.5.1, to avoid unnecessary churn for ROCm4.5.

Update torchvision commit to upstream

---

related_commits

Update related_commits for [the apex hash](https://github.com/ROCmSoftwarePlatform/apex/commit/abb6e5ba39b58322e1db5ff4bd89ab06792d4d46) to fix the compiling error related to THH/THHDeviceUtils.cuh.

Update related_commits for the apex hash to fix the compiling error related to THH/THHDeviceUtils.cuh

---

.circleci/docker/centos-rocm/Dockerfile

CentOS 7 build failed because packages.endpoint.com server has no response. Add another mirror  as the backup.

CentOS 7 build failed in rocm5.1_internal_testing branch

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/CrossKernel.cu
aten/src/ATen/native/cuda/DistributionTemplates.h
aten/src/ATen/native/cuda/FunctionOfAMatrixUtilsKernel.cu
aten/src/ATen/native/cuda/LinearAlgebra.cu
aten/src/ATen/native/cuda/Loops.cuh
aten/src/ATen/native/cuda/MemoryAccess.cuh
aten/src/ATen/native/cuda/ROCmLoops.cuh
aten/src/ATen/native/cuda/ScatterGatherKernel.cu
aten/src/ATen/native/cuda/UnfoldBackwardKernel.cu
aten/src/ATen/test/cuda_vectorized_test.cu

This pr cherrypicks  https://github.com/pytorch/pytorch/commit/4b1d044498f49ad5f770354174070a4277279c2d and adds some code changes to makes sure it functions on Navi21.
Summary:
This reverts commit 9e8016d8c48e9c99addad93112f99d3375a0fbc7.
cc jeffdaily sunway513 jithunnair-amd ROCmSupport KyleCZH
Pull Request resolved: https://github.com/pytorch/pytorch/pull/68008
Reviewed By: H-Huang
Differential Revision: D32254779
Pulled By: ngimel
fbshipit-source-id: 38ec415199f62a1e58000abe3e34ac91898a94ae
Fixes [SWDEV-319672](https://ontrack-internal.amd.com/browse/SWDEV-319672)

[WIP][resubmit] Don't #define NUM_THREADS (#68008)

---

CMakeLists.txt
caffe2/CMakeLists.txt

Fixes https://ontrack-internal.amd.com/browse/SWDEV-321296
Cherry-picking commit https://github.com/pytorch/pytorch/commit/77beccaedb3e40d83d1ea9bf6c6e33f7b23c7592 led to conflicts, so I took the bare minimum changes needed to disable Caffe2 build.

Disable caffe2 build

---

.circleci/docker/common/install_rocm.sh

Signed-off-by: Wang, Yanyao <yanyao.wang@amd.com>
The ROCm 5.0 installation failed for missing AMDGPU mapping.

Add ROCm5.0/AMDGPU support

---

tools/amd_build/build_amd.py
torch/utils/cpp_extension.py
torch/utils/hipify/hipify_python.py

1. Fix JIT path of building PyTorch extensions
2. includes/ignores must be absolute paths to handle JIT path
3. Use absolute paths for all files to allow for absolute paths in
includes/ignores
4. Limit hipification to build_dir for non-JIT path
5. Ignore ROCm/PyTorch headers during hipification of
header_include_dirs for JIT path
6. Update hipify output with clearer status
7. Don't include files ignored by hipify in hipify output to control verbosity of hipify output
8. Define HIP flags in cflags for JIT path as well
Fixes https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/276 and [SWDEV-318084](https://ontrack-internal.amd.com/browse/SWDEV-318084)

Fix JIT path for Pytorch extensions and other hipify fixes

---

aten/src/ATen/cuda/CUDABlas.cpp
aten/src/ATen/cuda/CUDASolver.cpp
aten/src/ATen/cuda/Exceptions.h
test/cpp_extensions/cublas_extension.cpp
test/cpp_extensions/cusolver_extension.cpp
test/cpp_extensions/setup.py
test/test_cpp_extensions_aot.py

Please see https://github.com/pytorch/pytorch/pull/67161 and https://github.com/pytorch/pytorch/commit/d4493b27ee513100aab94381a2fc86ba6188f1a1 for more information. This solved the issue of import error for Apex multihead_attn extension in PyTorch 1.10.

Cherry-pick the commit to make TORCH_(CUDABLAS|CUSOLVER)_CHECK usable in custom extensions

---

tools/amd_build/build_amd.py
torch/utils/cpp_extension.py
torch/utils/hipify/hipify_python.py

1. Fix JIT path of building PyTorch extensions
2. includes/ignores must be absolute paths to handle JIT path
3. Use absolute paths for all files to allow for absolute paths in
includes/ignores
4. Limit hipification to build_dir for non-JIT path
5. Ignore ROCm/PyTorch headers during hipification of
header_include_dirs for JIT path
6. Update hipify output with clearer status
7. Don't include files ignored by hipify in hipify output to control verbosity of hipify output
8. Define HIP flags in cflags for JIT path as well
Fixes https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/276 and [SWDEV-318084](https://ontrack-internal.amd.com/browse/SWDEV-318084)

Fix JIT path for Pytorch extensions and other hipify fixes (rocm5.0_internal_testing)

---

test/test_linalg.py

Cherrypicked the changes from master PT
https://github.com/pytorch/pytorch/pull/67679
Fixes https://ontrack-internal.amd.com/browse/SWDEV-320250

Fix failing test due to a bug in NumPy when using OpenBLAS

---

aten/src/ATen/Context.cpp
aten/src/ATen/Context.h
aten/src/ATen/cuda/CUDABlas.cpp
torch/csrc/autograd/function.h

Cherry-picked the commit to resolve Apex compiling issues related to rocblas_gemm_flags_fp16_alt_impl implementations in [MLP](https://github.com/ROCmSoftwarePlatform/apex/commit/063d720f1a41f1b5437f0cf7cbbc5e4a81392538) and [MHA](https://github.com/ROCmSoftwarePlatform/apex/commit/b6a1f48b9ddaa02653585531ce65dc6b3e020a43) extensions. The error message is like
```
/opt/rocm-5.0.1/bin/hipcc -I/var/lib/jenkins/apex/csrc -I/opt/conda/lib/python3.7/site-packages/torch/include -I/opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.7/site-packages/torch/include/TH -I/opt/conda/lib/python3.7/site-packages/torch/include/THC -I/opt/conda/lib/python3.7/site-packages/torch/include/THH -I/opt/rocm-5.0.1/include -I/opt/rocm-5.0.1/miopen/include …
```

rocblas alt impl during backward pass only

---

aten/src/ATen/native/cuda/Shape.cu

revert d5ca53c9554fd63d1fd69e58416dbf17a7952af9 (#46097).  The changes only affect ROCm.  Reverts a work-around for a compiler performance issue that is no longer needed.
`python -m pt.cat_test --tag_filter all --device cuda`
```
OLD Forward Execution Time (us) : 48.833
NEW Forward Execution Time (us) : 8.318
OLD Forward Execution Time (us) : 54.508
NEW Forward Execution Time (us) : 23.824
OLD Forward Execution Time (us) : 52.117
NEW Forward Execution Time (us) : 14.942
OLD Forward Execution Time (us) : 98.790
NEW Forward Execution Time (us) : 74.334
OLD Forward Execution Time (us) : 102.063
NEW Forward Execution Time (us) : 76.008
OLD Forward Execution Time (us) : 167.786
NEW Forward Execution Time (us) : 123.679
OLD Forward Execution Time (us) : 98.320
NEW Forward Execution Time (us) : …
```

[ROCm] revert cat operator performance work-around

---

test/test_multiprocessing.py

Skipped the tests as the fail and hang on ROCm w.r.t https://github.com/ROCmSoftwarePlatform/pytorch/pull/993,
JIRA: https://ontrack-internal.amd.com/browse/SWDEV-332522

Skipped the failing tests on ROCm during IFU-master-2022-04-11

---

torch/csrc/cuda/nccl.cpp

Deactive ncclAllToAll since degradation was observed on a Hayabusa system

Deactive ncclAllToAll

---

test/test_optim.py

ROCm: Fix test_nadam

---

test/distributed/test_data_parallel.py

Skips test as per https://ontrack-internal.amd.com/browse/SWDEV-327377
distributed/test_data_parallel  test suite fails, disabling these tests will make the suite pass.
The issue is currently under debug.

[ROCm] Disable TestDataParallelDeviceType tests

---

tools/amd_build/build_amd.py
torch/utils/cpp_extension.py
torch/utils/hipify/hipify_python.py

The commits in the PR, https://github.com/pytorch/pytorch/pull/76141, are required to build DeepSpeed on ROCm without the hipify errors.

Hipify fixes for a successful DeepSpeed build for rocm5.3_internal_testing

---

.circleci/docker/common/install_user.sh

Fixes issues such as [SWDEV-339205](https://ontrack-internal.amd.com/browse/SWDEV-339205) for rocm5.3_internal_testing
Use /bin/sudo to avoid issue on CentOS: https://bugzilla.redhat.com/show_bug.cgi?id=1319936

Use the right sudo depending on OS

---

test/test_shape_ops.py

Increase system memory requirement for TestShapeOpsCUDA.test_flip_large_tensor_cuda
Fixes https://ontrack-internal.amd.com/browse/SWDEV-335300

[ test_shape_ops] Increase system memory requirement

---

tools/amd_build/build_amd.py
torch/utils/cpp_extension.py
torch/utils/hipify/hipify_python.py

The commits in the PR, https://github.com/pytorch/pytorch/pull/76141, are required to build DeepSpeed on ROCm without the hipify errors.
cc: @jithunnair-amd

Hipify fixes for a successful DeepSpeed build with release/1.11

---

aten/src/ATen/native/Normalization.cpp

MIOPEN does not support channel last tensors so we use the native pytorch implementation.
https://ontrack-internal.amd.com/browse/SWDEV-333420

skip miopen batchnorm if channels_last (NHWC)

---

.circleci/docker/common/install_rocm.sh

Fix baseurl link in CentOS for ROCm5.2

---

.circleci/docker/common/install_rocm.sh

We already install the miopenkernels packages for Ubuntu. Need to do the same for CentOS.

[rocm5.3_internal_testing] Install miopenkernels package for CentOS

---

torch/nn/parallel/parallel_apply.py

#71033 moved test_data_parallel_module et al under `instantiate_device_type_tests`.  This had the side effect of now running the tests on a non-default stream.  The parallel_apply creates new threads, one per device, but does not forward the thread local current streams from the parent thread.  This defaults the new per-device threads to use the null stream.  The null stream will not sync with the non-default non-blocking streams, resulting in errors when these tests assert tensors are equal.

 [SOW MS3] parallel_apply should forward current streams to worker threads

---

caffe2/CMakeLists.txt
cmake/Dependencies.cmake

This prevents linking in the wrong libtinfo in
/opt/conda/lib, which conflicts with the libtinfo
ROCm built with at /usr/lib/x86_64-linux-gnu.
Currently only active for Ubuntu 20.04.

Remove -ltinfo from libtorch and use -rpath-link instead.

---

cmake/Dependencies.cmake

The ROCm libtinfo6 is conflicting with the libtinfo6
installed in the conda envirnonment in /opt/conda/lib.
This is first in the build rpath and causes issues on
Ubuntu 20.04 when resolving libamd_comgr.so
dependencies. Use -rpath-link to resolve dependencies
where the system libtinfo is found instead. This is
currently active on versions >= 20.04.

Use -rpath-link to fix libtinfo conflict.

---

aten/src/ATen/native/miopen/Conv_miopen.cpp
aten/src/ATen/native/native_functions.yaml
test/jit/test_freezing.py
test/test_nn.py
torch/csrc/jit/passes/frozen_conv_add_relu_fusion_cuda.cpp
torch/overrides.py

Adds MIOpen fused convolution relu for fp32 and contiguous memory format. Adds fallbacks for conv + z + bias + relu, fp16, and channels last until MIOpen adds these features.
Enables:
test_jit test_freeze_conv_relu_fusion (jit.test_freezing.TestFrozenOptimizations)
test_jit test_freeze_conv_relu_fusion_not_forward (jit.test_freezing.TestFrozenOptimizations)
test_nn test_cudnn_convolution_relu_cuda_float16 (__main__.TestNNDeviceTypeCUDA)
test_nn test_cudnn_convolution_relu_cuda_float32 (__main__.TestNNDeviceTypeCUDA)
test_nn test_cudnn_convolution_add_relu_cuda_float16 (__main__.TestNNDeviceTypeCUDA)
test_nn test_cudnn_convolution_add_relu_cuda_float32 (__main__.TestNNDeviceTypeCUDA)

[SOW MS3] [ROCm] MIOpen fused convolution relu

---

torch/testing/_internal/common_methods_invocations.py

Use skipCUDAIfNoCusolverAndNoHipsolver replacing skipCUDAIfNoCusolver only for decorators list of:
- linalg.householder_product
- ormqr
Fixes [#2104](https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2104)
Unit tests results:
test_out_linalg_householder_product_cuda_float32 (__main__.TestCommonCUDA) ... ok (3.980s)
test_conj_view_linalg_householder_product_cuda_complex64 (__main__.TestMathBitsCUDA) ... ok (6.892s)
test_conj_view_ormqr_cuda_complex64 (__main__.TestMathBitsCUDA) ... ok (3.815s)
test_dtypes_linalg_householder_product_cuda (__main__.TestCommonCUDA) ... ok (7.214s)
test_fn_grad_linalg_householder_product_cuda_complex128 (__main__.TestGradientsCUDA) ... ok (7.296s)
test_fn_grad_linalg_householder_product_cuda_float64 (__main__.TestGradientsCUDA) ... ok (6.974s) …

[SOW MS3] Enable hipSOLVER for test_ops* (#2104)

---

.jenkins/pytorch/build.sh
test/run_test.py

The following 12 tests are being re-enabled for ROCM:
test_openmp test_n_threads (main.TestOpenMP_ParallelFor)
test_openmp test_one_thread (main.TestOpenMP_ParallelFor)
And
test_tensorexpr_pybind test_alloc_in_loop (main.TestTensorExprPyBind)
test_tensorexpr_pybind test_kernel_shape_prop (main.TestTensorExprPyBind)
test_tensorexpr_pybind test_kernel_shape_prop_module (main.TestTensorExprPyBind)
test_tensorexpr_pybind test_kernel_with_custom_lowering (main.TestTensorExprPyBind)
test_tensorexpr_pybind test_kernel_with_expand (main.TestTensorExprPyBind)
test_tensorexpr_pybind test_kernel_with_permute (main.TestTensorExprPyBind)
test_tensorexpr_pybind test_kernel_with_scalar_inputs (main.TestTensorExprPyBind)
test_tensorexpr_pybind test_kernel_with_t (main.TestTensorExprPyBind) …

[SOW MS3]: Renable test_openmp and tensorexpr for ROCM

---

test/test_cuda.py
test/test_sparse.py
torch/csrc/serialization.cpp

Fixes serialization synchronization issue 
Enables:
test_cuda test_cudnn_multiple_threads_same_device (main.TestCuda)
test_sparse test_pickle_cuda_float64 (__main__.TestSparseCUDA)

[SOW MS3] Pickle and cuda_test

---

test/test_cuda.py
torch/testing/_internal/common_utils.py

Add retry loop to memory leak check to allow potential transient memory leak to correct itself

[SOW MS3] Transient mem leak error check fix

---

related_commits

Add torchdata to the related_commits file so it can be used in building/verifying torchtext.

Update related_commits with torchdata

---

test/test_cuda.py

This test currently only handles the cudnn case. This commit addresses the assertion passes in the miopen case

Add support for miopen version in test_autocast_rnn

---

test/test_testing.py
torch/testing/_internal/common_device_type.py

The test "test_filtering_env_var" requires CPU runner along with GPU.
For ROCm, instantiate_device_type_tests() instantiates GPU runner only.
Revert the upstream PR 55069 to instantiate CPU runner along with GPU.

[SOW MS3]: Enable test_filtering_env_var

---

test/test_sparse.py

```
root@0452a021af59:/home/jpvillam/pytorch# export PYTORCH_TEST_WITH_ROCM=1
root@0452a021af59:/home/jpvillam/pytorch# python3 test/test_sparse.py -v -k test_sparse_matmul
test_sparse_matmul_cuda_float32 (__main__.TestSparseCUDA)
This function test `torch.sparse.mm` when both the mat1 and mat2 are sparse tensors. ... ok
test_sparse_matmul_cuda_float64 (__main__.TestSparseCUDA)
This function test `torch.sparse.mm` when both the mat1 and mat2 are sparse tensors. ... ok
Ran 2 tests in 10.754s
OK
```
Tested on: `compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-dkms-no-npi-hipclang:10473_ubuntu20.04_py3.7_pytorch_sow_ms3_f761bb`

[SOW MS3] Enable test_sparse_matmul on floats on ROCm5.3

---

test/test_nn.py

https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2041
to enable test_cudnn_weight_format  
two of the checks in the test failing for rocm are skipped , the following issue is created to further look into this : 
https://github.com/ROCmSoftwarePlatform/pytorch/issues/1077

enable test_cudnn_weight_format , bypassing warning check

---

aten/src/ATen/native/Normalization.cpp
test/test_nn.py

test_nn.py::TestNN::test_batchnorm_cudnn_nhwc test passes by cherry picking change from PR [skip miopen batchnorm if channels_last (NHWC)](https://github.com/ROCmSoftwarePlatform/pytorch/pull/1025)

[SOW MS3]: Enable test_batchnorm_cudnn_nhwc 

---

aten/src/ATen/native/cuda/linalg/CUDASolver.cpp
aten/src/ATen/native/cuda/linalg/CUDASolver.h

hipSolver const bug was fixed as of rocm build 10604. This PR reverts the workaround for that bug.
python test/test_linalg.py
```
Ran 1494 tests in 550.543s
OK (skipped=105)
```

[SOW MS3] Revert workaround for SWDEV-344283

---

test/run_test.py

Enables:
```
distributed/_sharded_tensor/test_sharded_tensor.test_empty
distributed/_sharded_tensor/test_sharded_tensor.test_serialize_and_deserialize
```
from SOW MS3 unit test parity list
which were moved to `distributed/_shard/sharded_tensor/test_sharded_tensor`

[SOW MS3] Remove test_sharded_tensor from ROCM_BLOCKLIST

---

aten/src/ATen/native/cuda/linalg/CUDASolver.h

Const qualifier is only supported in hipSOLVER in ROCM 5.3. Reverting previous const changes and adding a conditional to check for ROCM version.

[SOW MS3] Re-add CONST_QUALIFIER for rocm version less than 5.3

---

test/test_cuda.py

Replaces CUDA_VISIBLE_DEVICES with HIP_VISIBLE_DEVICES for ROCm.

Added ROCm support for cuda lazy init check

---

test/test_ops.py

Tests passing with change to magma
```
PYTORCH_TEST_WITH_ROCM=1 python test/test_ops.py TestCommonCUDA.test_out_linalg_svdvals_cuda_float32
[W Context.cpp:199] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
.
Ran 1 test in 20.643s
OK
```
```
PYTORCH_TEST_WITH_ROCM=1 python test/test_ops.py TestCommonCUDA.test_out_warning_linalg_svdvals_cuda
[W Context.cpp:199] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
. …
```

Set magma backend for test_out/warning

---

torch/testing/_internal/common_methods_invocations.py

test_non_standard_bool_values_to_sparse_cuda_bool
test_non_standard_bool_values_argwhere_cuda_bool
test_non_standard_bool_values_masked_select_cuda_bool
test_non_standard_bool_values_nonzero_cuda_bool
They are tracked in SWDEV-344137 and this should be reverted after fix.

[SOW MS3] Skipping few tests temporarily

---

aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.cpp
torch/utils/hipify/cuda_to_hip_mappings.py

gesvdj re-enabled after fix came in from hipSOLVER: https://ontrack-internal.amd.com/browse/SWDEV-345921?focusedCommentId=9554282&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

[SOW MS3] Enable gesvdj API to be called

---

cmake/Dependencies.cmake
torch/utils/hipify/cuda_to_hip_mappings.py

This removes most deprecation warnings such as:
```
Sep 09 02:41:24 In file included from /var/lib/jenkins/pytorch/build/third_party/gloo/hip/gloo/hip_private.hip:9:
Sep 09 02:41:24 In file included from /var/lib/jenkins/pytorch/build/third_party/gloo/hip/gloo/hip_private.h:20:
Sep 09 02:41:24 In file included from /var/lib/jenkins/pytorch/build/third_party/gloo/hip/gloo/hip.h:15:
Sep 09 02:41:24 /opt/rocm/hip/include/hip/hip_runtime.h:25:9: warning: This file is deprecated. Use file from include path /opt/rocm-ver/include/ and prefix with hip [-W#pragma-messages]
Sep 09 02:41:24 #pragma message("This file is deprecated. Use file from include path /opt/rocm-ver/include/ and prefix with hip")
Sep 09 02:41:24         ^
```
which blow up the PyTorch build logs in size.
This PR uses …

Update hipification and header include logic for ROCm headers

---

related_commits

To avoid future complications in triaging we have added the apex commit in related_commits to the rocm5.3_internal_testing and rocm5.4_internal_testing branches.

Added apex TOT to related_commits

---

test/test_cuda.py

This PR fixes random seg faults or hip errors seen when running PyTorch hipGraph-related unit tests with non-hipGraph-related unit tests.
Results:
test_graph_record_stream (__main__.TestCuda) ... skipped "test doesn't currently work on the ROCm stack"
test_graph_grad_scaling (__main__.TestCuda) ... ok
cc: @dllehr-amd @jithunnair-amd

Fixed errors in test/test_cuda.py

---

aten/src/ATen/native/Convolution.cpp
test/test_nn.py
torch/testing/_internal/common_device_type.py

Follow up to https://github.com/ROCmSoftwarePlatform/pytorch/pull/1072.
This PR works around the issue by enforcing the output tensor to be contigous and match ouput format of the weight tensor.
``` 
python test_nn.py --verbose  TestNNDeviceTypeCUDA.test_conv_cudnn_ndhwc_cuda_float16
python test_nn.py --verbose  TestNNDeviceTypeCUDA.test_conv_cudnn_ndhwc_cuda_float32
python test_nn.py --verbose  TestNNDeviceTypeCUDA.test_convert_conv2d_weight_memory_format_cuda
```

[SOW MS3] Workaround MIOPEN output tensor memory format issues #2

---

.jenkins/pytorch/common_utils.sh

CI scripts currently pull `release/1.10` branch. But since we limit refspec to `release/1.10.1` in CI job, it results in errors such as:
http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-1/389/console
```
17:42:52 Oct 03 22:42:52 + file_diff_from_base /tmp/tmp.6vpKW8MKN0
17:42:52 Oct 03 22:42:52 + set +e
17:42:52 Oct 03 22:42:52 + git fetch origin release/1.10 --quiet
17:42:53 Oct 03 22:42:53 + set -e
17:42:53 Oct 03 22:42:53 ++ git merge-base origin/release/1.10 HEAD
17:42:53 Oct 03 22:42:53 fatal: Not a valid object name origin/release/1.10
17:42:53 Oct 03 22:42:53 + git diff --name-only ''
17:42:53 Oct 03 22:42:53 fatal: ambiguous argument '': unknown revision or path not in the working tree.
17:42:53 Oct 03 22:42:53 Use '--' to separate paths from revisions, like this: …
```

[CI ONLY] Use release/1.10.1 branch for CI scripts

---

.jenkins/pytorch/test.sh

so that distributed CI actually runs distributed UTs. This is needed because otherwise the `SHARD_NUMBER` being defined [here](https://github.com/ROCmSoftwarePlatform/rocAutomation/blob/jenkins-pipelines/pytorch/pytorch_ci/test_pytorch_test_distributed_1.sh#L73) ends up triggering single-GPU unit tests

Move distributed case before single-GPU cases

---

.circleci/docker/common/install_rocm.sh

The ROCM_REPO will follow the distribution of Ubuntu after ROCm5.3.
e.g. "focal" is used for Ubuntu 20.04.

Fix the distribution of the Ubuntu repo for ROCm 5.3 installation

---

torch/profiler/_pattern_matcher.py

TF32 is not supported on ROCm and hence the torch/profiler/_pattern_matcher.py FP32MatMulPattern should return False for ROCm instead of checking the results of torch.cuda.get_arch_list(). Depending on the gfx arch running the test, test_profiler.py's test_profiler_fp32_matmul_pattern (main.TestExperimentalUtils) will fail otherwise.

[ROCm] add case for FP32MatMulPattern skip property

---

test/test_nn.py

Support for MIOpen immediate mode is not enabled in release/1.11 release/1.12 branches which is required
for the test_Conv2d_naive_groups test to pass - https://ontrack-internal.amd.com/browse/SWDEV-355273
Copy from https://github.com/ROCmSoftwarePlatform/pytorch/commit/ae2949bf77745b987cd9d80b4eaf58c972ed0537

Skipping test on branch with no MIOpen immediate mode support

---

test/test_nn.py

Support for MIOpen immediate mode is not enabled in release/1.11 release/1.12 branches which is required for the test_Conv2d_naive_groups test to pass 
Fixes https://ontrack-internal.amd.com/browse/SWDEV-355273
Same as https://github.com/ROCmSoftwarePlatform/pytorch/pull/1131

Skip conv2d naive groups on release/11.1

---

torch/distributed/distributed_c10d.py

Cherry-picked the fix from https://github.com/pytorch/pytorch/pull/84363.
`torch.distributed.distributed_c10d._get_global_rank` is going to be deprecated in the future when the ecosystem moves away from it, but not now.
It will be replaced with `torch.distributed.distributed_c10d.get_global_rank` later.

Cherry-pick the fix to resolve missing deprecated distributed_c10d._get_global_rank

---

test/run_test.py

Skips test_jit_cuda_fuser UTs in rocm5.4_internal_testing.
These tests were enabled in the latest IFU but are causing issues one some architectures due to lack of full NVfuser support. For now skip testing this file until fix is available. 
For full context and information:
- Follows on from: https://github.com/ROCmSoftwarePlatform/pytorch/pull/1136
- Ticket addressing: https://ontrack-internal.amd.com/browse/SWDEV-361875

Add test_jit_cuda_fuser to ROCM_BLOCKLIST

---

test/test_nn.py

Support for MIOpen immediate mode is not enabled in release/1.10, release/1.11 release/1.12 branches which is required
for the test_Conv2d_naive_groups test to pass - https://ontrack-internal.amd.com/browse/SWDEV-355273
Copy from https://github.com/ROCmSoftwarePlatform/pytorch/commit/ae2949bf77745b987cd9d80b4eaf58c972ed0537

Skipping test on branch with no MIOpen immediate mode support (release/1.10)

---

aten/src/ATen/native/cuda/layer_norm_kernel.cu

Cherry picks upstream updates to the Apex layer_norm port.
https://github.com/pytorch/pytorch/pull/87635
https://github.com/pytorch/pytorch/pull/87726
Needs to make into 5.5 release
Identical to 5.4 PR
https://github.com/ROCmSoftwarePlatform/pytorch/pull/1146

backwards apex layer_norm cherry pick - 5.5

---

aten/src/ATen/cuda/Atomic.cuh

Reverts PR https://github.com/ROCmSoftwarePlatform/pytorch/pull/1151
PR 1151 causes a regression in MI200 benchmarks, and needs to be backed out.

Revert "Remove use of atomicAddNoRet for fp32 ROCm (#1151)"

---

tools/dynamo/verify_dynamo.py

Skips check_cuda() on ROCm in tools/dynamo/verify_dynamo.py
Output:
```
Python version: 3.8.15
`torch` version: 2.0.0a0+gitc0e9a5f
CUDA version: None
/opt/conda/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py:372: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled.Consider setting `torch.set_float32_matmul_precision('high')`
warnings.warn(
/opt/conda/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py:372: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled.Consider setting `torch.set_float32_matmul_precision('high')`
warnings.warn(
/opt/conda/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py:372: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication …
```

Disable check_cuda on ROCm

---

test/inductor/test_torchinductor_opinfo.py

Initially, not all pytorch ops will have ROCm support for inductor.  This provides a mechanism to allow a check for additionally skipped ops that are supported on CUDA but not ROCm.

Add ability to skip rocm ops for inductor.

---

test/inductor/test_torchinductor_opinfo.py

Ran into an issue with https://github.com/ROCmSoftwarePlatform/pytorch/pull/1159
'inductor_skips_rocm' dict must be defined before use or following error occurs
```
_________ ERROR collecting test/inductor/test_torchinductor_opinfo.py __________
File "/var/lib/jenkins/pytorch/test/inductor/test_torchinductor_opinfo.py", line 185, in <module>
   inductor_skips_rocm["cuda"] = {
NameError: name 'inductor_skips_rocm' is not defined
```

Fix for inductor_skips_rocm

---

.circleci/docker/common/install_rocm.sh

Starting from ROCm5.5, miopenkernels packages are replaced by miopen-hip-gfx packages

Only install miopen-hip-gfx packages for ROCm5.5 onwards

---

tools/dynamo/verify_dynamo.py

Implements an equivalent `check_rocm` in `verify_dynamo.py` currently this mimics the behaviour on CUDA, throwing a warning if `MIN_ROCM_VERSION` (5.4) requirement is not met by torch or the system ROCm.
```
Python version: 3.8.13
`torch` version: 2.0.0a0+git10df28a
CUDA version: None
ROCM version: 5.4
```
cc: @zstreet87 @jithunnair-amd @dllehr-amd

Implement check_rocm for verify_dynamo.py

---

aten/src/ATen/cuda/CUDABlas.cpp
aten/src/ATen/cuda/CUDABlas.h
aten/src/ATen/cuda/Exceptions.h
aten/src/ATen/native/cuda/linalg/BatchLinearAlgebra.cpp
aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.cpp
aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.h
c10/core/TensorImpl.h
test/test_linalg.py
torch/utils/hipify/cuda_to_hip_mappings.py

New PR rebased on ~~rocm5.5_internal_testing~~ rocm5.6_internal_testing
Integrates batched versions of getrs, geqrf, getrf, getri, and gels

Integrate new batched linalg drivers

---

test/inductor/test_torchinductor.py

skipCUDAIfRocm resulted in AttributeError's as device_type does not exist for the inductor UTs. Replaced these with skipIfRocm.
Since latest triton we are able to remove some skips:
```
test_gather_scatter (cpu, cuda) - PASSED
test_index_put2 (cpu, cuda) - PASSED
test_scatter3 (cpu, cuda) FAILED - LLVM error on cuda - AtomicLoadFAdd
test_scatter_add2 (cpu, cuda) FAILED - f16 LLVM error on Atomicloadfadd
test_scatter_add3 (cpu, cuda) FAILED - f16 LLVM error on AtomicLoadFAdd
test_scatter_reduce1 FAILED -  f16 LLVM error on AtomicLoadFAdd
test_scatter_reduce2 FAILED - f16 LLVM error on AtomicLoadFAdd
test_argmax_argmin1 - PASSED
test_argmax_argmin2 - PASSED
test_index_put_issue - FAILED - LLVM ERROR: Cannot select: 0xbd744d0: f16,ch = AtomicLoadFAdd<(load store monotonic (s16) on %ir.666, …
```

Use skipIfRocm instead of skipCUDAIfRocm and unskip tests

---

test/inductor/test_torchinductor.py

Some UTs use the `@patch.object` decorator to force enable cudagraph, this PR disables two UTs which are having issues with cudagraphs on ROCm which throw `RuntimeError: Triton Error [HIP]: invalid device function`
After this PR there are 0 `RuntimeError: Triton Error [HIP]: invalid device function` occurences in `test_torchinductor.py`

Disables cudagraph on some UTs in test_torchinductor for ROCm

---

test/dynamo/test_cudagraphs.py
test/inductor/test_pattern_matcher.py
test/inductor/test_torchinductor.py
test/inductor/test_torchinductor_opinfo.py
tools/dynamo/verify_dynamo.py
torch/_dynamo/test_case.py
torch/testing/_internal/inductor_utils.py

Addresses issue occuring in upstream CI run https://github.com/pytorch/pytorch/pull/94660
- Fixes linting issues
- Imports torch in `verify_dynamo.py` for hip check
- Skips `test_cat_slice_cat` UT in `inductor/test_pattern_matcher` on ROCm
- Skips additional `Tensor-likes are not close!` errors in `test_torchinductor.py`
- Adds `patch_all()` to skip additional UT in `dynamo/test_cudagraphs`

Additional fixes for ROCm

---

test/inductor/test_torchinductor.py
test/inductor/test_torchinductor_opinfo.py

This PR makes additional temporary skips on ROCm, disables cudagraph on UTs and removes ROCm specific FIXME links.

Skipping some UTs on ROCm

---

setup.py

Added MIOpen header files to installation package for building Pytorch Extensions that requires MIOpen as a dependency.

Added MIOpen header files to installation package for ROCm.

---

setup.py

Temporary removal of triton wheel install until we find out how to conditionalise out for ROCm

[Revert this] CI workaround - disable openai triton wheel install for ROCm

---

torch/utils/hipify/cuda_to_hip_mappings.py

Cherry-pick commit https://github.com/ROCmSoftwarePlatform/pytorch/commit/66ae7075224e575a22035b30cf70b6c84d9fbb56 resulted in duplicate hipify mappings which causes PyTorch build issues in https://ontrack-internal.amd.com/browse/SWDEV-383732

[SWDEV-383732] rocm5.6_internal_testing hipify mapping fix

---

test/profiler/test_profiler_tree.py

Fixed the issue: https://ontrack-internal.amd.com/browse/SWDEV-363998
Docker image: compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-dkms-no-npi-hipclang:11597_ubuntu20.04_py3.8_pytorch_rocm5.5_internal_testing_fe7cc73
Fixed unit tests failures in test_profiler_tree.py:
test_profiler_experimental_tree
test_profiler_experimental_tree_with_memory
test_profiler_experimental_tree_with_record_function
[test_profiler_tree.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/10798203/test_profiler_tree.log)

[SWDEV-363998] Fixed test_profiler_tree issue

---

test/run_test.py

Removing temporarily, since many UT execution is blocked for below files.
Direct test file execution is fine.
https://ontrack-internal.amd.com/browse/SWDEV-383419

Removing test custom handler temporarily

---

.jenkins/pytorch/test.sh

A workaround for  #SWDEV-384803, forcing filelock installation, needs to be reverted after pytorch 2.0 is enabled on 5.6.
Same change for 5.6 branch as in 5.5 branch, https://github.com/ROCmSoftwarePlatform/pytorch/pull/1191

call filelock function

---

torch/csrc/autograd/python_variable.cpp

- This reverts commit 8f737087497d79b3d46bb2c3b32b4c59281d5223.
- SWDEV-386723 - superbench perf regression.
- This makes the rocm5.5_internal_testing state in sync with release/1.13 branch and upstream also regarding this change.

Revert "Revert "Release the GIL when munmap'ing tensors - fixes #77139 (#83623)

---

test/profiler/test_memory_profiler.py

Fixes https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3748
It is an output comparison mismatching issue. Two extra operations: create and destroy introduces the mismatching.
Initial failures are on MI100/MI200. The test runs well on MI50 and CUDA node. Operations sequence are identical through comparisons between failed and successful cases. CUDA uses 96 bytes (MI50 with 64 bytes) for each but ROCm uses 384 bytes on MI100 and 256 bytes on MI200. And logging condition is if size >= 256.
After the fix, verified entire test_memory_profiler.py tests pass on CUDA node, MI50, MI100 and MI200.

Fixed test_memory_timeline

---

.ci/pytorch/common_utils.sh
test/inductor/test_torchinductor.py
test/inductor/test_torchinductor_dynamic_shapes.py
test/inductor/test_torchinductor_opinfo.py
tools/dynamo/verify_dynamo.py
torch/_inductor/lowering.py

- Removed warnings on fallback to aten.miopen_batch_norm (due to perf diff)
- Refactored ROCm skips in opinfo
- sync with some upstream changes to remove install_triton,

ROCm changes for PyT2.0 support

---

related_commits
requirements.txt

Pinning numpy version in requirements.txt due to bug encountered on the 1.10.1 release branch with numpy>=1.24.0 (SWDEV-385058)
Companion PR to pin requirements in torchvision: https://github.com/ROCmSoftwarePlatform/vision/pull/1

Pinning numpy version for backwards compatibility of 1.10.1

---

requirements.txt

Align numpy pinning in requirements.txt to the numpy version used in vision/0.11.2 branch https://github.com/ROCmSoftwarePlatform/vision/commit/cb18e83524eacaa674319a372e8dd853b9bf2f14

Pin numpy to match vision/0.11.2

---

.ci/docker/build.sh

Fixes issues similar to https://ontrack-internal.amd.com/browse/SWDEV-382771 and https://ontrack-internal.amd.com/browse/SWDEV-387153
The conda cmake package can detect conda MKL during PyTorch build (but the regular cmake package cannot), thereby building PyTorch with MKL support. We need this change because ROCm-internal CI uses a config/BUILD_ENVIRONMENT that falls in the catchall clause of the switch-case statement in .ci/docker/build.sh, whereas upstream uses `pytorch-linux-focal-rocm-n-py3` and `pytorch-linux-focal-rocm-n-1-py3`, which have `CONDA_CMAKE=yes`.

Set CONDA_CMAKE=yes for any 'rocm' configs

---

aten/src/ATen/cuda/CUDASparse.h
aten/src/ATen/cuda/CUDASparseDescriptors.h

Fixes SWDEV-387879, but now using hipsparse version 2.4.0.

conditionally enable hipsparse const descriptors for version >= 2.4.0

---

test/profiler/test_memory_profiler.py

Fixes [JIRA ticket](https://ontrack-internal.amd.com/browse/SWDEV-395420) by modification of logging threshold of memory profiling. Before the fix, the issue only happens on MI210/MI250. Full tests have been verified on MI250 after this change.

Fixed SWDEV-395420 - modified logging threshold for memory profiling

---

test/profiler/test_memory_profiler.py

Cherry pick of https://github.com/ROCmSoftwarePlatform/pytorch/commit/77f1f08ad3670fd0616a88403b0100182ea25cd2
Same fail observed in SWDEV-384825
```
======================================================================
FAIL: test_memory_timeline (__main__.TestMemoryProfilerE2E)
File "profiler/test_memory_profiler.py", line 1488, in test_memory_timeline
self.assertExpectedInline(
File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/expecttest/__init__.py", line 262, in assertExpectedInline
self.assertMultiLineEqualMaybeCppStack(expect, actual, msg=help_text)
File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/expecttest/__init__.py", line 281, in …
```

SWDEV-398062 modified logging threshold for memory profiling

---

CHANGELOG.md
torch/testing/_internal/common_fsdp.py

This PR fixes UTs:  test_fsdp_uneven and test_fsdp_tp_integration in SWDEV-396381. 
This PR limits the nranks to 8GPUs if there are more than 8GPUs in a node. This avoids any key error trying to access for nodes greater than 8 as the test seems to be very small.

[SWDEV-396381] FSDP UT failures

---

.circleci/docker/common/install_conda.sh

Failure observed during docker build in http://rocm-ci.amd.com/view/Release-5.6/job/framework-pytorch-1.12-ci_rel-5.6/28
```
[2023-06-11T08:49:13.999Z] [91m++ conda install -q -y cmake
[2023-06-11T08:49:18.719Z] [0mCollecting package metadata (current_repodata.json): ...working... done
[2023-06-11T08:49:20.082Z] Solving environment: ...working... unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
[2023-06-11T08:49:21.050Z] Solving environment: ...working... unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
[2023-06-11T08:49:21.050Z] [91m
[2023-06-11T08:49:21.050Z] ResolvePackageNotFound: 
[2023-06-11T08:49:21.050Z]   - conda==23.3.1
```
Tested successfully via: …

[release/1.12] Fix conda error during docker build

---

.circleci/docker/common/install_conda.sh

Failure observed during PyTorch build in: http://rocm-ci.amd.com/job/framework-pytorch-1.13-ci_rel-5.6/32
```
[2023-06-13T03:02:49.015Z] ++ conda install -q -y cmake
[2023-06-13T03:03:08.270Z] Collecting package metadata (current_repodata.json): ...working... done
[2023-06-13T03:03:08.270Z] Solving environment: ...working... unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
[2023-06-13T03:03:08.270Z] Solving environment: ...working... unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
[2023-06-13T03:03:08.270Z] 
[2023-06-13T03:03:08.270Z] ResolvePackageNotFound: 
[2023-06-13T03:03:08.270Z]   - conda==23.3.1
```
Tested successfully via: http://rocm-ci.amd.com/view/Release-5.6/job/framework-pytorch-1.13-ci_rel-5.6/ …

[release/1.13] Fix conda error during docker build

---

torch/testing/_internal/distributed/distributed_test.py

Related ticket https://ontrack-internal.amd.com/browse/SWDEV-407256
Tracking issue: https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/4816
Numeric issues observed in 5.6 release/2.0 images. This PR will skip the affected UTs until further investigation.
Example fail
```
BACKEND=nccl WORLD_SIZE=2 PYTORCH_TEST_WITH_ROCM=1 HIP_VISIBLE_DEVICES=4,5 python3 test/distributed/test_distributed_spawn.py TestDistBackendWithSpawn.test_ddp_apply_optim_in_backward_grad_as_bucket_view_false
AssertionError: Tensor-likes are not close!
Mismatched elements: 9405 / 9408 (100.0%)
Greatest absolute difference: 0.06988954544067383 at index (34, 2, 0, 4) (up to 1e-05 allowed)
Greatest relative difference: 154.58467937778929 at index (7, 1, 3, 6) (up to 1.3e-06 allowed
```
NOTE: gloo backend …

[SWDEV-407256] - Temporarily skip distributed_spawn failures

---

.ci/pytorch/common_utils.sh
.ci/pytorch/test.sh

By default when testing locally TEST_CONFIG is not set. This results in OpenAI's triton being installed in the install_triton path (as opposed to doing nothing at all)
This issue causes failures in inductor UTs on ROCm when run with test.sh
```
inductor/test_torchinductor_opinfo.py::TestInductorOpInfoCUDA::test_comprehensive___radd___cuda_float16 /usr/bin/ld: cannot find -lcuda
raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: compile_fx_wrapper raised CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmptgpf59c5/main.c', '-O3', '-I/root/.local/lib/python3.8/site-packages/triton/third_party/cuda/include', '-I/opt/conda/envs/py_3.8/include/python3.8', '-I/tmp/tmptgpf59c5', '-shared', '-fPIC', '-lcuda', '-o', …
```

Do not reinstall triton if BUILD_ENVIRONMENT OR TEST_CONFIG is rocm

---

test/test_matmul_cuda.py

After discussion with the rocBLAS team it turns out our common testing method of floating point errors is flawed. The conclusions are
1) Relative tolerance parameter (rtol) may cause false negatives and
should be avoided;
2) Absolute tolerance parameter (atol) should take the number of FLOPs
into consideration.
An example for 1): [1e-5, 100.0, -100.0]. For FP16 its sum is 7.6e-06 (numpy CPU), and the rtol is exaggerated to 23.71%.
2) is straightforward since FP errors are accumulating.
Fixes #SWDEV-408938

[ROCM] Fixes SWDEV-408938

---

aten/src/ATen/cuda/CUDABlas.cpp

Workaround of SWDEV-407984

---

.ci/docker/common/install_rocm_magma.sh
.gitmodules
cmake/public/LoadHIP.cmake
torch/utils/hipify/cuda_to_hip_mappings.py

Fixed PyTorch build in release/2.0 branch with supporting ROCm6.0.
PyTorch build log: 
[pytorch_build.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/12318872/pytorch_build.log)
micro_benchmarking test log: 
[pytorch_microtest.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/12318874/pytorch_microtest.log)

ROCm6.0 ecosystem support

---

aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/native/miopen/Conv_miopen.cpp

(cherry picked from commit 2fd428d1d80e9ef075dd708fc578d69ef1e9478f)
Upstreamed via https://github.com/pytorch/pytorch/pull/107028
To resolve:
https://ontrack-internal.amd.com/browse/SWDEV-367256
https://ontrack-internal.amd.com/browse/SWDEV-371309
https://ontrack-internal.amd.com/browse/SWDEV-403530
https://ontrack-internal.amd.com/browse/SWDEV-403537

Add miopen determinism support for convolutions

---

test/nn/test_convolution.py

This is due to incorrect atol/rtol settings for torch.half and torch.bfloat16 data types.
Fixes #SWDEV-416500

Fix test_Conv2d_groups related errors (SWDEV-416489)

---

torch/utils/tensorboard/summary.py

Fixes SWDEV-411637.
ANTIALIAS is deprecated and has been removed in Pillow 10. Without downgrading Pillow version from 10.0.0, PIL.Image.Resampling.LANCZOS needs to be used instead.

ANTIALIAS updated to Resampling.LANCZOS

---

test/nn/test_convolution.py

Fix test_Conv2d_groups related errors
Cherry-pick https://github.com/ROCmSoftwarePlatform/pytorch/commit/e9b273df57b240f14ead07b5fda97bdf2be6673a from SWDEV-416489 https://github.com/ROCmSoftwarePlatform/pytorch/pull/1269
Fixes #420882

Fix test_Conv2d_groups related errors (SWDEV-420882)

---

.circleci/docker/requirements-ci.txt

Specified protobuf version in requirements-ci.txt. Built docker image and verified this [issue](https://ontrack-internal.amd.com/browse/SWDEV-411637?focusedId=13807080&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13807080) is resolved without manual downgrade.

Updated requirements-ci.txt with protobuf version

---

aten/src/ATen/cuda/CUDASparseDescriptors.cpp
aten/src/ATen/native/sparse/cuda/SparseBlasImpl.cpp

Fixes #SWDEV-420269
Tested with `CI=1 PYTORCH_TEST_WITH_ROCM=1  python3 test/run_test.py --continue-through-error --verbose -i test_sparse test_sparse_csr --use-pytest`
All tests passed:
```
xmllint --xpath '//testsuites/testsuite/@*' test_sparse/test_sparse-807071f7b5dbf692.xml  test_sparse_csr/test_sparse_csr-bc83509a402772ff.xml 
name="pytest"
errors="0"
failures="0"
skipped="345"
tests="2799"
time="163.612"
timestamp="2023-09-14T19:28:32.475896"
hostname="eaeb070677c3"
name="pytest"
errors="0"
failures="0"
skipped="729"
tests="4751"
time="263.728"
timestamp="2023-09-14T19:31:23.585087"
hostname="eaeb070677c3"
```

Make sampled_addmm_out_sparse_csr and spmm compatible with hipSparse >= 2.4.0

---

.circleci/docker/common/install_rocm.sh

Magma needs to be built for newer gfx targets, so use PYTORCH_ROCM_ARCH env var instead of hardcoded list of targets.

Use PYTORCH_ROCM_ARCH to define build targets for Magma for 1.10.1

---

test/run_test.py

This test suite fails only on MI300.
Further debugging is tracked by this task: https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/6065

Include test_vmap into rocm_blocklist

---

torch/testing/_internal/distributed/distributed_test.py

To resolve https://ontrack-internal.amd.com/browse/SWDEV-403530 and https://ontrack-internal.amd.com/browse/SWDEV-419837. 
For more context check upstream issue https://github.com/pytorch/pytorch/issues/111834

Skip ddp apply_optim_in_bwd tests for gloo

---

.ci/docker/centos-rocm/Dockerfile
.ci/docker/common/install_triton.sh

I have built a Centos image using the Dockerfile in this PR here: http://rocm-ci.amd.com/job/mainline-framework-pytorch-ci/1407/
With this generated docker image, I was able to verify that triton was indeed installed and working properly.

[ROCm] Build Triton in Centos for ROCm

---

torch/testing/_internal/distributed/distributed_test.py

At branch cutoff this was flakey/failing upstream https://github.com/pytorch/pytorch/issues/104526, seeing failures as of nightlies 2 weeks ago on both CUDA/ROCm and the issue was closed last week.

[do not cherry pick to 6.1] sparse_allreduce skip

---

test/dynamo/test_modules.py

This test was disabled in upstream right before our cherry-pick via https://github.com/pytorch/pytorch/issues/108838 . However, it seems to be fixed now. So, we do not want this commit to be cherry-picked in our future branches, just a quick fix for rocm6.0 branch.

[DO NOT CHERRY PICK] Disable test_modules.py:test_module_with_training_state

---

test/test_matmul_cuda.py

After talking with @pruthvistony  - this is a tolerance issue for torch.float16 on rocm on gfx90a.
```text
python torch/test/test_matmul_cuda.py -v -k test_cublas_baddbmm_large_input_2_1000_1000_1000_cuda_float16 
Test results will be stored in test-reports/python-unittest/test.test_matmul_cuda
Running tests...
test_cublas_baddbmm_large_input_2_1000_1000_1000_cuda_float16 (__main__.TestMatmulCudaCUDA) ... FAIL (2.579s)
======================================================================
FAIL [2.579s]: test_cublas_baddbmm_large_input_2_1000_1000_1000_cuda_float16 (__main__.TestMatmulCudaCUDA)
File …
```

[NO Cherry-pick] increase tolerance for torch.float16 on rocm for test_cublas_baddbmm_large_input_*_cuda_float16

---

related_commits

Update commits for vision/text/data to match the release commits for PyTorch2.1.1.
Audio update handled by https://github.com/ROCmSoftwarePlatform/pytorch/commit/98a1b69bd1d11e969d392c45cac42029631a34da

Update related_commits to match PyTorch2.1.1 versions

---

torch/testing/_internal/distributed/distributed_test.py

Skips required to resolve SWDEV-371309. Same issue as https://github.com/ROCmSoftwarePlatform/pytorch/pull/1302
Tracked on upstream issue: https://github.com/pytorch/pytorch/issues/111834

DDP hook skips on 2.0 branch.

---

.ci/docker/common/install_rocm.sh

Fix ROCm installation failure in Ubuntu22.04

---

aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.cpp
aten/src/ATen/native/cuda/linalg/CUDASolver.cpp

This also fixes a problem in `gesvd` driver when UV is not needed.
Fixes SWDEV-392430

Enable gesvda for ROCM >= 6.1

---

test/inductor/test_pattern_matcher.py
test/inductor/test_select_algorithm.py

Same issue as https://github.com/ROCmSoftwarePlatform/pytorch/pull/1294
Requires same fix in 2.1 branch due to lack of bf16 tl.dot support in the triton pin.

[SWDEV-435696] test_pattern_matcher skips cherry picked from 6.0

---

test/test_ops.py
test/test_unary_ufuncs.py
torch/testing/_internal/distributed/distributed_test.py

This PR is to skip the following unit tests
distributed/test_distributed_spawn - ERROR: test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithSpawn)
test_ops - FAIL: test_reference_testing_linalg_tensorinv_cuda_float32 (__main__.TestCommonCUDA)
test_ops - FAIL: test_variant_consistency_eager_nn_functional_conv_transpose2d_cuda_float32 (__main__.TestCommonCUDA)
test_unary_ufuncs - FAIL: test_out_arg_all_dtypes_reciprocal_cuda_complex64 (__main__.TestUnaryUfuncsCUDA)
test_unary_ufuncs - FAIL: test_out_arg_all_dtypes_sinc_cuda_complex64 (__main__.TestUnaryUfuncsCUDA)

Skip failing unit tests release/1.10.1

---

test/nn/test_convolution.py

Fix test_Conv2d_groups related errors for release/2.1 branch (SWDEV-423016)
Cherry-pick https://github.com/ROCmSoftwarePlatform/pytorch/commit/deeeb91dd3294ae93a42ca7e5c94d85e2e39b9e7 from SWDEV-416489 https://github.com/ROCmSoftwarePlatform/pytorch/pull/1269
@jithunnair-amd @pruthvistony

Fix test_Conv2d_groups related errors (SWDEV-423016) (#1269)

---

aten/src/ATen/native/RNN.cpp

Some MIOpen RNN functions (lstm, rnn, gru) can't work with empty tensors and return error "MIOpen error handling for support zero input length"
This PR disables MIOpen tor empty tensors and force to use native methods
The solution is based on condition of using CUDNN  https://github.com/pytorch/pytorch/blob/3a52147cc59b240737602d3d046080bbf6f567f1/aten/src/ATen/native/TensorProperties.cpp#L91
It also fix [test_nn.py::TestNN::test_RNN_input_size_zero](https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/6732)
@pruthvistony @jeffdaily @jithunnair-amd

Disable MIOpen for empty tensors for RNN

---

cmake/External/oort.cmake

by adding /opt/rocm/lib to RUNPATH during the build process.
Note: /opt/rocm is configurable with ROCM_PATH environment variable.
Fixes #SWDEV-443861
The actual fix is inside the triton repository: https://github.com/ROCm/triton/commit/848dea1a1aeb0fb1060d0232861323256f40881b

Fix SWDEV-443861

---

test/inductor/test_max_autotune.py

Introduce skip logic from upstream nightly into 2.1 branch to skip for Navi31.

[SWDEV-430417] Disable max_autotune UTs device not "is_big_gpu"

---

test/inductor/test_cuda_repro.py
test/inductor/test_torchinductor.py
test/inductor/test_torchinductor_opinfo.py
torch/testing/_internal/common_utils.py

To address required skips from https://ontrack-internal.amd.com/browse/SWDEV-442047 until full triton support is available

Add skipIfRocmArch decorator for Navi skips

---

c10/util/signal_handler.cpp
c10/util/signal_handler.h
test/distributed/test_c10d_nccl.py

Fixes test_c10d_nccl.py -k test_timeout_dumps_timing_enabled_True.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/120544
Approved by: https://github.com/atalman

Use condition_variable and wait_until in nccl dump on timeout

---

aten/src/ATen/miopen/AutocastRNN.cpp
test/test_cuda.py

support for autocast with rnns. Fixes test_autocast_rnn
```
root@713353bd62ea:/var/lib/jenkins/pytorch# rtest test/test_cuda.py TestCuda.test_autocast_rnn
Running tests...
/var/lib/jenkins/pytorch/torch/backends/cudnn/__init__.py:141: UserWarning: cuDNN Benchmark limit is not supported in MIOpen and will have no effect. (Triggered internally at /var/lib/jenkins/pytorch/torch/csrc/cuda/Module.cpp:1357.)
torch._C._cuda_set_cudnn_benchmark_limit(_benchmark_limit)
.
Ran 1 test in 20.334s
OK
Generating XML reports...
```

Autocast RNN support

---

test/inductor/test_torchinductor.py

Fixes test_alexnet_prefix_cuda and test_alexnet_prefix_dynamic_shapes_cuda. Upstream has also increased the threshold, although that is because they enabled channels last. We have channels last disabled by default for MI200 but not for MI300.

Increase threshold for test_alexnet_prefix

---

test/test_sparse_csr.py

release/1.13 is very old to fix, just skip test for ROCm
newer versions were fixed by this PR https://github.com/ROCm/pytorch/pull/1283

skip test_baddbmm_cuda_* for ROCm for release/1.13

---

test/inductor/test_torchinductor.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-444963

Bad import in test_torchinductor and skip torchvision related UT

---

test/inductor/test_inductor_freezing.py

These UT are disabled upstream as well. Trying to skip them in code so we remove the disabled issues and try to fix them in CI.

skip test_inductor_freezing failing UTs

---

cmake/Dependencies.cmake

C++20 mangling rules were recently added to hip-clang. This flag maintains compatibility since pytorch is at C++17. Otherwise the linker fails.

add -fclang-abi-compat=17 to HIP_HIPCC_FLAGS

---

.github/scripts/build_triton_wheel.py

* Add ROCm version to triton version
Tested via: http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/162

[release/2.1] Include rocm_version in triton version

---

.github/scripts/build_triton_wheel.py

Tested via: http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/163
cc @pruthvistony

[release/2.0] Include rocm_version in triton version

---

aten/src/ATen/native/RNN.cpp

Fix cherry-picked from upstream for release/2.2 branch
Some MIOpen RNN functions (lstm, rnn, gru) can't work with empty tensors and return error "MIOpen Error: Lengths must be > 0" This PR disables MIOpen tor empty tensors and force to use native methods.
Also fix test_nn.py::test_RNN_input_size_zero

[ROCm] Disable MIOpen for empty tensors for RNN (#117672)

---

torch/_inductor/kernel/mm_common.py

Using (128,128,64) kernel config, we saw 5-7% performance boost for resnet152 with higher batch sizes.

Add new kernel config for AMD GPUs

---

.ci/pytorch/test.sh

CPP version of aot inductor UTs were disabled upstream and in our rocm6.0 branch, but we missed this commit in release/2.1 branch.

[SWDEV-447062] - Disable cpp version of test_aot_inductor test for rocm

---

test/inductor/test_pattern_matcher.py

There was a known issue with triton where we saw errors with bfloat16. This is now fixed upstream with
https://github.com/pytorch/pytorch/pull/111129 . However, it seems that we branched off release/2.1 before the change was merged upstream. In the meantime, we can just skip these UTs.

[SWDEV-445217] test_pattern_matcher: skip bfloat16 UTs

---

.ci/docker/common/install_conda.sh

Fixes https://ontrack-internal.amd.com/browse/SWDEV-457714
Tested successfully here: http://rocm-ci.amd.com/job/framework-pytorch-2.1-ci_rel-6.1/61

[release/2.1] Skip certificate check for CentOS7 since certificate expired

---

torch/csrc/distributed/c10d/Backend.hpp
torch/csrc/distributed/c10d/ProcessGroupGloo.cpp
torch/csrc/distributed/c10d/ProcessGroupGloo.hpp

This PR is to fix https://ontrack-internal.amd.com/browse/SWDEV-447053 - test/distributed/test_distributed_spawn.py::TestDistBackendWithSpawn::test_sparse_all_reduce_sum_cuda with gloo backend.
Rebuilt PyTorch after changes and unit test runs fine.
Reference: https://github.com/pytorch/pytorch/pull/111485

Supported allreduce sparse

---

.github/scripts/build_triton_wheel.py

Follow-up to https://github.com/ROCm/pytorch/commit/16e830cee4530f2f97e4f45540400a158f270e86 to resolve issues with ROCm6.1.1 (and similar patch versions) where triton wheel wouldn't contain the patch version but torch wheel would have a dependency on the name with patch version.
Similar changes to https://github.com/ROCm/pytorch/commit/1c7726a612551daab5480f902e43ffc2cc400057, but makes patch version unconditional
This was requested by DC GPU team to simplify their scripts that use PyTorch wheels and determine the name using the ROCM build version shown here - http://mkdcvlnxapp01.amd.com/dashboard - under "Core/ROCm Release".
Tested via: http://ml-ci-internal.amd.com:8080/job/pytorch/job/dev/job/manylinux_rocm_wheels_test/56

[release/2.2] Include ROCm patch version unconditionally in triton version

---

torch/utils/hipify/cuda_to_hip_mappings.py

This PR is to add cublasGemmAlgo_t -> hipblasGemmAlgo_t to cuda_to_hip_mappings.py.
It is required for DeepSpeed transformer extension build on ROCm.

Added cublasGemmAlgo_t -> hipblasGemmAlgo_t

---

torch/_C/__init__.pyi.in
torch/_inductor/codegen/codegen_device_driver.py
torch/csrc/cuda/Module.cpp

gfx10 and gfx11 Wavefront Size is 32 compared to gfx9, which is 64. It was causing the test_multi_kernel.py test to fail.
Fail case
```
> AMD_LOG_LEVEL=3 TORCH_LOGS="+dynamo" TORCHDYNAMO_VERBOSE=1 AOT_FX_GRAPHS=1 TORCH_COMPILE_DEBUG=1 PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_multi_kernel.py -k test_reduction_scratch_buffer_cpp_wrapper 
> 
> :3:hip_module.cpp           :74  : 1406367010027 us: [pid:6817  tid:0x7ffa3ce5a740]  hipModuleGetFunction ( 0x7ffc23ed3128, 0xb997850, triton_ )
> :3:hip_module.cpp           :88  : 1406367010031 us: [pid:6817  tid:0x7ffa3ce5a740] hipModuleGetFunction: Returned hipSuccess :
> :3:hip_module.cpp           :434 : 1406367010037 us: [pid:6817  tid:0x7ffa3ce5a740]  hipModuleLaunchKernel ( 0x0xc674930, 2, 1, 1, 128, 1, 1, 0, stream:<null>, …
```

[ROCm] skip warp update to 64 for gfx10 and gfx11

---

aten/src/ATen/cuda/CUDABlas.cpp
aten/src/ATen/native/cuda/Blas.cpp
test/test_matmul_cuda.py

Reverts the AMAX workaround now that hipblasLT supports AMAX. hipblasLT does not like getting nullptr for scale D so we create a dummy scalar tensor with the value of 1.0 to pass in the event we are about to pass a nullptr

[ROCm] Integrate hipblasLT AMAX_D pointer

---

test/test_matmul_cuda.py

reformat rocm related skips to reflect current f8 functionality

Enable e5m2 x e4m3 test in test_float8_scale

---

test/functorch/test_ops.py

skip vmapvjpvjp_linalg_householder_product_cuda_float32

---

.lintrunner.toml
test/run_test.py
tools/dynamo/verify_dynamo.py
torch/_vendor/README.md
torch/_vendor/packaging/LICENSE
torch/_vendor/packaging/LICENSE.APACHE
torch/_vendor/packaging/LICENSE.BSD
torch/_vendor/packaging/__init__.py
torch/_vendor/packaging/_structures.py
torch/_vendor/packaging/version.py
torch/torch_version.py
torch/utils/cpp_extension.py

Tested successfully via http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/295/
Tested that TorchVersion doesn't give an import error for `packaging`.
```
root@588a082ce4d1:/# pip list | grep setuptools
setuptools          69.5.1
root@588a082ce4d1:/# python -c 'import torch.torch_version; print(torch.torch_version.TorchVersion("1.0.0"))'
1.0.0
```

[release/2.0] Remove references to `pkg_resources.packaging`

---

.lintrunner.toml
test/run_test.py
torch/_vendor/README.md
torch/_vendor/packaging/LICENSE
torch/_vendor/packaging/LICENSE.APACHE
torch/_vendor/packaging/LICENSE.BSD
torch/_vendor/packaging/__init__.py
torch/_vendor/packaging/_structures.py
torch/_vendor/packaging/version.py
torch/torch_version.py
torch/utils/cpp_extension.py

Tested successfully via: http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/296/
Tested that TorchVersion doesn't give an import error for packaging.
```
root@33e1cabcaf4e:/# pip list | grep setuptools
setuptools          70.0.0
root@33e1cabcaf4e:/# python -c 'from pkg_resources import packaging'
<string>:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
File "<string>", line 1, in <module>
ImportError: cannot import name 'packaging' from 'pkg_resources' (/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py)
root@33e1cabcaf4e:/# python -c 'import torch.torch_version; print(torch.torch_version.TorchVersion("1.0.0"))'
1.0.0
```

[release/1.13] Remove references to `pkg_resources.packaging`

---

test/run_test.py
torch/_C/__init__.pyi.in
torch/csrc/cuda/Module.cpp
torch/testing/_internal/common_utils.py
torch/utils/collect_env.py

This PR is to add gcnArchName in release/2.0 branch.
This is also a follow up PR (https://github.com/ROCm/pytorch/pull/1382) to fix API call and move helper location.
Rebuilt PyTorch and quick tests run fine.

Added gcnArchName

---

test/test_modules.py

This is a cherry-pick of an upstream commit to fix https://ontrack-internal.amd.com/browse/SWDEV-462482
Fix https://github.com/pytorch/pytorch/issues/125967 . The test actually fail for empty 4D or 5D tensors when checking for memory format.
I'm not exactly sure what recent inductor change cause the failure, but it may be not that important to maintain strides for an empty tensor. (?)
I just skip the check for empty tensor.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/126593
Approved by: https://github.com/ezyang

don't check memory format for empty tensors (#126593)

---

aten/src/ATen/native/transformers/hip/flash_attn/flash_api.hip

- The Rank of logsumexp Tensor must be 3, which was considered for internal use only but apparently exposed to UTs.
- The stream should be selected after picking the current device according to input tensor. Not sure if it is critical to SWDEV-459623 but it is no harm to fix this as well.
Fixes #SWDEV-459623
Tested on `rocm-framework-51`. Log:
```
(py_3.10) xinyazha@12fd1640b6b7:~/rocm-pytorch$ PYTORCH_TEST_WITH_ROCM=1 python test/distributed/_tensor/test_attention.py -k test_ring_attention_compile_attention -v
test_ring_attention_compile_attention_fn0 (__main__.RingAttentionTest) ... ok
test_ring_attention_compile_attention_fn1 (__main__.RingAttentionTest) ... [rank1]:[W530 08:05:10.073449407 ProcessGroupNCCL.cpp:1113] WARNING: process group has NOT been destroyed before it is being …
```

Fix SWDEV-459623

---

aten/src/ATen/native/Normalization.cpp
aten/src/ATen/native/miopen/BatchNorm_miopen.cpp
test/test_nn.py

* Non-static PYTORCH_MIOPEN_SUGGEST_NHWC env variable enables MIOpen batchnorm for NHWC and can be changed at runtime
* New unit test `test_batchnorm_nhwc_miopen` compares NHWC MIOpen batchnorm with native NHWC batchnorm to verify miopen. It works only with fp32 input, fp16 and fp64 will be done soon in another PR

Enable NHWC batchnorm for miopen

---

tools/stats/monitor.py
torch/cuda/memory.py

Summary:
https://github.com/pytorch/pytorch/pull/119182 uses an API that has already been deprecated by https://github.com/ROCm/amdsmi/commit/c551c3caedbd903ba828e7fdffa5b56d475a15e7. So fixing this in a backward compatible way
Reviewed By: nmacchioni
Differential Revision: D57711088
(cherry picked from commit a04cda7cd2a63a6da47f545dd5e29ed8e2b6f719)

[SWDEV-464578] [AMD] Fix deprecated amdsmi api (#126962)

---

.automation_scripts/run_pytorch_unit_tests.py

Dump all the test log output into a file called `pytorch_unit_tests.log` in the timestamped directory created for the run eg.
`.automation_logs/20240614_09-04-01/`

Print consolidated log file for pytorch unit test automation scripts

---

torch/_inductor/runtime/triton_heuristics.py

https://ontrack-internal.amd.com/browse/SWDEV-463139 - resolves issue observed with long sequence size observed in gpt-fast.
Without this change we exceed the max grid as XBLOCK is too small.

Scale XBLOCK in triton reduction configs to avoid hitting max grid

---

test/functorch/test_ops.py
test/profiler/test_profiler_tree.py

Skipping the following test
test/profiler/test_profiler_tree.py:test_profiler_experimental_tree
test/profiler/test_profiler_tree.py:test_profiler_experimental_tree_with_memory
Fixing
test/functorch/test_ops.py:test_vmapvjpvjp_linalg_householder_product_cuda_float32
by adjusting the TOL value.

[release/2.1] fix test_vmapvjpvjp and skip test_profiler_experimental_tree

---

related_commits

Tested using http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/427
Artifacts generated: http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/427/artifact/result.cp39/*view*/
`apex-1.3.0+rocm6.2.0-cp39-cp39-linux_x86_64.whl pushed to http://compute-artifactory.amd.com/artifactory/compute-pytorch-rocm/compute-rocm-rel-6.2/4/apex-1.3.0+rocm6.2.0-cp39-cp39-linux_x86_64.whl`
L0 tests ran fine with: `bash run_rocm.sh 2>&1 | tee run_rocm.log`

[release/2.3] Update apex commit to pick up wheel-related changes

---

test/distributed/fsdp/test_fsdp_clip_grad_norm.py
test/distributed/fsdp/test_fsdp_optim_state.py
test/distributed/fsdp/test_fsdp_use_orig_params.py
test/distributed/test_c10d_gloo.py

I see this one failing consistently failing due to tensor-likes are not equal:
python test/distributed/test_c10d_gloo.py -k test_reduce_stress_cuda
These are flaky. I see them run fine when I run individually, however, they timeout in the bunch:
test/distributed/fsdp/test_fsdp_clip_grad_norm.py -k test_no_gradients
test/distributed/fsdp/test_fsdp_optim_state.py -k test_optim_state_dict_nested
test/distributed/fsdp/test_fsdp_optim_state.py -k test_scatter_full_optim_state_dict
test/distributed/fsdp/test_fsdp_optim_state.py -k test_rekey_optim_state_dict
test/distributed/fsdp/test_fsdp_optim_state.py -k test_shard_full_optim_state_dict
test/distributed/fsdp/test_fsdp_optim_state.py -k test_full_optim_state
test/distributed/fsdp/test_fsdp_use_orig_params.py -k …

SWDEV-469009 - skips for flaky distributed tests

---

torch/_inductor/runtime/triton_heuristics.py

The `is_hip` logic is flakey on 6.2_internal_testing, bringing in this change to avoid unexpected issues due to `device_prop.regs_per_multiprocessor` not being available on ROCm in this branch. This will be adopted upstream and cherry picked into 6.3 via https://github.com/pytorch/pytorch/pull/129663
This issue was raised in trying to reproduce a defect in PLAT-160450 and will help the investigation into this issue.

[NO CP] [Inductor] Use torch.version.hip to conditionalise out dynamic rblock scaling

---

test/profiler/test_profiler.py

`test_oom_tracing` expects OutOfMemory exception by allocating a large tensor. MI300X has enough memory to allocate test tensor
This PR increases tensor size with a large margin to force OutOfMemory exception on MI300X and future GPU generations
@SkipIfRocm  for `test_profiler_cuda_sync_events` was cherry-picked from upstream https://github.com/ROCm/pytorch/commit/57fb8860f3d55c2f24986e4afbd643766c649a03 for [SWDEV-452384](https://ontrack-internal.amd.com/browse/SWDEV-452384)

[release/2.2] fix test_oom_tracing and skip test_profiler_ cuda_sync_events

---

test/profiler/test_profiler.py

test_oom_tracing expects OutOfMemory exception by allocating a large tensor. MI300X has enough memory to allocate test tensor 
This PR increases tensor size with a large margin to force  OutOfMemory exception on MI300X and future GPU generations

[rocm6.3_internal_testing] Fix test_oom_tracing by increasing tensor size

---

test/profiler/test_profiler.py

test_oom_tracing expects OutOfMemory exception by allocating a large tensor. MI300X has enough memory to allocate test tensor
This PR increases tensor size with a large margin to force OutOfMemory exception on MI300X and future GPU generations

[release/2.3] Fix test_oom_tracing by increasing tensor size

---

test/profiler/test_profiler.py

test_oom_tracing expects OutOfMemory exception by allocating a large tensor. MI300X has enough memory to allocate test tensor
This PR increases tensor size with a large margin to force OutOfMemory exception on MI300X and future GPU generations

[release 2.0] Fix test_oom_tracing by increasing tensor size for

---

test/profiler/test_profiler.py

test_oom_tracing expects OutOfMemory exception by allocating a large tensor. MI300X has enough memory to allocate test tensor
This PR increases tensor size with a large margin to force OutOfMemory exception on MI300X and future GPU generations

[release/1.13] Fix test_oom_tracing by increasing tensor size

---

torch/cuda/__init__.py

Cherry pick of https://github.com/pytorch/pytorch/pull/130331/files
```
Extending on the change in https://github.com/pytorch/pytorch/pull/127729
Depending on gcnArch the API to return socket power will change. This will help us handle both cases for now until this is consolidated in the future.
```
MI200
Current socket power: N/A
Average socket power: 94
MI300
Current socket power: 717
Average socket power: N/A
Fixes https://ontrack-internal.amd.com/browse/SWDEV-472265

[rocm6.2_internal_testing] [ROCm] [SWDEV-472265] Return correct AMDSMI socket_power metric

---

torch/cuda/__init__.py

ROCm6.1 provided info in the `cur_clk` field
ROCm6.2 provided info in the `clk` field
Keep conditional logic for backward-compatibility
Cherry pick of https://github.com/ROCm/pytorch/commit/20086f5d363cf9fb2c378c46d9d90143ba3835bf + https://github.com/ROCm/pytorch/commit/4d3bd90442cae7bc9f22e30a28e03b6467dd81fd
Will upstream change shortly

Update clock info metric AMDSMI

---

.ci/pytorch/test.sh

(cherry picked from commit 08dc08c40e9d4938c9586ce3784bde029f1e23d4)
Fixes SWDEV-471949

[release/2.2] Disable cpp version of test_aot_inductor test for rocm (#1397)

---

test/functorch/test_ops.py
test/profiler/test_profiler_tree.py

cherry-picked from https://github.com/ROCm/pytorch/commit/7e963910dcebdb6726bd3f08b4784338c19d8869 for release/2.2
Skipping the following test
test/profiler/test_profiler_tree.py:test_profiler_experimental_tree
test/profiler/test_profiler_tree.py:test_profiler_experimental_tree_with_memory
Fixing
test/functorch/test_ops.py:test_vmapvjpvjp_linalg_householder_product_cuda_float32
by adjusting the TOL value.

[release/2.2] fix test_vmapvjpvjp and skip test_profiler_experimental_tree

---

torch/_inductor/runtime/triton_heuristics.py

As part of our previous fix for https://ontrack-internal.amd.com/browse/SWDEV-463139 I brought in an additional small change from upstream developments to more sensibly set ROCm defaults for num_warps in reduction kernels as this has reported to improve performance for some workloads by upstream developers https://github.com/pytorch/pytorch/pull/125084
More analysis is needed for us to investigate this change as some regressions are observed with this.
AMD Triton team recommend num_warps=8 as ROCm default to improve our latency, but for the case mentioned upstream it benefits from this change as the TTGIR implements a wider load and has improved vectorisation. We will need to seek out a better middle ground in the future. Current thoughts are that we could reduce num_warps and increase …

[NO CP] [SWDEV-472647] Revert default_num_stages change on ROCm

---

test/test_cuda.py
test/test_cuda_nvml_based_avail.py
torch/cuda/__init__.py

Before initializing CUDA, it can change by modifying CUDA_VISIBLE_DEVICES
Cherry pick of - https://github.com/pytorch/pytorch/pull/122815 
Fixes https://ontrack-internal.amd.com/browse/SWDEV-461863

[Release 2.3] [SWDEV-461863] Don't cache device_count if CUDA isn't initialised yet

---

test/test_cuda.py
test/test_cuda_nvml_based_avail.py
torch/cuda/__init__.py

Before initializing CUDA, it can change by modifying CUDA_VISIBLE_DEVICES
Cherry pick of - https://github.com/pytorch/pytorch/pull/122815 
Fixes https://ontrack-internal.amd.com/browse/SWDEV-461863

[Release 2.2] [SWDEV-461863] Don't cache device_count if we haven't initialized CUDA yet 

---

aten/src/ATen/cuda/CUDAGraph.cpp
torch/utils/hipify/cuda_to_hip_mappings.py

There is a new hip feature where they do not free hipGraph memory as soon as hipGraphExecDestroy is called. This is to support async work on the GPU. See this for more details:
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#cuda-user-objects
We noticed this issue when an allreduce op inside a hipGraph hung. Essentially, ncclCommAbort was waiting for all GPU activity to finish. However, since hipGraph memory was technically still in use, we had an infinite hang. So, I added an extra hipDeviceSynchronize in CUDAGraph's destructor to esure that memory is freed and got
test_allreduce_in_cudagraph UT to pass.
However, when I ran this on CUDA machine, I noticed that they did not require this extra sync in order to successfully run the UT. It seems that they were calling …

[rocm6.2_internal_testing] [SWDEV-469514] hipGraphExecDestroy requires an explicit sync

---

torch/csrc/utils/tensor_numpy.cpp

Test plan:
```
% python -c "import torch;import numpy;print(numpy.__version__, torch.tensor(numpy.arange(3, 10)))"
2.1.0.dev0+git20240312.9de8a80 tensor([3, 4, 5, 6, 7, 8, 9])
% python -c "import torch;print(torch.rand(3, 3).numpy())"
[[0.0931946  0.44874293 0.8480404 ]
[0.93877375 0.10188377 0.67375803]
[0.02520031 0.89019287 0.5691561 ]]
```
Fixes https://github.com/pytorch/pytorch/issues/121798
Pull Request resolved: https://github.com/pytorch/pytorch/pull/121880
Approved by: https://github.com/albanD
(cherry picked from commit 38d9bb5abcc31ba97927a5399b88afe2cf60bf64)

[release/1.13] Make PyTorch compilable against upcoming Numpy-2.0 (#121880) (#123380)

---

CMakeLists.txt
caffe2/CMakeLists.txt
cmake/CheckAbi.cmake

Fixes issue whereby setting the `_GLIBCXX_USE_CXX11_ABI` env var (and thus the Cmake define `GLIBCXX_USE_CXX11_ABI`) would still not explicitly set the compiler cxx flags

[release/1.13] CXX11 ABI fix to respect GLIBCXX_USE_CXX11_ABI=0

---

related_commits

Update `related_commits` for `release/1.13` to use torchvision with numpy<2 requirements from `ROCm/vision` repo
Also change `ROCmSoftwarePlatform/apex` repo link to `ROCm/apex`
Uses torchvision fix in https://github.com/ROCm/vision/commit/befa25624b54fffe82bac99c73661e4bf0c0e612

[release/1.13] update torchvision in related_commits

---

related_commits

Update `related_commits` for `release/2.0` to use torchvision with numpy<2 requirements from `ROCm/vision` repo
Also change `ROCmSoftwarePlatform/apex` repo link to `ROCm/apex`
Uses torchvision fix in https://github.com/ROCm/vision/commit/c5e28d62174bb69801e5512ea2e63409151060b6

[release/2.0] update torchvision in related_commits

---

requirements.txt
setup.py

(cherry picked from rocm6.2_internal_testing branch, commit 1feb1a81136120c40dd0e68d38829109eb16af03)
fix for:
- test_dynamic_shapes.py::TestFloorDiv::test_floordiv_*
- test_dynamic_shapes.py::TestPySymInt::test_sym_*

[release/2.2] SWDEV-472761: limit sympy version to 1.12.1 or lower

---

related_commits

Update `related_commits` for `release/2.1` to use torchvision with numpy<2 requirements from `ROCm/vision` repo
Also were changed `ROCmSoftwarePlatform/apex` repo link to `ROCm/apex`
and `ROCmSoftwarePlatform/audio` to `ROCm/audio`
Uses https://github.com/ROCm/vision/commit/8c34ea8a172336567050a73dc7fffa8689a6ae11

[release/2.1] update torchvision in related_commits

---

related_commits

Update `related_commits` for `release/2.2` to use torchvision with numpy<2 requirements from `ROCm/vision` repo
Also `ROCmSoftwarePlatform/apex` repo link was changed to `ROCm/apex`
Uses https://github.com/ROCm/vision/commit/f74325507630b1fff230abdf618e03c8af17de89

[release/2.2] update torchvision in related_commits

---

related_commits

Update `related_commits` for `release/2.3` to use torchvision with numpy<2 requirements from `ROCm/vision` repo
Also `ROCmSoftwarePlatform/apex` repo link was changed to `ROCm/apex`
Uses https://github.com/ROCm/vision/commit/68ba7ec9a80887a4ebf208f9388ab0362ec7610a

[release/2.3] update torchvision in related_commits

---

.automation_scripts/run_pytorch_unit_tests.py

* Report execution time
* Sanity check that distributed config is not run with only 1 GPU visible

[SWDEV-466849] Enhancements for PyTorch UT helper scripts

---

c10/cuda/CUDAMacros.h

This is an ongoing pain point of PyTorch - https://github.com/pytorch/pytorch/issues/115331 
We will bring this change into the earlier release branches which will let us increase compile limit to 120 GPUs (setting this to 128 causes some issues according to upstream developers) https://github.com/pytorch/pytorch/pull/121076 
Besides this there is ongoing work to increase max gpus to 512 by upstream developers https://github.com/pytorch/pytorch/pull/119639  but this is unable to be merged until caffe2 is removed via https://github.com/pytorch/pytorch/pull/122527.
I have left a comment asking for an update https://github.com/pytorch/pytorch/pull/119639#issuecomment-2242609917 for now lets use the 120 limit and if required in the future we can see if we can get the draft fix enabled on our …

[Release 2.2] [SWDEV-461863] Temporarily increased compile time limit of #GPUs to 120

---

c10/cuda/CUDAMacros.h

This is an ongoing pain point of PyTorch - https://github.com/pytorch/pytorch/issues/115331%C2%A0
We will bring this change into the earlier release branches which will let us increase compile limit to 120 GPUs (setting this to 128 causes some issues according to upstream developers) https://github.com/pytorch/pytorch/pull/121076%C2%A0
Besides this there is ongoing work to increase max gpus to 512 by upstream developers https://github.com/pytorch/pytorch/pull/119639%C2%A0 but this is unable to be merged until caffe2 is removed via https://github.com/pytorch/pytorch/pull/122527.
I have left a comment asking for an update https://github.com/pytorch/pytorch/pull/119639#issuecomment-2242609917%C2%A0for now lets use the 120 limit and if required in the future we can see if we can get the draft …

[Release 2.1] [SWDEV-461863] Temporarily increased compile time limit of #GPUs to 120

---

c10/cuda/CUDAMacros.h

This is an ongoing pain point of PyTorch - https://github.com/pytorch/pytorch/issues/115331%C2%A0
We will bring this change into the earlier release branches which will let us increase compile limit to 120 GPUs (setting this to 128 causes some issues according to upstream developers) https://github.com/pytorch/pytorch/pull/121076%C2%A0
Besides this there is ongoing work to increase max gpus to 512 by upstream developers https://github.com/pytorch/pytorch/pull/119639%C2%A0 but this is unable to be merged until caffe2 is removed via https://github.com/pytorch/pytorch/pull/122527.
I have left a comment asking for an update https://github.com/pytorch/pytorch/pull/119639#issuecomment-2242609917%C2%A0for now lets use the 120 limit and if required in the future we can see if we can get the draft …

[Release 2.0] [SWDEV-461863] Temporarily increased compile time limit of #GPUs to 120 

---

test/functorch/test_ops.py
test/inductor/test_select_algorithm.py
test/profiler/test_profiler_tree.py
test/test_matmul_cuda.py

Fixes for SWDEV-462203 
cherry-picked from https://github.com/ROCm/pytorch/commit/bf4c47816ef0c631545973384fc704dca0f9523e
Skipping for 
- test/inductor/test_select_algorithm.py::TestSelectAlgorithm::test__int_mm
Cherry-picked from release/2.2 https://github.com/ROCm/pytorch/commit/0766b9c680c93bdd3516eed9ac65358df921d3a6
Skipping the following test
- profiler/test_profiler_tree.py:test_profiler_experimental_tree
- profiler/test_profiler_tree.py:test_profiler_experimental_tree_with_memory
Fixing
- functorch/test_ops.py:test_vmapvjpvjp_linalg_householder_product_cuda_float32 by adjusting the TOL value.
cherry-picked from rocm6.3_internal_testing https://github.com/ROCm/pytorch/commit/cb0e9ad04d09b4f28f984f47ce25b56880770bdb
Fixing
- …

[release2.3] fix test_vmapvjpvjp and skip test_profiler_experimental_tree

---

aten/src/ATen/cuda/CUDAGraph.cpp
aten/src/ATen/cuda/CUDAGraph.h

Fix CUDAGraph `HIP error: invalid device ordinal. Aborted (core dumped)` error after this PR https://github.com/ROCm/pytorch/pull/1471 for some CUDAGraph tests 
Tested on `test_cuda.py::TestCuda::test_graph_make_graphed_callables_*`
and `distributed/test_c10d_nccl.py::ProcessGroupNCCLTest::test_allreduce_in_cudagraph`
Skip device sync in the `~CUDAGraph()` destructor if `capture_begin()` method was not used and `capture_dev_` variable is not initialized
Additional bool variable `device_captured_` was introduced and used to track `capture_dev_` variable initialization for ROCm>=6.2. 
Also it can be done in another way using a magic value (-1) as not initialized `capture_dev_` value

[release/2.2] cudagraph explicit sync only after capture_begin()

---

.circleci/docker/requirements-ci.txt

limits `pytest==7.3.2' in .ci/docker/requirements-ci.txt file like in [release/2.1+](https://github.com/ROCm/pytorch/blob/9712f03685c162337c2b15c75821b22592456e5d/.ci/docker/requirements-ci.txt#L143)
Fix some distributed tests from https://ontrack-internal.amd.com/browse/SWDEV-471962
```
FAILED distributed/pipeline/sync/test_pipe.py::test_batch_size_indivisible - TypeError: exceptions must be derived from Warning, not <class 'NoneType'>
FAILED distributed/pipeline/sync/test_pipe.py::test_batch_size_small - TypeError: exceptions must be derived from Warning, not <class 'NoneType'>
```
verified in the test build http://rocm-ci.amd.com/job/framework-pytorch-2.2-ci_rel-6.2/46/
```
distributed/pipeline/sync/test_pipe.py::test_batch_size_indivisible PASSED …
```

[release/1.13] limit pytest version in requirements-ci.txt

---

related_commits

Update torchvision in the releted_commits file 
Use https://github.com/ROCm/vision/commit/69e03dbe3ab4285bccec5aa429f0b0265dc05060 commit from rocm6.2_internal_testing branch

Update torchvision in related_commits to keep numpy<2

---

aten/src/ATen/cuda/CUDAGraph.cpp
aten/src/ATen/cuda/CUDAGraph.h

Skip device sync in the ~CUDAGraph() destructor if capture_begin() method was not used and capture_dev_ variable is not initialized
* cudagraph explicit sync only after capture_begin
* use 'capture_dev_=-1' as not initialized value
* use named constant instead of magic '-1' value
(cherry picked from release/2.2 commit eb433b9aa6433632df92e1a1d728f00f56212ed2)

[rocm6.2_internal_testing] cudagraph explicit sync only after capture_begin() (#1492)

---

aten/src/ATen/cuda/CUDAGraph.cpp
aten/src/ATen/cuda/CUDAGraph.h

Skip device sync in the ~CUDAGraph() destructor if capture_begin() method was not used and capture_dev_ variable is not initialized
* cudagraph explicit sync only after capture_begin
* use 'capture_dev_=-1' as not initialized value
* use named constant instead of magic '-1' value
(cherry picked from release/2.2 commit eb433b9aa6433632df92e1a1d728f00f56212ed2)

[release/2.1] cudagraph explicit sync only after capture_begin() (#1492)

---

aten/src/ATen/cuda/CUDAGraph.cpp
aten/src/ATen/cuda/CUDAGraph.h

Skip device sync in the ~CUDAGraph() destructor if capture_begin() method was not used and capture_dev_ variable is not initialized
* cudagraph explicit sync only after capture_begin
* use 'capture_dev_=-1' as not initialized value
* use named constant instead of magic '-1' value
(cherry picked from release/2.2 commit eb433b9aa6433632df92e1a1d728f00f56212ed2)

[release/1.13] cudagraph explicit sync only after capture_begin() (#1492)

---

.ci/pytorch/test.sh

test_aot_inductor was not enabled in 2.2, however, there are direct calls to run test_aot_inductor UTs in inductor_distributed.

[release/2.2][SWDEV-476861] Skip test_aot_inductor distributed UTs

---

test/inductor/test_torchinductor.py
test/inductor/test_torchinductor_dynamic_shapes.py

Fixes inductor.test_torchinductor_dynamic_shapes::TestInductorDynamicCUDA::test_item_unbacked_stride_nobreak_cuda

Added functions imports

---

.circleci/docker/requirements-ci.txt

Fix "numpy.typing has no attribute NDArray" for release/1.13
The latest version of `pillow` 10.4.0 uses a higher version of `numpy` (https://github.com/python-pillow/Pillow/blob/9b4fae77178e827ab17118fbc89c739ffd6a0fab/src/PIL/_typing.py#L10)

[release/1.13] pin pillow version to 10.3.0

---

.automation_scripts/run_pytorch_unit_tests.py

* Fail earlier for distributed-on-1-GPU scenario
* print cmd in consolidated log with prettier formatting
* python->python3
Fixes https://ontrack-internal.amd.com/browse/SWDEV-477264

PyTorch unit test helper scripts enhancements

---

.ci/docker/common/cache_vision_models.sh
.ci/docker/requirements-ci.txt

This PR pins sympy==1.12.0 in the .ci/docker/requirements-ci.txt file
Also it skips pytorch-nightly installation in docker images
Installation of pytorch-nightly is needed to prefetch mobilenet_v2 avd v3 models for some tests.
Came from https://github.com/ROCm/pytorch/commit/85bd6bc0105162293fa0bbfb7b661f85ec67f85a
Models are downloaded on first use to the folder /root/.cache/torch/hub
But pytorch-nightly installation also overrides .ci/docker/requirements-ci.txt settings and upgrades some of python packages (sympy from 1.12.0 to 1.13.0) which causes several 'dynamic_shapes' tests to fail
Skip prefetching models affects these tests without any errors (but **internet access required**):
- python test/mobile/model_test/gen_test_model.py mobilenet_v2
- python …

[release/2.2] pin sympy==1.12.0 and skip pytorch-nightly installation

---

.ci/docker/requirements-ci.txt

Just pin sympy==1.12.1 in the requirements-ci.txt file to fix some **dynamic_shapes** tests

[release/2.0] pin sympy==1.12.1 in the requirements-ci.txt file

---

test/inductor/test_cuda_repro.py
test/inductor/test_torchinductor.py
test/inductor/test_torchinductor_opinfo.py

Relates to https://ontrack-internal.amd.com/browse/SWDEV-461590

[Navi] [Inductor] Unskip Navi inductor UTs

---

torch/cuda/__init__.py

Fix from https://github.com/pytorch/pytorch/pull/132990 cherry picked into 6.2 to be resolved for 6.2.1
"""
This is a bugfix that was recently encountered in ROCm/Deepspeed. Currently if a library installs pynvml and runs on ROCm pytorch will break as _HAS_PYNVML is set to true and it will attempt to use amdsmi library for the device_count call which will not be installed.
This fix will set _HAS_PYNVML to false on ROCm if amdsmi is not installed.
"""
Will need to be cherry picked to release/2.3 and rocm6.3_internal_testing also

[SWDEV-477447] Set _HAS_PYNVML to false if amdsmi not installed

---

requirements.txt

To resolve issue when building triton for py3.12 eg. http://rocm-ci.amd.com/blue/organizations/jenkins/framework-pytorch-ci-phantom_rel-6.2/detail/framework-pytorch-ci-phantom_rel-6.2/41/pipeline/:
```
[2024-08-16T23:15:02.632Z]       downloading and extracting https://oaitriton.blob.core.windows.net/public/llvm-builds/llvm-ed4e505c-ubuntu-x64.tar.gz ...
[2024-08-16T23:15:02.632Z]       error: HTTP Error 404: The specified blob does not exist.
[2024-08-16T23:15:02.632Z]       [end of output]
```

[release/2.3] Use newer version of optree for py3.12+

---

test/distributed/_tensor/test_attention.py

`_c10d_functional_autograd::all_to_all_single` seems not implemented on ROCm.
Note: another unfixed problem is the mismatching of outputs between torch.ops.aten._scaled_dot_product_flash_attention and _scaled_dot_product_chunk_flash_attention. We need fix both problems to enable this UT.
Fixes SWDEV-459618

Mitigates SWDEV-459618

---

test/test_cuda.py

Test was enabled in the upstream https://github.com/pytorch/pytorch/pull/121539
But failed with "AssertionError: Tensor-likes are not close! Mismatched elements: 30 / 30 (100.0%)"
in release/2.3 and rocm6.3_internal_testing on MI300 and passed on MI210
Pass with AMD_LOG_LEVEL=3 on MI300
Need to dig deeper
Skip TestCuda::test_autocast_rnn as in other releases (https://ontrack-internal.amd.com/browse/SWDEV-468117)
release/2.1 https://github.com/ROCm/pytorch/blob/073f5dcaebc61b69a71de8918e574053bf95c40b/test/test_cuda.py#L2023
release/2.2 https://github.com/ROCm/pytorch/blob/a3208baad2f2d537f10362fe9ca30f60ff5aea21/test/test_cuda.py#L2047

[release/2.3] skip test_autocast_rnn

---

related_commits

Update related_commits for release/2.4 to use torchvision with numpy<2 requirements from ROCm/vision repo
Uses https://github.com/ROCm/vision/commit/fab848869c0f88802297bad43c0ad80f33ecabb4

[release/2.4] update torchvision in related_commits

---

test/test_cuda.py
torch/testing/_internal/common_utils.py

Add skipIfRocmArch() decorator and skip test_autocast_rnn only for MI300

[release2.3] skip test_autocast_rnn  only on MI300 

---

.ci/docker/common/install_aotriton.sh

Fixes sha256sum mismatch issues eg. http://rocm-ci.amd.com/blue/organizations/jenkins/framework-pytorch-2.4-ci_rel-6.2/detail/framework-pytorch-2.4-ci_rel-6.2/4/pipeline
Tested via: http://rocm-ci.amd.com/job/framework-pytorch-2.4-ci_rel-6.2/6/

[release/2.4] Use shared library tarball for aotriton for CI base docker image

---

.ci/docker/common/cache_vision_models.sh
.ci/docker/requirements-ci.txt

This PR pins sympy==1.12.1 in the .ci/docker/requirements-ci.txt file Also it skips pytorch-nightly installation in docker images
Installation of pytorch-nightly is needed to prefetch mobilenet_v2 avd v3 models for some tests.
Came from
https://github.com/ROCm/pytorch/commit/85bd6bc0105162293fa0bbfb7b661f85ec67f85a Models are downloaded on first use to the folder /root/.cache/torch/hub But pytorch-nightly installation also overrides
.ci/docker/requirements-ci.txt settings and upgrades some of python packages (sympy from 1.12.0 to 1.13.0) which causes several 'dynamic_shapes' tests to fail
Skip prefetching models affects these tests without any errors (but **internet access required**):
- python test/mobile/model_test/gen_test_model.py mobilenet_v2
- python …

[rocm6.3_internal_testing] pin sympy==1.12.1 and skip pytorch-nightly installstion

---

test/inductor/test_pad_mm.py

skip test_pad_mm_dyn_[mnk] on MI300
https://ontrack-internal.amd.com/browse/SWDEV-462203
tests can be enabled after closing https://github.com/ROCm/frameworks-internal/issues/8803

[release/2.3] skip inductor/test_pad_mm.py::test_pad_mm_dyn_* on MI300

---

aten/src/ATen/native/cuda/thread_constants.h

This patch increments the amount of work assigned per thread in vectorized_elementwise_kernel, thus reducing the number of threadblocks needed to execute the loops while increasing register usage.

Improve vectorized_elementwise_kernel by increasing vector length.

---

test/test_nn.py

New tests introduced for testing NHWC and NCHW batchnorm on MIOpen : 
- test_batchnorm_nhwc_miopen_cuda_float32
- test_batchnorm_nchw_miopen_cuda_float32
This test verifies weight and bias gradients, running_mean and running_var
We can add other dtypes later
How to run:
`MIOPEN_ENABLE_LOGGING_CMD=1 python -u test/test_nn.py -v -k test_batchnorm_nhwc_miopen_cuda_float32`
There is a difference in running_variance for NHWC batchnorm fp32 between MIOpen and native 
```
MIOPEN_ENABLE_LOGGING_CMD=1 python -u test/test_nn.py -v -k test_batchnorm_nhwc_miopen_cuda_float32
...
self.assertEqual(mod.running_var, ref_mod.running_var)
AssertionError: Tensor-likes are not close!
Mismatched elements: 8 / 8 (100.0%)
Greatest absolute difference: 0.05455732345581055 at index (5,) (up to 1e-05 allowed) …
```

Add test_batchnorm_nhwc_miopen_cuda_float32

---

test/run_test.py

Skip test_typing to avoid `Error importing plugin "numpy.typing.mypy_plugin": No module named 'numpy.typing.mypy_plugin'`
It happens because we have numpy==1.20.3 in some of our images. But `mypy` can be used only witn numpy>=1.21
We have numpy==1.20.3 in our images with python3.9
Will check numpy version in run_tests.py and add test_typing to ROCM_BLOCKLIST if numpy version less then 1.21
Fix https://github.com/ROCm/frameworks-internal/issues/8497

[release/2.4] skip test_typing if numpy less then 1.21

---

torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp

Decreasing the watchdog timer sleep time to 100 ms from 1000ms. 
Refer commit c16e6e4 in PT upstream. [ProcessGroup] Make watchdog check work queue more frequently
Today watchdog's sleep interval is 1s. That's a bit long compared to modern GPU link's (or network link's) speed.
Take DDP and Ampere for example:
DDP's bucket size = 25 MB
Ampere's NVLink speed = 250 GB/s
25 MB / 250 GB/s = 100 ms.
So we are updating the interval to 100 ms.
Update:
25 MB / 250 GB/s = 0.1 ms
But let's see how it goes so far between making the checking more aggressive.
Fixes https://ontrack-internal.amd.com/browse/SWDEV-476819

[release/2.1]: Fix distributed tests

---

torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp

Decreasing the watchdog timer sleep time to 100 ms from 1000ms. 
Refer commit c16e6e4cf70a0fd7a73f9c4df38761778efc543e in PT upstream. [ProcessGroup] Make watchdog check work queue more frequently
Today watchdog's sleep interval is 1s. That's a bit long compared to modern GPU link's (or network link's) speed.
Take DDP and Ampere for example:
DDP's bucket size = 25 MB
Ampere's NVLink speed = 250 GB/s
25 MB / 250 GB/s = 100 ms.
So we are updating the interval to 100 ms.
Update:
25 MB / 250 GB/s = 0.1 ms
But let's see how it goes so far between making the checking more aggressive.
Fixes https://ontrack-internal.amd.com/browse/SWDEV-467357

[release/2.2]: Fix distributed tests

---

test/run_test.py

Warning!!! 
run_test.py failed if nothing to do in release/2.2 (`./run_test.py -i test_typing` if test_typing is banned)
```
+ f"to prioritize ({(num_tests_found / len(tests)):.2%}%)"
ZeroDivisionError: division by zero
```
Skip test_typing to avoid `Error importing plugin
"numpy.typing.mypy_plugin": No module named 'numpy.typing.mypy_plugin'` It happens because we have numpy==1.20.3 in some of our images. But `mypy` can be used only witn numpy>=1.21
We have numpy==1.20.3 in our images with python3.9
Will check numpy version in run_tests.py and add test_typing to ROCM_BLOCKLIST if numpy version less then 1.21
Fix https://github.com/ROCm/frameworks-internal/issues/8497
(cherry picked from commit 3b54c4556df4682e4a7b71d1006c2984071ea212)

[release/2.2] skip test_typing if numpy less then 1.21 (#1563)

---

test/run_test.py

Skip test_typing to avoid `Error importing plugin
"numpy.typing.mypy_plugin": No module named 'numpy.typing.mypy_plugin'` It happens because we have numpy==1.20.3 in some of our images. But `mypy` can be used only witn numpy>=1.21
We have numpy==1.20.3 in our images with python3.9
Will check numpy version in run_tests.py and add test_typing to ROCM_BLOCKLIST if numpy version less then 1.21
Fix https://github.com/ROCm/frameworks-internal/issues/8497
(cherry picked from commit 3b54c4556df4682e4a7b71d1006c2984071ea212)

[release/2.3] skip test_typing if numpy less then 1.21 (#1563)

---

aten/src/ATen/native/transformers/cuda/sdp_utils.cpp
test/test_transformers.py

[ROCm] Prevent accidental enablement of efficient attention. (#133331)
Currently Efficient attention and Flash attention share the same set of GPU kernels on ROCM and have common limitations on head sizes.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/133331
Approved by: https://github.com/malfet, https://github.com/jithunnair-amd
(cherry picked from commit 46ecc673ae048cc31a919a1d01dfdff51e3d2869)
Fixes https://github.com/pytorch/pytorch/issues/132004

[ROCm] Prevent accidental enablement of efficient attention. (#134531)

---

test/distributed/test_c10d_gloo.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-469119
@pruthvistony this test pass on MI200 and fail on MI300 in several branches. 
Do I need to introduce skipIfRocmArch decorator?

skip test_reduce_stress_cuda on ROCm as it fails on MI300

---

.ci/docker/requirements-ci.txt

Sync requirements-ci.txt optree versions with requirements.txt for py3.12

---

.ci/docker/requirements-ci.txt

Revert PR https://github.com/ROCm/pytorch/pull/1579
remove `tlparse` from requirements-ci.txt
need to use `.ci/pytorch/test.sh` to install requirements before testing
https://ontrack-internal.amd.com/browse/SWDEV-480494

[rocm6.2_internal_testing] revert add tlparse in requirements-ci.txt

---

aten/src/ATen/native/cuda/Reduce.cuh

Follow-up to https://github.com/pytorch/pytorch/pull/135397.
AMD gpus perform better with fewer thread blocks.
So increase the min_values_per_thread as well. 
This helped improved [CvT](https://github.com/facebookresearch/FAMBench/tree/main/benchmarks/cvt) benchmark performance on MI300X
Co-author: @carlobertolli

[ROCm] torch.sum optimization by increasing min_values_per_thread

---

.automation_scripts/run_pytorch_unit_tests.py

Removed args inside function

---

.automation_scripts/run_pytorch_unit_tests.py

Fixes SWDEV-487907. Verified throwing exception for distributed is working correctly on single gpu with command: python .automation_scripts/run_pytorch_unit_tests.py --priority_test

QA script - Added multi gpu check with priority_tests

---

test/run_test.py

Fixes error introduced by https://github.com/ROCm/pytorch/commit/995edef06cb695bbf52f6ebd3e2eca7efe2101a8 when running unit tests using `run_test.py`:
```
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
```
Refer solution suggested in: https://github.com/pytorch/pytorch/issues/37377#issuecomment-629610327
Need to cherry-pick this change to release/2.3 and release/2.4 branches as well.

SWDEV-486396 : Import numpy after torch

---

.ci/docker/requirements-ci.txt

this PR add tlparse==0.3.5 into requirementss-ci.txt
fix dynamo/test_structured_trace.py
Error message: FileNotFoundError: [Errno 2] No such file or directory: 'tlparse'
Fixes: https://ontrack-internal.amd.com/browse/SWDEV-480494 (cherry picked from commit 70fdaed1278eb4be695f2f583796454d592d1dbc)

[release/2.3] add tlparse into requirements-ci.txt

---

.ci/docker/requirements-ci.txt

this PR add tlparse==0.3.7 into requirementss-ci.txt
fix dynamo/test_structured_trace.py
Error message: FileNotFoundError: [Errno 2] No such file or directory: 'tlparse'
Fixes: https://ontrack-internal.amd.com/browse/SWDEV-480494 (cherry picked from commit 70fdaed1278eb4be695f2f583796454d592d1dbc)

[release/2.4] add tlparse into requirements-ci.txt (#1608)

---

.ci/docker/requirements-ci.txt

this PR add tlparse==0.3.25 into requirementss-ci.txt
fix dynamo/test_structured_trace.py
Error message: FileNotFoundError: [Errno 2] No such file or directory: 'tlparse'
Fixes: https://ontrack-internal.amd.com/browse/SWDEV-480494 (cherry picked from commit 70fdaed1278eb4be695f2f583796454d592d1dbc)

[rocm6.3_internal_testing] add tlparse into requirements-ci.txt

---

aten/src/ATen/native/transformers/cuda/sdp_utils.cpp
aten/src/ATen/native/transformers/hip/flash_attn/flash_api.hip

All Philox Tensors must be on the device, and `check_mem_efficient_hardware_support` should return true if test passed.
Fixes #SWDEV-487470

SWDEV-487470 : Move philox arguments to GPU and properly enable ME attention

---

torch/testing/_internal/distributed/nn/api/remote_module_test.py

[rocm6.3_internal_testing] Fixed error string assertion in test_invalid_devices

---

aten/src/ATen/native/cuda/Sort.cu

Improve performance for smaller shapes that use block radix sort by decreasing the item_per_thread to 8.
This will increase the thread block size leading to higher occupancy.
Co-author: Shetty, Sudarshanram (AMD)

[ROCm] Use IPT=8 for block radix sort

---

caffe2/CMakeLists.txt
test/distributed/test_c10d_nccl.py
test/distributed/test_symmetric_memory.py
torch/csrc/distributed/c10d/CUDASymmetricMemory.cu
torch/csrc/distributed/c10d/CUDASymmetricMemory.hpp
torch/csrc/distributed/c10d/intra_node_comm.cpp

With the latest IFU into rocm6.3_internal_testing branch, we pulled in SymmetricMemory code which is being used by intra node communication also. SymmetricMemory also introduces a new memory allocator called CUDASymmetricMemoryAllocator. intra_node_comm is now using this new allocator to manage memory.

[ROCm] Add support for SymmetricMemory

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/DistributionTemplates.h
aten/src/ATen/native/cuda/MemoryAccess.cuh
aten/src/ATen/native/cuda/thread_constants.h

enabling use of vector length 8 on AMD GPUs for vectorized elementwise kernel and minor parameter tuning to improve performance
Co-author: @akadutta

 Enabling vector length 8 for vectorized elementwise kernel

---

test/test_nn.py

`self.assertTrue(torch.equal(out1, out2))` assumes a compete match
But we have a slight difference (~1e-7) with fp32 NHWC and NCHW batchnorm output
`self.assertEqual(out1, out2)` allows for tolerance

change torch.equal() to self.assetrEqual() while comparing NHWC and NCHW batchnorm output

---

test/distributed/test_c10d_nccl.py
test/functorch/test_ops.py

Fixes the following issue by changing atol from 5e-4 to 1e-3
__ TestOperatorsCUDA.test_vmapvjpvjp_linalg_householder_product_cuda_float32 ___
File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 921, in test_wrapper
return test(*args, **kwargs)
File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_cuda.py", line 194, in wrapped
return f(*args, **kwargs)
File "/var/lib/jenkins/pytorch/test/functorch/test_ops.py", line 891, in test_vmapvjpvjp
self.assertEqual(loop_out, batched_out)
File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3635, in assertEqual
raise error_metas.pop()[0].to_error(
AssertionError: …

Release/2.3 linalg householder product change atol to 1e-03

---

test/distributed/test_c10d_gloo.py

I am skipping test_gather_stress_cuda for rocm6.2 due to getting time out.

skip all *_stress_cuda UT

---

aten/src/ATen/native/transformers/cuda/attention.cu
aten/src/ATen/native/transformers/cuda/attention_backward.cu
aten/src/ATen/native/transformers/cuda/sdp_utils.cpp
aten/src/ATen/native/transformers/hip/flash_attn/flash_api.hip

The previous backport of AOTriton 0.7 integration from PyTorch upstream is incomplete. This one includes the remaining part.
Fixes #SWDEV-490104

Fix SWDEV-490104

---

aten/src/ATen/native/cuda/Sort.cu

Improve performance for smaller shapes that use block radix sort by decreasing the item_per_thread to 8.
This will increase the thread block size leading to higher occupancy.
Co-author: @amd-sushetty

[ROCm] Use IPT=8 for block radix sort (#1619)

---

test/inductor/test_kernel_benchmark.py

These unit tests fail on NAVI nodes:
inductor/test_kernel_benchmark.py::TestKernelBenchmark::test_slice_mm_bandwidth_computation - RuntimeError: Expected to find "0.022 GB " but did not find it (test is good on MI300)
inductor/test_kernel_benchmark.py::TestKernelBenchmark::test_split_scan - RuntimeError: Expected to find "0.400 GB " but did not find it (test fails on MI300 as well)

Fixed unit test failures in test_kernel_benchmark.py

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/DistributionTemplates.h
aten/src/ATen/native/cuda/MemoryAccess.cuh
aten/src/ATen/native/cuda/thread_constants.h

enabling use of vector length 8 on AMD GPUs for vectorized elementwise kernel and minor parameter tuning to improve performance
Co-author: @akadutta

[ROCm] Enabling vector length 8 for vectorized elementwise kernel

---

torch/cuda/__init__.py

Port the patch (only torch/cuda/__init__.py) from Pytorch upstream e1b426b345c6fe7a349c41b88a44398cda6773c9
[ROCm] CUDA_VISIBLE_DEVICES fallback option for device_count
Fixes https://ontrack-internal.amd.com/browse/SWDEV-491112

[ROCm]: Fix torch cuda device to consider CUDA_VISIBLE_DEVICES

---

test/dynamo/test_activation_checkpointing.py
torch/testing/_internal/common_utils.py

Flash attention not available OOB on Navi. Skipping UT which requires flash attention

[SWDEV-480138] [SWDEV-460957] Skip flash attention inductor test on Navi

---

test/inductor/test_cpp_wrapper_hipify.py
torch/_inductor/codegen/codegen_device_driver.py

[rocm6.3_internal_testing] [NO CP] Added ignore to cuda driver check code to disable warnings for ROCm builds

---

aten/src/ATen/native/cuda/Reduce.cuh
aten/src/ATen/native/cuda/ReduceSumProdKernel.cu

Remove input_vec_size constexpr and make input vectorization dependent on vt0 template parameter, as it happens for non input vectorized, but unrolled, thread reduce implementation.

[ROCM] Enable *_load_dwordx4 ISA for BFloat16 and Half.

---

test/inductor/test_pad_mm.py
torch/_inductor/config.py
torch/_inductor/fx_passes/pad_mm.py

This fixes:
test_pad_mm_dyn_m
test_pad_mm_dyn_n
test_pad_mm_dyn_k

[release/2.3] Added force_shape_pad option to avoid compute bound optimizations for test_pad_mm.py

---

aten/src/ATen/native/cuda/Indexing.cu

On ROCm, hipification converts std::min to ::min, but ::min is not returning the right result. This impacts index_add_ operation on a large tensor, we end up picking the large values instead of max supported block size (128). This leads to GPU accessing memory out of bounds.
While we wait for ::min to be fixed, we can use < operator to compare instead of relying on ::min.
Example Code w/ failure:
```
D=6144
hidden_states = torch.zeros([16384, 6144],           device="cuda:0", dtype=torch.bfloat16)
index         = torch.randint(0, 16384, (1, 32, 16384), device="cuda:0", dtype=torch.int64)
output        = torch.empty([1, 32, 16384, 6144],    device="cuda:0", dtype=torch.bfloat16)
hidden_states.index_add_(0, index.view(-1), output.view(-1, D))
```
``` …
```

[rocm6.3_internal_testing][ROCm] Fix largeIndexBlockSize

---

torch/utils/module_tracker.py

When running an FSDP model with FlopCounterMode, we are experiencing a memory leak. It is coming from ModuleTracker class. Even though ModuleTracker class is keeping weakrefrences of the operators, the tensors/operators are not being freed after the backward pass. To force free these tensors/operators after forward pass, I explicitly added garbage collection in the post forward hook.
(cherry picked from commit 63dc40dedf6cfc815fe97057f02bc2cefb069a5c)

[release/2.4] ModuleTracker: Add explicit garbage collection

---

aten/src/ATen/native/cuda/DistributionTemplates.h
aten/src/ATen/native/cuda/thread_constants.h

thread work size = 8 performs better than 16 for 1D tensors. 
For 2D tensors, both 8 and 16 gives similar performance.

[ROCm] Set thread work size to 8 for elementwise kernels

---

test/inductor/test_pad_mm.py

This affects:
-test_cat_pad_mm_dyn_m
-test_pad_bmm_dyn_b
-test_pad_bmm_dyn_bm
-test_pad_bmm_dyn_k
-test_pad_mm_dyn_k
-test_pad_mm_dyn_n

[release/2.4] Enabled forced padding for multiple tests in test_pad_mm

---

test/inductor/test_kernel_benchmark.py

The test fails to use triton gemms because is_big_gpu returns true and thus fails to produce benchmarkable kernel.

[release/2.4] Skipped test_slice_mm_bandwidth_computation on big gpus

---

test/inductor/test_kernel_benchmark.py
test/inductor/test_pad_mm.py
torch/testing/_internal/common_utils.py

The tests fail because is_big_gpu for navi returns false and GEMMs backend fails to produce any kernels going back to ATen. The tests fail to check to valid metadate for kernels and thus fail. Decided to skip the for navi currently and not rely on is_big_gpu check.

[release/2.4] Skipped test_slice_mm_bandwidth_computation and test_pad_addmm_dyn_mn on navi

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/Dropout.cu
aten/src/ATen/native/cuda/MemoryAccess.cuh

Enable *_load_dwordx4 ISA for BFloat16 and Half by using vector size of 8
Co-author: @akadutta

[ROCm] Enable vector size for 8 for half precision types in elementwise kernels

---

aten/src/ATen/cuda/tunable/GemmCommon.h

Fixes #139116.  Also fixes other unreported issues with torch.bmm due to incorrect size calculations. Pull Request resolved: https://github.com/pytorch/pytorch/pull/139137 Approved by: https://github.com/yoyoyocmu

[rocm6.3] TunableOp use dense size calculations as minimum sizes (#139137)

---

torch/cuda/__init__.py

Fixes 491578
makes test_clock_speed and test_power_draw subtests in test_cuda PASS

Fix 491578 issue - socket_power metric AMDSMI and clockrate function using correct dictionary key

---

aten/src/ATen/native/cuda/int4mm.cu
test/test_linalg.py
torch/csrc/jit/codegen/fuser/codegen.cpp
torch/csrc/jit/codegen/fuser/cuda/resource_strings.h
torch/csrc/jit/tensorexpr/cuda_codegen.cpp
torch/testing/_internal/common_cuda.py
torch/utils/hipify/cuda_to_hip_mappings.py

- Add AMD support for int4 kernel
- Only supports CDNA2 and CDNA3 gpus for now
- Uses `mfma_f32_16x16x16bf16` instruction for matrix multiply
- Uses `v_and_or_b32` instruction and `__hfma2` instrinsic for unpacking bf16 values
- Enable hipify for `__nv_bfloat16` and `__nv_bfloat162` data types
- Enable int4 unit tests for CDNA2 and CDNA3 AMD gpus
- Fix torchscript issues due to hipify for `__nv_bfloat16` type
- TorchScript has its own implementation for bfloat16 type
- Implemented in `__nv_bloat16` structure at [resource_strings.h](https://github.com/pytorch/pytorch/blob/main/torch/csrc/jit/codegen/fuser/cuda/resource_strings.h)
- So, we shouldn't hipify any reference of `__nv_bfloat16` in the torchscript implementation
- Hence moved the `__nv_bfloat16` direct references in `codegen.cpp` …

[ROCm] Add int4 support (#129710)

---

aten/src/ATen/native/cuda/KernelUtils.cuh

MI300 adds HW support for packed bfloat16 and fp16. Enable via existing fastSpecializedAtomicAdd.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/135770
Approved by: https://github.com/xw285cornell, https://github.com/jianyuh

[ROCm] fastSpecializedAtomicAdd for MI300 (#135770)

---

test/test_linalg.py

Allow 3 or more digits for hipBLASLt version check in TunableOp test. Needed due to upcoming ROCm 6.3 release.
Fixes [SWDEV-493195](https://ontrack-internal.amd.com/browse/SWDEV-493195)
Same as [PR#139811](https://github.com/pytorch/pytorch/pull/139811)

[ROCM] Fix hipBLASLt version check in TunableOp test

---

test/test_linalg.py

Allow 3 or more digits for hipBLASLt version check in TunableOp test. Needed due to upcoming ROCm 6.3 release.
Fixes
[SWDEV-493195](https://ontrack-internal.amd.com/browse/SWDEV-493195)
Same as [PR#139811](https://github.com/pytorch/pytorch/pull/139811)

[release/2.5] [ROCM] Fix hipBLASLt version check in TunableOp test (#1678)

---

torch/utils/module_tracker.py

When porting https://github.com/ROCm/pytorch/pull/1660 onto release/2.4 branch, there were merge conflicts which I didn't handle correctly. Fixing by removing the extra line brought in

[release/2.4][SWDEV-496633] Fix bad merge

---

torch/_C/__init__.pyi.in
torch/_inductor/codegen/codegen_device_driver.py
torch/csrc/cuda/Module.cpp

Added warp size to device properties, removed 64 warpsize hardcode in codegen

[release/2.4] [NO CP] Warp size fix for navi arch

---

torch/_inductor/codecache.py

PR for reference: https://github.com/pytorch/pytorch/pull/131791

[release/2.4] [NO CP] Added missing library paths for aot_mode

---

.ci/docker/common/install_miopen.sh
.ci/docker/common/install_triton.sh

This resolves a maintenance burden of always needing to add a new conditional clause for newer ROCm versions. Now it assumes there's no need to rebuild MIOpen, unless a condition exists for that specific ROCm version. If we need to build a branch, we will add a clause for that ROCm version.
Fixes failures such as: 
http://rocm-ci.amd.com/view/Release-6.3/job/framework-pytorch-ci_rel-6.3/11

[release/2.5] Do not build MIOpen by default

---

aten/src/ATen/native/transformers/hip/flash_attn/flash_api.hip
test/inductor/test_fused_attention.py
test/inductor/test_graph_transform_observer.py
test/inductor/test_torchinductor.py
torch/testing/_internal/common_methods_invocations.py

The logsumexp tensor was considered for internal use only but apparently exposed to unit tests and inductors.
The stream should be selected after picking the current device. Otherwise the code is checking the default device's architecture.
Fixes #131316 #137414
Pull Request resolved: https://github.com/pytorch/pytorch/pull/137717
Approved by: https://github.com/drisspg
Co-authored-by: Jack Taylor <108682042+jataylo@users.noreply.github.com>
(cherry picked from commit 770fcaf2ab5424642eb3f65a7ab2bbe99a47342a)

[SWDEV-495116] Fix the Rank of logsumexp Tensor and mGPU support. (#137717)

---

test/inductor/test_torchinductor.py
torch/testing/_internal/common_utils.py

Relates to https://github.com/ROCm/pytorch/pull/1679 and https://github.com/ROCm/pytorch/pull/1697

[rocm6.3_internal_testing] Skipped some inductor tests for no hipcc rocm environments

---

test/inductor/test_torchinductor.py
torch/testing/_internal/common_utils.py

Skipped some tests for wheels builds with a check for ROCM_HOME.

[release/2.4] Skipped some inductor tests for no hipcc rocm environments

---

torch/testing/_internal/distributed/distributed_test.py

Fixes #SWDEV-493250
Solving these issues in 5 different tests.
| 1 | test_ddp_apply_optim_in_backward  distributed/test_distributed_spawn 1/7 failed!   | FAILED [9.4180s] distributed/test_distributed_spawn.py::TestDistBackendWithSpawn::test_ddp_apply_optim_in_backward - RuntimeError: Process 2 exited with error code 10 and exception:  AssertionError: Tensor-likes are not close!  Mismatched elements: 1 / 9 (11.1%) Greatest absolute difference: 0.02197265625 at index (1, 0) (up to 1e-05 allowed) Greatest relative difference: 3.0710627925145673e-06 at index (1, 0) (up to 1.3e-06 allowed) Params not equal at iteration 7 …

[Release/2.4] Fix 493250 - Fix distributed unit tests that fail on 4 GPU NAVI machine with python12, pytorch release2.4

---

aten/src/ATen/cuda/tunable/GemmCommon.h
test/test_linalg.py

Fixes https://github.com/pytorch/pytorch/issues/140278
Based on PR:
https://github.com/pytorch/pytorch/pull/140673
Note in test/linalg.py that I had to include Case #4 from upstream in addition to Case #5 to resolve the merge conflict from the cherry-pick of the upstream commit. 
Verified manually that test_bmm_tunableop_rocm UT passes.
cc: @jeffdaily

[UPCP][release/2.4] TunableOp fix for batched MM with views.

---

test/inductor/test_kernel_benchmark.py

Skipping tests in inductor/test_kernel_benchmark.py for release/2.4:
- test_mm_triton_kernel_benchmark

[release/2.4] Skip failed unit tests in inductor/test_kernel_benchmark

---

test/inductor/test_binary_folding.py

skipping tests in inductor/test_binary_folding.py for release/2.4:
- test_conv_bn_folding_cuda

[NOCP][release/2.4] Skip failed unit tests in inductor/test_binary_folding

---

test/functorch/test_ops.py

skipping tests in functorch/test_ops.py for release/2.4:
- test_vmapvjpvjp_linalg_householder_product_cuda_float32
- test_vmap_autograd_grad_nn_functional_scaled_dot_product_attention_cuda_float32

[release/2.4] Skip failed unit tests in functorch/test_ops.py

---

test/test_expanded_weights.py

skipping tests in test_expanded_weights.py for release/2.4:
- test_instance_norm_model_num_dim_3_cuda

[NOCP][release/2.4] Skip failed unit tests in test_expanded_weights.py

---

test/test_torch.py

skip for test_index_add_correctness on ROCm

[NOCP][release/2.4] skip failed tests in test_torch.py

---

torch/testing/_internal/distributed/distributed_test.py

Fixes #[SWDEV-493250](https://ontrack-internal.amd.com/browse/SWDEV-493250)
Added @with_nccl_blocking_wait decorator to tests test_barrier_full_group_cuda and test_barrier_group_cuda so that the CPU blocks until the GPU streams are synchronized in the barrier call and the assertion check is made after the GPU streams are synchronized. barrier() call is made to block CPU in the upstream after release2.4, but this functionality is not present in the upstream release2.4. This decorator helps to make barrier() block the CPU and pass these unit tests for rocm/pytorch release2.4.

[Release/2..4] Fix 493250 tests - make barrier() block cpu and pass two unit tests

---

aten/src/ATen/cuda/CublasHandlePool.cpp
docs/source/notes/hip.rst
test/test_cuda.py
torch/utils/hipify/cuda_to_hip_mappings.py

Fixes #138532.
This brings hipblas behavior in line with cublas behavior with respect to setting the workspace to an allocation from the caching allocator as well as the env var HIPBLAS_WORKSPACE_CONFIG.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/138791
Approved by: https://github.com/naromero77amd, https://github.com/eqy, https://github.com/malfet

[release/2.4] set hipblas workspace (#138791)

---

aten/src/ATen/cuda/CublasHandlePool.cpp
docs/source/notes/hip.rst
test/test_cuda.py
torch/utils/hipify/cuda_to_hip_mappings.py

Fixes #138532.
This brings hipblas behavior in line with cublas behavior with respect to setting the workspace to an allocation from the caching allocator as well as the env var HIPBLAS_WORKSPACE_CONFIG.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/138791
Approved by: https://github.com/naromero77amd, https://github.com/eqy, https://github.com/malfet

[release/2.5] set hipblas workspace (#138791)

---

test/distributed/test_c10d_gloo.py

skipping tests in distributed/test_c10d_gloo.py for release/2.4:
- test_allgather_stress_cuda
- test_allreduce_stress_cuda
- test_broadcast_stress_cuda
- test_gather_stress_cuda
- test_reduce_stress_cuda
- test_scatter_stress_cuda

[NOCP][release/2.4] Skip stress related distributed tests

---

test/nn/test_convolution.py
test/nn/test_embedding.py
test/nn/test_multihead_attention.py

skipping tests in nn/test_convolution.py for release/2.4:
- test_conv3d_64bit_indexing_cuda
skipping tests in nn/test_multihead_attention.py for release/2.4:
- test_multihead_self_attn_two_masks_fast_path_cuda

[NOCP][release/2.4] Skip failed unit tests in nn/test_convolution and nn/test_multihead_attention

---

test/test_ops.py

skipping tests in test_ops.py for release/2.4:
- <s>test_complex_half_reference_testing_fft_hfft_cuda_complex32</s> - PASSED
- <s>test_complex_half_reference_testing_mH_cuda_complex32</s> - PASSED
- <s>test_complex_half_reference_testing_nn_functional_conv3d_cuda_complex32</s> - PASSED
- <s>test_complex_half_reference_testing_nn_functional_conv_transpose2d_cuda_complex32</s> - PASSED
- test_operator_nn_functional_scaled_dot_product_attention_cuda_float32
- <s>test_conj_view_slice_cuda_complex64</s> - PASSED
- <s>test_neg_conj_view_kron_cuda_complex128</s> - PASSED
- <s>test_neg_view_stft_cuda_float64</s> - PASSED

[release/2.4] skip failed tests in test_ops.py

---

test/test_nn.py

skipping tests in test_nn.py for release/2.4:
- test_rnn_check_device
- test_transformerdecoder
- test_InstanceNorm3d_general_cuda
- <s>test_cross_entropy_large_tensor_reduction_none_cuda</s>

[release/2.4] skip failed tests in test_nn.py

---

test/test_matmul_cuda.py

skipping tests in test_matmul_cuda.py for release/2.4:
- test_float8_basics_cuda
- test_scaled_mm_vs_emulated_bfloat16_cuda
- test_scaled_mm_vs_emulated_float16_cuda
- test_scaled_mm_vs_emulated_float32_cuda

[release/2.4] skip failed tests in test_matmul_cuda.py

---

test/test_jit_fuser_te.py

skipping tests for release/2.4:
- test_jit_fuser_te.py::ЕestTEFuserDynamic::test_concat_invariant
- test_jit_fuser_te.py::TestTEFuserDynamic::test_sum_dim
- test_jit_fuser_te.py::TestTEFuserDynamic::test_sum_keepdim_cast

[release/2.4] skip failed tests in test_jit_fuser_te.py

---

test/jit/test_freezing.py

skipping test in  test_jit.py (jit/test_freezing.py) for release/2.4:
- test_linear_bn_folding_autocast_scenario_cuda

[release/2.4] skip failed tests in test_jit.py (jit/test_freezing.py)

---

test/inductor/test_benchmark_fusion.py

Choosing incorrect GEMM backend here for Triton because is_big_gpu doesn't have enough SMs for navi arch.

[release/2.4] Skipped equivalent_template_code in test_benchmark_fusion

---

aten/src/ATen/cuda/CUDABlas.cpp
aten/src/ATen/cuda/CUDABlas.h
aten/src/ATen/cuda/tunable/TunableGemm.h
aten/src/ATen/native/cuda/Blas.cpp

amax was removed from _scaled_mm by #128683. Remove it from the internal at::cuda::blas::scaled_gemm, as well.  This allows hipBLASLt to find additional solutions rather than forcing amax to be used and then discarding the result. Pull Request resolved: https://github.com/pytorch/pytorch/pull/135421 Approved by: https://github.com/drisspg, https://github.com/eqy

[release/2.5] remove amax_ptr from scaled_gemm (#135421)

---

test/inductor/test_pad_mm.py

test_cat_pad_mm_dyn_m is failing on navi due to is_big_gpu check returning false
test_pad_mm_dyn_m needs to be forced to pad

[release/2.4] Fixed two tests failing in test_pad_mm

---

aten/src/ATen/native/cuda/KernelUtils.cuh

MI300 adds HW support for packed bfloat16 and fp16. Enable via existing fastSpecializedAtomicAdd.
Helps with improving [torch.scatter_add_ performance](https://ontrack-internal.amd.com/browse/SWDEV-497013), among others.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/135770

[release/2.5] [ROCm] fastSpecializedAtomicAdd for MI300 (#135770)

---

test/test_ops.py

Skipping tests in test_ops.py for release/2.4:
- test_noncontiguous_samples_svd_lowrank_cuda_complex64

[release/2.4] Skip failed unit tests in test_ops.py

---

test/distributed/fsdp/test_fsdp_hybrid_shard.py

Skipping tests in distributed/fsdp/test_fsdp_hybrid_shard.py for release/2.4:
- test_fsdp_hybrid_shard_basic_setup

[NOCP][release/2.4] Skip failed unit tests in distributed/fsdp/test_fsdp_hybrid_shard

---

test/distributed/_composable/fully_shard/test_fully_shard_compile.py

Skipping tests in distributed/_composable/fully_shard/test_fully_shard_compile.py for release/2.4:
- test_compile

[NOCP][release/2.4] Skip failed unit tests in distributed/_composable/fully_shard/test_fully_shard_compile

---

test/distributed/test_c10d_nccl.py

Skipping tests in distributed/test_c10d_nccl.py for release/2.4:
- test_timeout_dumps_timing_enabled_False

[NOCP][release/2.4] Skip failed unit tests in distributed/test_c10d_nccl

---

test/distributed/fsdp/test_fsdp_sharded_grad_scaler.py

Skipping tests in distributed/fsdp/test_fsdp_sharded_grad_scaler.py for release/2.4:
- test_sharded_grad_scaler_found_inf

[NOCP][release/2.4] Skip failed unit tests in distributed/fsdp/test_fsdp_sharded_grad_scaler.py

---

test/distributed/_composable/fsdp/test_fully_shard_training.py

skipping tests in distributed/_composable/fsdp/test_fully_shard_training.py for release/2.4:
- test_gradient_accumulation

[NOCP][release/2.4] Skip failed unit tests in test_fully_shard_training.py

---

aten/src/ATen/native/Normalization.cpp
aten/src/ATen/native/miopen/BatchNorm_miopen.cpp

This PR enables:
* using MIOpen OCL_mix backend for bf16 batchnorm with fp32 weights (using torch autocast). This was required and tested for customer workload using NCHW (which is the only memory_layout enabled).
* logging for MIOpen batchnorm using `PYTORCH_MIOPEN_EXTRA_LOGGING` env var.
TODO in separate PR: Need to implement PyTorch unit tests for this bf16/fp16 inputs + fp32 weights case.

[release/2.3] Enable bf16 with fp32 weights for MIOpen batchnorm

---

aten/src/ATen/native/Normalization.cpp
aten/src/ATen/native/miopen/BatchNorm_miopen.cpp

This PR enables:
* using MIOpen OCL_mix backend for bf16 batchnorm with fp32 weights (using torch autocast). This was required and tested for customer workload using NCHW (which is the only memory_layout enabled).
* logging for MIOpen batchnorm using `PYTORCH_MIOPEN_EXTRA_LOGGING` env var.
TODO in separate PR: Need to implement PyTorch unit tests for this bf16/fp16 inputs + fp32 weights case.

[release/2.5] Enable bf16 with fp32 weights for MIOpen batchnorm

---

test/inductor/test_benchmark_fusion.py
test/inductor/test_pad_mm.py

Only merge if https://github.com/ROCm/pytorch/pull/1753 is merged!

[rocm6.3_internal_testing] [NO CP] Removed test skips for navi caused by is_big_gpu check

---

test/inductor/test_group_batch_fusion.py

rocm6.2_internal_testing and upstream compare `counters["inductor"]["unbind_stack_aten_pass"]` with `2`
https://github.com/ROCm/pytorch/blob/89f9b8db7b67cab32eeb1a00494397505c51ef39/test/inductor/test_group_batch_fusion.py#L476

[release/2.4] fix test_pointwise_op_fusion_post_grad

---

aten/src/ATen/native/cuda/Copy.cu

Based out of this PR: 
https://github.com/pytorch/pytorch/pull/140261

Port Transpose copy optimization. 

---

aten/src/ATen/native/cuda/layer_norm_kernel.cu

It was raised that the backwards layer norm on AMD was slightly off the accuracy of the equivalent NVIDIA implementation.
On AMD we call into a helper kernel `cuLoadWriteStridedInputs` which processes strided input and accumulates the partial gradients into shared memory.
In this kernel (https://github.com/pytorch/pytorch/pull/87635) we truncated `mean` and `rstd` from T_ACC type to T which causes numerical issues in the warp buffers created in this kernel. This PR will use the correct accumulator type for mean and rstd.
Note: Only AMD call into this call stack for backwards layer norm, so this was not an issue for NV.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/140259
Approved by: https://github.com/jianyuh
(cherry picked from commit …

[release/2.3] [ROCm] Correct numerical issues in layer norm backwards kernel (#140259)

---

aten/src/ATen/native/cuda/layer_norm_kernel.cu

It was raised that the backwards layer norm on AMD was slightly off the accuracy of the equivalent NVIDIA implementation.
On AMD we call into a helper kernel `cuLoadWriteStridedInputs` which processes strided input and accumulates the partial gradients into shared memory.
In this kernel (https://github.com/pytorch/pytorch/pull/87635) we truncated `mean` and `rstd` from T_ACC type to T which causes numerical issues in the warp buffers created in this kernel. This PR will use the correct accumulator type for mean and rstd.
Note: Only AMD call into this call stack for backwards layer norm, so this was not an issue for NV.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/140259
Approved by: https://github.com/jianyuh
(cherry picked from commit …

[release/2.2] [ROCm] Correct numerical issues in layer norm backwards kernel (#140259)

---

aten/src/ATen/native/cuda/layer_norm_kernel.cu
cmake/Dependencies.cmake
setup.py

Replace (more) exact calculation with hardware approximation.
Benefits:
Reduced code size.
Improved performance for certain scenarios.
Experiments show low reduction in precision.
Experiments show no significant performance regressions.
bfloat16 as well as float16 related calculations may benefit largely from this change.
vectorized_layer_norm_kernel:
Gains performance esp. for the following tensor shapes.
Lower values for dim1 do not change performance significantly.
dim1 = 8k-65k may gain considerable performance, but decline gradually with size.
```
dim0    dim1
----    ----
1024	8192
1024	16384
1024	32768
1024	65536
1024	131072
1024	262144
1024	524288
```

[release/2.4] [ROCm][layer_norm] Use __builtin_amdgcn_rcpf(x) instead of 1.f/x

---

aten/src/ATen/native/cuda/layer_norm_kernel.cu
cmake/Dependencies.cmake
setup.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/1688

[AUTOGENERATED] [release/2.5] [ROCm][layer_norm] Use __builtin_amdgcn_rcpf(x) instead of 1.f/x

---

.ci/docker/common/install_miopen.sh

Issue origin: [SWDEV-500540](https://ontrack-internal.amd.com/browse/SWDEV-500540?focusedId=17699571&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17699571)
Fixes http://rocm-ci.amd.com/job/framework-pytorch-2.5-ci_rel-6.2/3/
With http://rocm-ci.amd.com/job/framework-pytorch-2.5-ci_rel-6.2/6/

[release/2.5] Remove sanitized rocm path in install_miopen.sh

---

torch/utils/cpp_extension.py

This PR is a release/2.5-based version of https://github.com/ROCm/pytorch/pull/1809
Copied description by @hj-wei from https://github.com/ROCm/pytorch/pull/1809
> Hi all, I manually generating nvcc to bypass NVIDIA component checks(Megatron-LM),
see https://github.com/NVIDIA/Megatron-LM/blob/2da43ef4c1b9e76f03b7567360cf7390e877f1b6/megatron/legacy/fused_kernels/__init__.py#L57
> but it can lead to incorrect CUDA_HOME configurations. This can cause initialization anomalies in downstream libraries like DeepSpeed

FEAT:at least one of ROCM_HOME or CUDA_HOME must be None.

---

torch/utils/cpp_extension.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/1814

[AUTOGENERATED] [release/2.4] FEAT:at least one of ROCM_HOME or CUDA_HOME must be None.

---

aten/src/ATen/native/transformers/cuda/sdp_utils.cpp
test/functorch/test_ops.py

Fixes [10211](https://github.com/ROCm/frameworks-internal/issues/10211) 
Deselecting the efficient attention backend for scaled dot product function for ROCm architecture when casual parameter is True.
Reference - https://github.com/ROCm/aotriton/issues/25 
We are aware of this issue but the precise ETA has not been determined at the moment due to various missing functionalities in AOTriton, (varlen, MQA, causal variants, etc.)

[Release/2.4] Fixes 10211 - Deselecting the efficient attention backend for scaled dot product function in ROCm

---

aten/src/ATen/native/transformers/cuda/sdp_utils.cpp

This is required by current AOTriton's backend.
Fixes NaN when calling SDPA ME backend with `q.dtype() != attn_mask.dtype()` when training llama2 using transformers+deepspeed+pytorch
Corresponding CUDA check: https://github.com/pytorch/pytorch/blob/708ce3c0082d670d9eaff84bc3c43cad4554a75d/aten/src/ATen/native/transformers/cuda/attention.cu#L1331-L1336

ROCm SDPA: Ensure attn_mask has the same dtype with q

---

aten/src/ATen/native/cuda/Copy.cu
aten/src/ATen/native/cuda/Reduce.cuh

- optimize copy transpose op:
-   fix cacheline miss in L2
-   performance 2x for large shapes lastdim % 64 != 0
-   reach 4TB/s for typical cases

Copy trans fixl2 miss

---

test/functorch/test_ops.py

remove `xfail` from `batch_norm_with_update` op in `test_grad` and `test_vmap_autograd_grad`
these tests are passed now
Fixes https://ontrack-internal.amd.com/browse/SWDEV-472564
cherry-picked from rocm6.3_internal_testing PR https://github.com/ROCm/pytorch/pull/1776

[rocm6.4_internal_testing] remove xfail from 'batch_norm_with_update'

---

torch/_meta_registrations.py

This PR adds a meta_registration for miopen_batch_norm to resolve this issue
Fixes: https://ontrack-internal.amd.com/browse/SWDEV-507115
```
NotImplementedError: aten::miopen_batch_norm: attempted to run this operator with Meta tensors, but there was no fake impl or Meta kernel registered.
```
cherry-picked from upstream https://github.com/pytorch/pytorch/commit/4e4182dbd0417a859919183df86f5d40cf0ce2e6

[release/2.5] Add miopen_batch_norm to meta_registrations

---

torch/_meta_registrations.py

This PR adds a meta_registration for miopen_batch_norm in release/2.4 to resolve this issue
```
NotImplementedError: aten::miopen_batch_norm: attempted to run this operator with Meta tensors, but there was no fake impl or Meta kernel registered.
```
cherry-picked from upstream https://github.com/pytorch/pytorch/commit/4e4182dbd0417a859919183df86f5d40cf0ce2e6
Co-authored-by: Jack Taylor <jack.taylor@amd.com>
(cherry picked from commit 0ca1e5ba8fdf9b03beec04918ef3394a6ef53936)

[release/2.4] Add miopen_batch_norm to meta_registrations

---

torch/_meta_registrations.py

This PR adds a meta_registration for miopen_batch_norm in rocm6.4_internal_testing to resolve this issue
```
NotImplementedError: aten::miopen_batch_norm: attempted to run this operator with Meta tensors, but there was no fake impl or Meta kernel registered.
```
cherry-picked from upstream https://github.com/pytorch/pytorch/commit/4e4182dbd0417a859919183df86f5d40cf0ce2e6
Co-authored-by: Jack Taylor <jack.taylor@amd.com>
(cherry picked from commit 0ca1e5ba8fdf9b03beec04918ef3394a6ef53936)

[rocm6.4_internal_testing] Add miopen_batch_norm to meta_registrations

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/Dropout.cu
aten/src/ATen/native/cuda/MemoryAccess.cuh

Cherry-pick of https://github.com/ROCm/pytorch/pull/1738

[AUTOGENERATED] [release/2.5] [ROCm] Enable vector size for 8 for half precision types in elementwise kernels

---

aten/src/ATen/Context.cpp
aten/src/ATen/cuda/CUDABlas.cpp
test/dynamo/test_misc.py
test/test_cuda.py
torch/utils/hipify/cuda_to_hip_mappings.py

Ported patch from https://patch-diff.githubusercontent.com/raw/pytorch/pytorch/pull/143549.patch Resolved conflict in aten/src/ATen/Context.cpp
file test/dynamo/test_graph_region_tracker.py skipped since not present in rel 2.5 branch

[release/2.5] [reland][AMD] Turn on TF32 for aten::mm

---

aten/src/ATen/native/Normalization.cpp
aten/src/ATen/native/miopen/BatchNorm_miopen.cpp

This PR enables:
* using MIOpen OCL_mix backend for bf16 batchnorm with fp32 weights (using torch autocast). This was required and tested for customer workload using NCHW (which is the only memory_layout enabled).
* logging for MIOpen batchnorm using `PYTORCH_MIOPEN_EXTRA_LOGGING` env var.
TODO in separate PR: Need to implement PyTorch unit tests for this bf16/fp16 inputs + fp32 weights case.
(cherry picked from commit abbfe770c8db8f48ae0a5abdc788ef6705818de3)

[release/2.4] Enable bf16 with fp32 weights for MIOpen batchnorm

---

aten/src/ATen/native/Normalization.cpp
aten/src/ATen/native/miopen/BatchNorm_miopen.cpp
test/test_nn.py

bf16/fp16 NHWC/NCHW mixed batchnorm merged
refactoring of miopen batchnorm tests:
- `test_batchnorm_nhwc_miopen` - removed
- `test_batchnorm_layout_*_mixed_*` - added to cover all batchnorm train configs
> - `test_batchnorm_layout_NCHW_mixed_True_bfloat16` - skipped due to MIOpen tolerance issue SWDEV-507600
- `test_batchnorm_nhwc_eval_*` - added to cover all NHWC batchnorm inference configs
> - test_batchnorm_nhwc_eval_mixed_False_float32 - skipped due to SolverNotFound SWDEV-509640
> - test_batchnorm_nhwc_eval_mixed_True_bfloat16  - skipped due to SolverNotFound SWDEV-509640
> - test_batchnorm_nhwc_eval_mixed_True_float16  - skipped due to SolverNotFound SWDEV-509640
```
python test_nn.py  -v -k test_batchnorm_layout
Running tests... …
```

[rocm6.4_internal_testing] merge miopen bf16/fp16 mixed batchnorm

---

aten/src/ATen/native/transformers/cuda/attention.cu
aten/src/ATen/native/transformers/cuda/attention_backward.cu
aten/src/ATen/native/transformers/cuda/sdp_utils.cpp
aten/src/ATen/native/transformers/hip/flash_attn/flash_api.hip
cmake/External/aotriton.cmake
setup.py
test/inductor/test_flex_attention.py
test/inductor/test_flex_decoding.py
test/test_native_mha.py
test/test_transformers.py
torch/testing/_internal/common_methods_invocations.py

This is backported from upstream PR #140172, #137443 and #139432.
Original commit message of #140172:
Notable new features for SDPA operators on AMD systems from AOTriton 0.8b:
1. Nestedtensor support;
2. MQA/GQA support;
3. Restore Efficient attention support for causal=True and seqlen_q != seqlen_k cases;
+ The kernel should use top-left alignment, bottom right alignment will be added later
4. Move gfx1100 (RX7900/W7800/W7900) out of experimental support status. However, users are strongly recommended to update to ROCM 6.2.4, notably for its firmware updates.
Related unit tests are enabled as well.
Notable related changes from AOTriton 0.8b:
1. AOTriton 0.8b moves the GPU kernel out of libaotriton.so to a separate directory `aotriton.images`;
2. LZMA replaces ZSTD as GPU kernel …

[release/2.5] Support head dimension 512 with AOTriton 0.8.1b

---

torch/utils/module_tracker.py

Thanks @drisspg and @albanD for finding the fix
**TEST PLAN**
```
import gc
import torch
import torch.nn as nn
from torch.utils.module_tracker import ModuleTracker
class MyModel(nn.Module):
def forward(self, x):
return x * x
print(f"torch=={torch.__version__}")
m = MyModel()
m.cuda()
m.to(torch.bfloat16)
mt = ModuleTracker()
for i in range(1000):
if i % 100 == 0:
gc.collect()
print("memory_allocated:", torch.cuda.memory_allocated())
x = torch.randn([128, 256], device="cuda", dtype=torch.bfloat16, requires_grad=True)
with mt:
m(x)
```
Pull Request resolved: https://github.com/pytorch/pytorch/pull/141960 Approved by: https://github.com/albanD
(cherry picked from commit 9125e9119cee131d7f839c105d79e8036b44e92b)

[release/2.5] Fix memory leak in `ModuleTracker` (#141960)

---

aten/src/ATen/native/cuda/Reduce.cuh
aten/src/ATen/native/cuda/ReduceSumProdKernel.cu

Cherry-pick of https://github.com/ROCm/pytorch/pull/1638

[AUTOGENERATED] [release/2.5] [ROCM] Enable *_load_dwordx4 ISA for BFloat16 and Half.

---

test/test_cuda.py

Navi passes condition `torch.cuda.get_device_capability() >= (9, 4)` and  uses `default_workspace_size=128MB`, but it required only for MI300
Fix condition to use `("gfx94" in gcn_arch)` instead of  `torch.cuda.get_device_properties()` to detect MI300
Fixes https://ontrack-internal.amd.com/browse/SWDEV-507235

[rocm6.4_internal_testing] fix test_cublas_workspace_explicit_allocation for navi

---

aten/src/ATen/native/Normalization.cpp

PR to disable BF16 batchnorm on ROCm less then 6.4
Fixes "Solver Not Found" https://ontrack-internal.amd.com/browse/SWDEV-502652

[release/2.4] disable BF16 batchnorm with MIOpen for ROCm less then 6.4

---

aten/src/ATen/cuda/CublasHandlePool.cpp
test/test_cuda.py

Navi passes condition `torch.cuda.get_device_capability() >= (9, 4)` and uses `default_workspace_size=128MB`, but it required only for MI300 
Fix condition to use `("gfx94" in gcn_arch)` instead of `torch.cuda.get_device_properties()` to detect MI300
(cherry picked from commit d4d0b070874ff4ef66cb8fab5a7165dc39d5fe00)

[release/2.5] fix test_cublas_workspace_explicit_allocation for navi

---

aten/src/ATen/cuda/CublasHandlePool.cpp
test/dynamo/test_activation_checkpointing.py
test/dynamo/test_misc.py
test/jit/test_freezing.py
test/nn/test_convolution.py
test/run_test.py
test/test_cuda.py
test/test_linalg.py
test/test_nn.py
test/test_ops.py
test/test_sparse_csr.py
torch/testing/_internal/common_utils.py

Several inductor test files are added to ROCM_BLOCKLIST on Navi4x
```python
if "gfx12" in gcn_arch:
NAVI_BLOCKLIST = [
"inductor/test_aot_inductor.py",
"inductor/test_compiled_optimizers.py",
"inductor/test_control_flow.py",
"inductor/test_cuda_cpp_wrapper.py",
"inductor/test_cuda_repro.py",
"inductor/test_multi_kernel.py",
"inductor/test_padding.py",
"inductor/test_pattern_matcher.py",
"inductor/test_torchinductor_codegen_dynamic_shapes.py",
"inductor/test_torchinductor_dynamic_shapes.py",
"inductor/test_torchinductor_opinfo.py",
"inductor/test_torchinductor.py",
"inductor/test_unbacked_symints.py",
]
ROCM_BLOCKLIST.extend(NAVI_BLOCKLIST)
```
Skipped several `test_ops.py` tests on Navi4 by exact name matchng (to avoid missing many tests) 
```python
if "gfx12" in gcn_arch:
navi_blocklist …
```

[release2.4] navi4x fixes

---

aten/src/ATen/native/ck/ck_layer_norm.hip

The tensors needs to be contiguous in the CK LayerNorm kernel.

make tensors contiguous in ck layernorm

---

aten/src/ATen/native/cuda/UpSampleNearest3d.cu
test/test_torch.py

Fixes #144855
Follows approach in https://github.com/pytorch/pytorch/pull/141923 to use int64 types to increase INT_MAX limits Pull Request resolved: https://github.com/pytorch/pytorch/pull/144865 Approved by: https://github.com/eqy
(cherry picked from commit 082fab0fc7e26bbe0957386308e285c404e80276)

[SWDEV-509031] [CP] [64-bit] Int64 casting for UpSampleNearest3D (#144865)

---

aten/src/ATen/cuda/jiterator.cu
aten/src/ATen/native/cuda/CUDAJitLoops.cuh
aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/Dropout.cu
aten/src/ATen/native/cuda/MemoryAccess.cuh
aten/src/ATen/native/cuda/jit_utils.cpp
aten/src/ATen/native/cuda/jit_utils.h

*  Make io_size calculation as minimum of size of input and output size, rather than the summation of all sizes
* for e.g, for torch.add() on half dtypes (bfloat16/float16), calc_io_size() returns 6 causing elems_per_thread to be 4
* But elems_per_thread = 8 works better on half datypes for AMD gpus
* Enable *_load_dwordx4 ISA for 16-bit and 8-bit dtypes on AMD gpus by using vector size of 8 and 16 respectively
Co-author: @akadutta
Pull Request resolved: https://github.com/pytorch/pytorch/pull/143269
Approved by: https://github.com/jeffdaily, https://github.com/pruthvistony

[ROCm] Improvements for vectorized elementwise kernels (#143269)

---

aten/src/ATen/native/cuda/CUDALoops.cuh

* Unroll loops manually to hide memory access latency
*  Strided access for coalesced memory acesses 
Co-authors: @akadutta @doru1004 @amd-hhashemi @carlobertolli

[ROCm] Improvements to non-vectorized elementwise kernels

---

test/dynamo/test_activation_checkpointing.py
torch/testing/_internal/common_utils.py

skip `dynamo/test_activation_checkpointing.py::ActivationCheckpointingViaTagsTests::test_pattern_matcher` on Navi in release/2.3
Fixes SWDEV-481719

[release/2.3] skip test_pattern_matcher on Navi

---

aten/src/ATen/native/transformers/cuda/sdp_utils.cpp
test/functorch/test_ops.py

Fixes https://github.com/ROCm/frameworks-internal/issues/10211
Reverting https://github.com/ROCm/pytorch/commit/3dff0be30b4a44b1eab95a951cf8c96780845ca0 as there were performance issues reported in https://ontrack-internal.amd.com/browse/SWDEV-508915
This PR solve it without any performance issue
Deselecting the efficient attention backend for scaled dot product function for ROCm architecture when casual parameter is True.
Reference - https://github.com/ROCm/aotriton/issues/25
We are aware of this issue but the precise ETA has not been determined at the moment due to various missing functionalities in AOTriton, (varlen, MQA, causal variants, etc.)

Fix 10211 without performance issue

---

test/test_linalg.py

TunableOp UT will fail because the regular expression in the test will not work for future versions of ROCm.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/146548

[rocm6.4_internal_testing] [ROCm][TunableOp] Future proof TunableOp unit test.

---

aten/src/ATen/cuda/tunable/Tunable.cpp

This is cherry-pick of an upstream PR that has been approved but is unmerged (due to CI delays). The PR did previously pass ROCm tests.
https://github.com/pytorch/pytorch/pull/146574
This PR is to fix UT breakage that has been reported internally and is considered high priority. When tunable.record_untuned_enable(False) is invoked, we flush the results of the untuned gemm file.
Offline tuning I/O currently doesn't have a set untuned results filename member function or untuned results write to file member function. When performing back-to-back unit tests, the same ofstream ends up getting reused between UTs. Due to the way the UT are executed, this can lead to unexpected failures.

[rocm6.4_internal_testing] [ROCm][TunableOp] Close offline tuning results file when offline tuning is disabled.

---

test/test_linalg.py

Note that I had to copy and paste this one line change because the file has changed so much that the cherry-pick command fails.
TunableOp UT will fail because the regular expression in the test will not work for future versions of ROCm.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/146548

[release/2.5] [ROCm][TunableOp] Future proof TunableOp unit test.

---

aten/src/ATen/native/cuda/Indexing.cu

cherry-pick of  https://github.com/pytorch/pytorch/pull/146448
Co-author: @amd-hhashemi

[ROCm] Indexing perf optimization via Unroll/WideFetch/IdxReuse/OneDupOpt

---

.github/scripts/build_triton_wheel.py
related_commits

Relates to:
Validation:
http://ml-ci-internal.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/519/

[Release/2.1] triton git commit

---

.github/scripts/build_triton_wheel.py

Relates to:
Validation:
http://ml-ci-internal.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/530/

[Release/2.5] triton git commit

---

test/inductor/test_aot_inductor.py
torch/testing/_internal/common_utils.py

The test fails with assertion error "Tensors are not close"
After testing I can confirm that this issue is caused by eager mode execution specific to navi32 during the test_sdpa_2 run. Made a cross reference between navi31, navi32 and mi300. AOTInductor results are all the exact same for all of the archs, only the eager mode fails here for navi32 with 1.5% difference in tensor values from the gpu run. I assume that this happens due to fp16-32-16 conversions in eager mode or missing some if-statements for navi32 specifically.
Simple reproducer to check the values for cpu/gpu/eager/aoti runs.
[gfx1101_test_sdpa_2_issue_reproducer.txt](https://github.com/user-attachments/files/18676367/gfx1101_test_sdpa_2_issue_reproducer.txt)

[rocm6.4_internal_testing] [NAVI32] Skipped sdpa_2 test in test_aot_inductor for Navi32

---

test/test_cuda.py
torch/cuda/__init__.py

Respect ROCR_VISIBLE_DEVICES on AMD GPU device discovery (#142292)
Reland of #140320 after failing test on trunk. Fixes potential environment clobbering in test, makes ROCr+HIP devices (if specified together) more robust to index errors.
Fixes #140318
Pull Request resolved: https://github.com/pytorch/pytorch/pull/142292
Approved by: https://github.com/jataylo, https://github.com/huydhn, https://github.com/jeffdaily
Co-authored-by: Jack Taylor <108682042+jataylo@users.noreply.github.com>
Co-authored-by: Jeff Daily <jeff.daily@amd.com>
(cherry picked from commit c0d710634fcce172490c3ace0de977829b38bc06)
Co-authored-by: Tal Ben-Nun <tbennun@users.noreply.github.com>
(cherry picked from commit 23e390c711670095a8a4a64cc01b0c86eb3af04e)

[release/2.5] [CP] Respect ROCR_VISIBLE_DEVICES on AMD GPU device discovery (#144026)

---

test/inductor/test_group_batch_fusion.py

Test failed only on Navi rocm6.3 release/2.4
test expects ["unbind_stack_aten_pass"] == 2 but got 1. Failed only on Navi rocm6.3 release/2.4
Fixes SWDEV-504963
Previous PR https://github.com/ROCm/pytorch/pull/1865 was closed beasuse it wlil break this test on MI

[release/2.4] skip test_pointwise_op_fusion_post_grad on Navi

---

cmake/Dependencies.cmake

Cherry-pick of https://github.com/ROCm/pytorch/pull/1921

[AUTOGENERATED] [rocm6.4_internal_testing] [ROCm] Fix for ld failed to convert GOTPCREL relocation in PyTorch build (#143986)

---

aten/src/ATen/native/cuda/Sort.cpp
torch/testing/_internal/common_methods_invocations.py

When converting rom uint8 to bool using `view` op, we get a bool that has 0 for false and a non-zero value for true. However, these kinds of bool have undefined behavior. We only read the last bit as 0 or 1 to convert to false or true.
In this fix, we convert bools to uint8, which will convert false to 0 and non-zero value to 1. Essentially, converting non-standard bool to a standard bool and fixing the sort op for non-standard bool.
(cherry picked from commit dda599d938c39f14dbd5416ce4e89a6dbcd6bc03)

[release/2.6] Fix sort for non-standard bool

---

aten/src/ATen/cuda/tunable/Tunable.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/1889

[AUTOGENERATED] [release/2.6] Cherry-pick PR-1889

---

test/inductor/test_flex_decoding.py

Fixes [SWDEV-480212](https://ontrack-internal.amd.com/browse/SWDEV-480212)
test/inductor/test_flex_decoding.py runs fine and re-enable test/inductor/test_flex_decoding.py::TestFlexDecoding::test_windowed_no_mask_vs_sdpa (verified this unit test runs fine on NAVI3x and MI300)

Updated test_flex_decoding.py

---

torch/testing/_internal/distributed/rpc/rpc_test.py

skip_if_rocm does not exist in torch/testing/_internal/common_distributed.py. Use skipIfRocm from torch/testing/_internal/common_utils.py instead.

Fixed rocm skip import issue

---

test/distributed/_tools/test_sac_ilp.py
test/distributed/fsdp/test_fsdp_sharded_grad_scaler.py
test/inductor/test_max_autotune.py
torch/testing/_internal/common_utils.py

This PR is to skip certain unit tests on NAVI only.
Fixes SWDEV-509011 - test_sac_ilp.py::TestSACILP::test_sac_ilp_case1
Fixes SWDEV-509311 - test_max_autotune.py::TestMaxAutotune::test_non_contiguous_input_addmm
Fixes SWDEV-510738 test_fsdp_sharded_grad_scaler.py::TestShardedGradScalerParityWithDDP::test_sharded_grad_scaler_found_inf

Skip certain unit tests on NAVI

---

aten/src/ATen/native/cuda/Indexing.cu

Cherry-pick of https://github.com/ROCm/pytorch/pull/1937 
The first 2 commits are already in 2.6 branch

[AUTOGENERATED] [release/2.6] [release/2.5][ROCm] Indexing backward kernel improvements from mainline (mutiple commits)

---

tools/autograd/derivatives.yaml

Pytorch called `grad.contiguous()` before `miopen_batch_norm_backward`. This led to redundant conversions from NHWC gradient to NCHW and back to NHWC.
Solution based on `cudnn_batch_norm_backward` description in the same `derivatives.yaml` file
Fixes SWDEV-520250
Before:
After:

[romc6.4_internal_testing] avoid redundant NHWC-NCHW-NHWC conversions for MiopenBatchNormBackward

---

.ci/docker/common/install_conda.sh

Fixes SWDEV-516667
* conda installs the same libgcc-ng package from "defaults" conda channel: `libgcc-ng pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1`
* However, at a later point, when we try to [install libstdcxx-ng 12.3.0 from conda-forge](https://github.com/ROCm/pytorch/blob/7cecbf6d33d6567b6ef3aab0b3d6bc5e63478e81/.ci/docker/common/install_conda.sh#L77), conda 24.7.1 updates the dependencies of that package, including libgcc-ng package to the following: 
libgcc-ng-14.2.0 | h69a702a_2 52 KB conda-forge
* On the contrary, conda 25.1.1 does *not* update any dependencies, and hence the same installation of libgcc-ng is present in DOCKER_F after this step.
* The older libgcc-ng from the "defaults" conda channel contains a problematic RPATH setting: 
0x000000000000000f (RPATH) Library …

[release/2.4] Newer conda versions require --update-deps to update dependencies such as libgcc-ng

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/Loops.cuh
aten/src/ATen/native/cuda/MemoryAccess.cuh

This patch includes changes from https://github.com/pytorch/pytorch/pull/147527 with an extension to support multiple input tensor types.

  Support heterogeneous tensor types for vectorized elementwise kernel.

---

.github/scripts/amd/package_triton_wheel.sh

libamd_comgr.so.2 is breaking rocm6.4 and newer. Breaking this build: http://rocm-ci.amd.com/job/pytorch2.4-manylinux-wheels_rel-6.4/14/
similar changes to https://github.com/ROCm/triton/pull/760
Validation
http://rocm-ci.amd.com/job/pytorch2.4-manylinux-wheels_rel-6.4/18/

[release/2.4] Update libamd_comgr.so.3 in triton wheel build

---

torch/utils/cpp_extension.py

I made improvements to the exising PR to that fixes CUDA to HIP flag conversion. 
* Log: We should log this behavior since this can break hipcc down the line for all we know
* Log: Make it transparent to user what hipify actions are doing so devs are not left in the dark. 
* Fix cases where it should not touch the `-I` flags or case where CUDA appear more than once by replacing only the first instance. 
* Fix case where `nvcc` key may not exist 
* Fix case where hipify should ignore flag values and only touch the flag itself
@naromero77amd 
cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang
Passes the following unit test
```py
import unittest
import sys
from unittest.mock import Mock
class TestHipifyCompileFlags(unittest.TestCase):
def …
```

reduce CUDA to HIP flag hipify breaking existing/valid flags

---

aten/src/ATen/Context.cpp

Add gfx110x and gfx120x to supported architectures for hipBLASLt so it does not fall back to rocBLAS

[release/2.5] Add gfx110x and gfx120x in supported archs for hipBLASLt

---

aten/src/ATen/native/cuda/Copy.cu

Similar to #110251 we're seeing cases where vectorization can benefit casts to fp16/bf16
Pull Request resolved: https://github.com/pytorch/pytorch/pull/137053
Approved by: https://github.com/drisspg

[CUDA][AMP] Speed up fp16/bf16 casts on H100+ (#137053)

---

test/test_nn.py

RNN dropout PR for upstream still in review pytorch/pytorch#144572
Fixes SWDEV-517343

[rocm6.4_internal_testing] temporary skip test_RNN_dropout_state on ROCm

---

test/inductor/test_group_batch_fusion.py
test/test_matmul_cuda.py

Adjust tolerance for fp16 on Navi (https://ontrack-internal.amd.com/browse/SWDEV-481719):
- test_matmul_cuda.py::TestMatmulCudaCUDA::test_cublas_addmm_size_10000_cuda_float16
Skip no Navi (https://ontrack-internal.amd.com/browse/SWDEV-520262):
- inductor/test_group_batch_fusion.py::TestGroupBatchFusion::test_pointwise_op_fusion_post_grad

[release/2.5] [Navi] fix test_cublas_addmm_size_10000_cuda_float16, skip test_pointwise_op_fusion_post_grad

---

.ci/docker/common/install_conda.sh

Cherry-pick of https://github.com/ROCm/pytorch/pull/1946

[AUTOGENERATED] [release/2.5] Newer conda versions require --update-deps to update dependencies such as libgcc-ng

---

.ci/docker/common/install_conda.sh

Cherry-pick of https://github.com/ROCm/pytorch/pull/1946

[AUTOGENERATED] [release/2.6] Newer conda versions require --update-deps to update dependencies such as libgcc-ng

---

torch/testing/_internal/common_cuda.py

Include gfx1100, and optionally enable gfx1201/gfx950 according to env var TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL
Fixes #SWDEV-515529

[ROCm] testing: enable MEFF/FA unittests for gfx1100

---

torch/utils/cpp_extension.py

Here are the following modifications made to cpp_extension.py-
1) Changed compiler flag to use --version.
2) Added a feature to convert alpha-numeric string to numeric string for the version string returned by compiler. This was the source of error as the parser was failing on parsing alpha-numeric version string.
Build with following pytorch extensions- Apex, TorchVision, TorchAudio & DeepSpeed.
Unit tested with following pytorch extensions- Apex, TorchVision.

Build Pytorch extensions with amdclang++

---

related_commits

Relates to https://github.com/ROCm/vision/pull/7
Cherry pick of this https://github.com/pytorch/vision/pull/8982
https://ontrack-internal.amd.com/browse/SWDEV-522276
Validation:http://rocm-ci.amd.com/job/pytorch2.4-manylinux-wheels_rel-6.4/23/

[Release/2.4] Update related_commits for vision

---

related_commits

Relates to https://github.com/ROCm/vision/pull/7
Cherry pick of this https://github.com/pytorch/vision/pull/8982
https://ontrack-internal.amd.com/browse/SWDEV-522276
Validation:http://rocm-ci.amd.com/job/pytorch2.5-manylinux-wheels_rel-6.4/35/

[Release/2.5] Update related_commits for vision

---

related_commits

Relates to https://github.com/ROCm/vision/pull/7
Cherry pick of this https://github.com/pytorch/vision/pull/8982
https://ontrack-internal.amd.com/browse/SWDEV-522276
Validation:
http://rocm-ci.amd.com/job/pytorch2.6-manylinux-wheels_rel-6.4-preview/9/

[Release/2.6] Update related_commits for vision

---

aten/src/ATen/native/cuda/Loss.cu

Mirroring https://github.com/pytorch/pytorch/pull/149548 for release/2.6

[release/2.6] [ROCm] NLLLoss (torch.nll_loss) Performance Tuning by Dynamically Selecting # of GPU threads #149548

---

aten/src/ATen/native/cuda/Loss.cu

Mirroring https://github.com/pytorch/pytorch/pull/149548 for release/2.5.

[release 2.5] [ROCm] NLLLoss (torch.nll_loss) Performance Tuning by Dynamically Selecting # of GPU threads #149548

---

test/test_nn.py

python failed for the entire `test_nn.py` file if `@skipIfRocm` comes first before `@unittest.skipIf` for test_RNN_dropout_state
This PR is to reordering decorators for test_RNN_dropout_state
Fixes this PR https://github.com/ROCm/pytorch/pull/1970 with wrong decorator sequence

[rocm6.4_internal_testing] reorder skip decorators for test_RNN_dropout_state

---

torch/testing/_internal/common_cuda.py

Ported from PR #1951
Note this does not check TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL since
the env var was not added to the SDPA adapter for AOTriton 0.8.2b.
Fixes #SWDEV-515529

[Release/2.6][ROCm] testing: enable MEFF/FA unittests for gfx1100

---

torch/csrc/cuda/CUDAPluggableAllocator.h

Altering the flag to use the correct streamType for CUDAPluggableAllocator. This is impacting Distributed Fused Adam in Rocm/APEX. 
See PR https://github.com/ROCm/apex/pull/184
Related Issue : https://ontrack-internal.amd.com/browse/SWDEV-519796

[ROCm6.4_internal_testing] Update CUDAPluggableAllocator.h

---

related_commits
torch/utils/cpp_extension.py

Update to torchvision branch https://github.com/ROCm/vision/tree/release/0.15
Validation:http://rocm-ci.amd.com/view/Release-6.4/job/pytorch2.0-manylinux-wheels_rel-6.4/32/

[release/2.0] Remove custom kwargs before calling BuildExtension.__init__(...)

---

related_commits
torch/utils/cpp_extension.py

Update to torchvision branch https://github.com/ROCm/vision/tree/release/0.18
Validation:http://rocm-ci.amd.com/view/Release-6.4/job/pytorch2.3-manylinux-wheels_rel-6.4/29/

[release/2.3]Remove custom kwargs before calling BuildExtension.__init__(...)

---

related_commits
torch/utils/cpp_extension.py

Update to torchvision branch https://github.com/ROCm/vision/tree/release/0.19
Validation:http://rocm-ci.amd.com/view/Release-6.4/job/pytorch2.4-manylinux-wheels_rel-6.4/33/

[release/2.4] Remove custom kwargs before calling BuildExtension.__init__(...)

---

torch/utils/cpp_extension.py

Validation:http://rocm-ci.amd.com/view/Release-6.4/job/pytorch2.5-manylinux-wheels_rel-6.4/45/

[release/2.5] Remove custom kwargs before calling BuildExtension.__init__(...)

---

torch/utils/cpp_extension.py

Validation:http://rocm-ci.amd.com/view/Release-6.4/job/pytorch2.6-manylinux-wheels_rel-6.4-preview/22/

[release/2.6] Remove custom kwargs before calling BuildExtension.__init__(...)

---

aten/src/ATen/native/cuda/CUDALoops.cuh

Seeing a memory fault issue while running some model workload.

[ROCm] Disable vectorization for heterogenous tensor types

---

related_commits

Instead of using build_wheel.sh we remove the file and build in the [else block](https://github.com/ROCm/rocAutomation/blob/82e21b6a617965341e8d4a1ea4194a363028dc05/pytorch/manylinux_rocm_wheels/build_torchvision_wheel_inside_docker.sh#L29) This way we are able to build successfully
fixes https://ontrack-internal.amd.com/browse/SWDEV-522993
Relates to  https://github.com/ROCm/vision/pull/8

[release/2.0] Update related_commits

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/MemoryAccess.cuh

This PR ports to release/2.5 the generalization of vectorized elementwise kernels for multiple heterogeneous tensor types. It's still missing the reverted threadblock mapping present in the original PR, which will come in a later PR.

Port https://github.com/pytorch/pytorch/pull/149738 to ROCm (part 1).

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/Loops.cuh
aten/src/ATen/native/cuda/MemoryAccess.cuh

* In-place vectorized elementwise operations are slower on MI300 with bigger vector size
* We support vector size upto 8

[ROCm] Set vector size to 4 for in-place vectorized elementwise operations for MI300

---

aten/src/ATen/native/cuda/Indexing.cu
test/test_indexing.py

Improve backwards indexing when stride is not one.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/147630

[ROCm] Improve backwards indexing when stride is not one (#147630)

---

aten/src/ATen/native/Normalization.cpp
aten/src/ATen/native/miopen/BatchNorm_miopen.cpp
test/test_nn.py
tools/autograd/derivatives.yaml

This PR enables NHWC batchnorm on MIOpen in release/2.6 branch
`ROCm version >= 6.5` and `PYTORCH_MIOPEN_SUGGEST_NHWC_BATCHNORM=1` environment variable required to enable nhwc batchnorm 
This PR branch for `release/2.6` was built and tested using docker image: `compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-dkms-no-npi-hipclang:15845_ubuntu22.04_py3.10_pytorch_rocm6.4_internal_testing_8190c80`. 
New batchnorm tests introduced:
train:
```
test_batchnorm_train_NCHW_vs_cpu_float32 (__main__.TestNN) ... ok (0.040s)
test_batchnorm_train_NCHW_vs_cpu_mixed_bfloat16 (__main__.TestNN) ... ok (0.007s)
test_batchnorm_train_NCHW_vs_cpu_mixed_float16 (__main__.TestNN) ... ok (0.005s)
test_batchnorm_train_NCHW_vs_native_float32 (__main__.TestNN) ... ok (0.089s) …
```

[release/2.6] enable NHWC batchnorm with MIOpen

---

.ci/docker/centos-rocm/Dockerfile
.ci/docker/common/install_conda.sh
.ci/docker/ubuntu-rocm/Dockerfile

* Using miniforge avoids rate limit errors when using miniconda installer and default conda package channel: `[2025-04-15T19:29:19.374Z] CondaHTTPError: HTTP 429 TERMS OF SERVICE RATE LIMIT EXCEEDED for url <https://repo.anaconda.com/pkgs/main/linux-64/repodata.json>`
* However, conda-forge channel brings in CMake 4.0 by default, which is not compatible with older PyTorch release branches. Hence, pin CMake to 3.x
* Also, miniforge installation of conda does *not* install sqlite conda package by default, hence explicitly install sqlite packages (needed in [install_rocm.sh](https://github.com/ROCm/pytorch/blob/use_miniforge_release_2.6/.ci/docker/common/install_rocm.sh#L60))
Validation: http://rocm-ci.amd.com/job/mainline-framework-pytorch-2.6-ub22-py3.10-ci/50/

[release/2.6] Use miniforge instead of miniconda; pin to CMake 3.x; install sqlite

---

aten/src/ATen/cuda/tunable/TunableOp.h

This PR corrects the behavior of the TunableOp warmup variables:
```
PYTORCH_TUNABLEOP_MAX_WARMUP_DURATION_MS
PYTORCH_TUNABLEOP_MAX_WARMUP_ITERATIONS
```
See the updated comments which describe how the environment variables are intended to work. Previously, if you only set one of the two environment variables the warmup iters would always be zero.
Manually tested the four possible combinations to make sure things still behavior as intended.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/147412
(cherry picked from commit 4b35139a462f1858cf5fe5346e16f7e1abede78d)

[release/2.4][ROCm][TunableOp] Fix TunableOp warmup environment variable. (#147412)

---

related_commits

Following changes are added : 
Building nccl_allocator only for pytorch 2.6 branch - https://github.com/ROCm/apex/commit/8ee83055447af32a5b5949fb3ff7a213391c9b91
Change the location of the fused_dense unit tests. -  https://github.com/ROCm/apex/commit/2550ea6ef334f1b1d83b6a64e183797455615776

[release/2.6] Update related_commits

---

related_commits

Apex changes 
Building nccl_allocator only for pytorch 2.6 branch -  https://github.com/ROCm/apex/commit/a34f5c396c93adf9e2844142ba1b6281540bec3a
Change the location of the fused_dense unit tests -  https://github.com/ROCm/apex/commit/b06b4c3f6cf85ef367ae1ae8dfbd18d2c35a789e
Include run_transformer UTs in the run_rocm.sh file -  https://github.com/ROCm/apex/commit/1c44f5d8b90fda3736e94b613e2fa7412eef51d5
Fix transformer unit tests -
https://github.com/ROCm/apex/commit/1667e85d0c3ee96ea3ee40cb48a7d159971c6851
Fixes https://github.com/ROCm/frameworks-internal/issues/11932 
Fixes https://github.com/ROCm/frameworks-internal/issues/11934

[rocm6.4_internal_testing] Update related_commits

---

test/inductor/test_fused_attention.py
test/inductor/test_torchinductor.py
torch/_inductor/fx_passes/fuse_attention.py
torch/_meta_registrations.py

Fixes a series of failing and skipped unit tests.
For nvidia hw, the longsumexp last dimension is required to be a multiple of 32.  This is not the case for rocm.
A related issue: https://github.com/pytorch/pytorch/issues/146848
The unit tests in question:
```bash
inductor.test_fused_attention	SDPAPatternRewriterCudaDynamicTests	test_sdpa_prev_13_cuda
inductor.test_fused_attention	SDPAPatternRewriterCudaDynamicTests	test_sdpa_prev_14_cuda
inductor.test_fused_attention	SDPAPatternRewriterCudaDynamicTests	test_sdpa_prev_15_cuda
inductor.test_fused_attention	SDPAPatternRewriterCudaDynamicTests	test_sdpa_rewriter_11_cuda
inductor.test_fused_attention	SDPAPatternRewriterCudaDynamicTests	test_sdpa_rewriter_14_cuda
inductor.test_fused_attention	SDPAPatternRewriterCudaDynamicTests …
```

[ROCm] Update meta_registration for efficient attention (#146979)

---

.ci/docker/common/install_conda.sh

https://ontrack-internal.amd.com/browse/SWDEV-528304
Build error in UB22.04 with release/2.4.
```
[2025-04-17T05:48:09.594Z] LibMambaUnsatisfiableError: Encountered problems while solving:
[2025-04-17T05:48:09.594Z]   - package numpy-1.21.2-py37h620df1f_0 requires python_abi 3.7 *_pypy37_pp73, but none of the providers can be installed
[2025-04-17T05:48:09.594Z] 
[2025-04-17T05:48:09.594Z] Could not solve for environment specs
[2025-04-17T05:48:09.594Z] The following packages are incompatible
[2025-04-17T05:48:09.594Z] ├─ numpy 1.21.2**  is installable with the potential options
[2025-04-17T05:48:09.594Z] │  ├─ numpy 1.21.2 would require
[2025-04-17T05:48:09.594Z] │  │  └─ python_abi 3.7 *_pypy37_pp73, which can be installed;
[2025-04-17T05:48:09.594Z] │  ├─ numpy 1.21.2 would require …
```

[release/2.4] Conditionalize versioning for conda

---

test/test_cuda.py
torch/testing/_internal/common_utils.py

Skip for some tests for wheels builds with a check for ROCM_HOME
- test_cuda.py::TestMemPool::test_mempool_with_allocator
Fixes SWDEV-529917
similar draft PR for release/2.5 https://github.com/ROCm/pytorch/pull/1697 
(partially cherry-picked from 1b312e4e739093af8db8b9e9b2fbbdb895e90bd6)

[release/2.5] [WHL] skip test if no hipcc

---

.gitmodules

change kineto repo to ROCm
Use kineto workaround for non-amd systems
(cherry picked from commit 402deb262174f83d414b66ce8f757a7289274b2c)

[rocm6.5_internal_testing] Update kineto rocprof commit (#2015)

---

test/inductor/test_loop_ordering.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-510660
This test can't function for ROCm because fp8 'mul_cuda' op is not supported in eager mode that is required here to check vs compiled results.

[rocm6.4_internal_testing] Skipped two tests with fp8 types in test_loop_ordering for ROCm

---

.ci/docker/centos-rocm/Dockerfile
.ci/docker/common/install_base.sh
.ci/docker/common/install_cache.sh
.ci/docker/common/install_conda.sh
.ci/docker/common/install_rocm.sh
.ci/docker/common/install_vision.sh

Validation: http://rocm-ci.amd.com/job/mainline-framework-pytorch-internal-ub22-py3.10-ci/212/

[release/2.7] Update CentOS dockerfile for CentOS Stream 9

---

test/inductor/test_kernel_benchmark.py

Fixes one part of https://ontrack-internal.amd.com/browse/SWDEV-480219?focusedId=18920795&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18920795
The test requires triton version 3.3+ and rocm6.4_internal_testing branch only has 3.2 version so it's not supported.
This needs to be cherry picked later ONLY in release/2.6

[rocm6.4_internal_testing] Skipped split_scan test in test_kernel_benchmark

---

test/inductor/test_loop_ordering.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2064

[AUTOGENERATED] [rocm6.5_internal_testing] Skipped two tests with fp8 types in test_loop_ordering for ROCm

---

test/inductor/test_loop_ordering.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2064

[AUTOGENERATED] [release/2.6] Skipped two tests with fp8 types in test_loop_ordering for ROCm

---

test/inductor/test_loop_ordering.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2064

[AUTOGENERATED] [release/2.7] Skipped two tests with fp8 types in test_loop_ordering for ROCm

---

test/functorch/test_ops.py

remove `xfail` from `batch_norm_with_update` op in `test_grad` and `test_vmap_autograd_grad`
these tests are passed since ROCm6.4
Fixes https://ontrack-internal.amd.com/browse/SWDEV-529820
(cherry picked from commit 99b075842070e2b73625440d8712b87e1833515c)

[release/2.6] remove xfail from 'batch_norm_with_update'

---

aten/src/ATen/cuda/tunable/GemmCommon.h

Omit the bias type argument for BLAS logging when there is a ScaledGEMM with no bias vector.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/149357
(cherry picked from commit dbea13ed45497ef954b7581b505a3dfc73c0d345)

[release/2.7][ROCm][TunableOp] Minor fix to BLAS logging for ScaledGEMM with no bias vector.

---

aten/src/ATen/cuda/tunable/GemmHipblaslt.h
aten/src/ATen/cuda/tunable/GemmRocblas.h
aten/src/ATen/cuda/tunable/TunableGemm.h
test/test_linalg.py
torch/cuda/tunable.py

TunableOp TF32 support enabled via two-cherry picks from upstream.
https://github.com/pytorch/pytorch/pull/145946
https://github.com/pytorch/pytorch/pull/149088

[release/2.7][ROCm][TunableOp] TunableOp TF32 support 

---

cmake/External/aotriton.cmake

This packages mixes the support of conventional architectures and gfx950, and also removes the "experimental" status of gfx950 for testing

Update to AOTriton 0.9.2b with gfx950 support package

---

aten/src/ATen/Context.cpp

hipBLASLt causes performance regression on gfx110x and gfx120x. This PR removes them from the list of supported architectures.

[release/2.5] Change gfx110x and gfx120x BLAS Preferred Backend to rocBLAS

---

cmake/External/aotriton.cmake

To resolve build issues introduced by https://github.com/ROCm/pytorch/pull/2074, since the actual url - `https://github.com/ROCm/aotriton/releases/download/0.9.2b/aotriton-0.9.2b_612896439f-manylinux_2_28_x86_64-rocm6.5-shared.tar.gz` -  doesn't match the expected value: `/ROCm/aotriton/releases/download/0.9.2b_612896439f/aotriton-0.9.2b_612896439f-manylinux_2_28_x86_64-rocm6.5-shared.tar.gz`
Fixes build breakages like: http://rocm-ci.amd.com/job/mainline-framework-pytorch-internal-ub22-py3.10-ci/215/
Validation: http://rocm-ci.amd.com/job/mainline-framework-pytorch-internal-ub22-py3.10-ci/217/

[DO NOT CHERRY-PICK] [rocm6.5_internal_testing] Introduce __AOTRITON_VER_WITH_COMMIT

---

test/inductor/test_aot_inductor.py
torch/testing/_internal/common_utils.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/1882 

[AUTOGENERATED] [release/2.6] [rocm6.4_internal_testing] [NAVI32] Skipped sdpa_2 test in test_aot_inductor for Navi32

---

test/inductor/test_aot_inductor.py
torch/testing/_internal/common_utils.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-522391
Accelerated SDPA is not supported on navi32
Needs to be cherry-picked in rocm6.4, rocm6.5 and release/2.7

[release/2.6] Skipped two sdpa tests in test_aot_inductor for Navi32

---

test/inductor/test_aot_inductor.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2093

[AUTOGENERATED] [release/2.7] [release/2.6] Skipped two sdpa tests in test_aot_inductor for Navi32

---

test/inductor/test_aot_inductor.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2093

[AUTOGENERATED] [rocm6.4_internal_testing] [release/2.6] Skipped two sdpa tests in test_aot_inductor for Navi32

---

test/distributed/tensor/parallel/test_micro_pipeline_tp.py
torch/testing/_internal/common_device_type.py

Created PR for fp8 fix on release/2.5 branch. The tests were failing in test/distributed/tensor/parallel/test_micro_pipeline_tp.py and are related to fp8 issue. The issue was reported in for Jira ticket- https://ontrack-internal.amd.com/browse/SWDEV-503871
Added fix for fp8 issue. Tested by running the test_micro_pipeline_tp.py tests and all test passed. Attached the screenshot displaying the results of the test.
Used this docker image for testing-
compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-rel-6.4:64_ubuntu22.04_py3.10_pytorch_release-2.5_fd9f71a

[release/2.5 ] Fix fp8 issue on release/2.5 branch for Jira ticket#503871

---

test/distributed/tensor/parallel/test_micro_pipeline_tp.py
torch/testing/_internal/common_device_type.py

In this PR, pf8 tests are enabled in test_micro_pipeline_tp.py for MI300. 
Tested on av_fp8_distributed_tensor_test_release2.6 branch by running distributed.tensor.parallel.test_micro_pipeline_tp UTs and all tests were passed. Attached screenshot of the test results.
This docker image was used for testing-
compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-dkms-no-npi-hipclang:15960_ubuntu24.04_py3.12_pytorch_release-2.6_cbd7bc9

[release/2.6] Enabled pf8 tests in test_micro_pipeline_tp.py for MI300

---

test/test_linalg.py
torch/cuda/tunable.py

The main purpose of this PR is to fix offline tuning for ScaledGEMM. The previous UT passed because it was not strict enough. Additionally:
- All the offline tuning tests now do a comparison with the online results to ensure that ParamSignature match.
- We raise an error if submatrices are encountered as this is only supported in online tuning mode.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/149677
(cherry picked from commit 01b1d1f91b9ee15051489da6d4e9377459ad692c)

[release/2.7][ROCm][TunableOp] Fix offline tuning for ScaledGEMM. (#149677)

---

cmake/External/aotriton.cmake

Also fixes the URL problem, where release page does not always match the version string in file name.

AOTriton: add 0.9.2b version built on ROCM 6.5, with gfx950 supported.

---

.ci/pytorch/common_utils.sh

Removing --no-deps and --no-index flags because the old setuptools was installing the requirements of the torch wheel along with those of the torchvision wheel when using the old setuptools version (<80.0.1) and in versions greater than setuptools 80.0.1, the new setuptools does not install the requirements of the torch wheel and torchvision wheel. Resolves 
https://ontrack-internal.amd.com/browse/SWDEV-531011
Validation:
http://rocm-ci.amd.com/job/framework-pytorch-2.6-ub22-py3.10-ci_rel-6.4-preview/60/

[release/2.6] Remove --no-index and --no-deps flags

---

test/inductor/test_aot_inductor.py
torch/testing/_internal/common_utils.py

It's an internal change, removes unnecessary arch mentions and generalizes conditions.
Needs to be cherry-picked into rocm6.5_internal_testing and release/2.7

[rocm6.4_internal_testing] Replaced ROCm specific skips to generalized conditions

---

cmake/External/ck_kernels.cmake

In this PR made changes to ck_kernels.cmake to use BUILD_BYPRODUCTS instead of INSTALL_BYPRODUCTS in ExternalProject_Add function. It's an attempt to check if it fixes CK library build issue with Jenkins.
Tested locally with manual pytorch installation and the build was successful.

Use BUILD_BYPRODUCTS instead of INSTALL_BYPRODUCTS in ExternalProject_Add

---

aten/src/ATen/Context.h

Only AMD Instinct GPUs prefer hipblaslt by default, but user can still override using env var.

[release/2.6] Change gfx110x BLAS preferred backend

---

test/inductor/test_decompose_mem_bound_mm.py
torch/testing/_internal/common_utils.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-506859
As discussed upping the tolerance level conditionalized for navi archs specifically.
Will need to be cherry picked into other branches.

[release/2.5] test_decompose_mem_bound_mm.py tolerance increase for navi3x

---

.ci/pytorch/common_utils.sh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2103

[AUTOGENERATED] [rocm6.5_internal_testing] Remove --no-index and --no-deps flags

---

.ci/pytorch/common_utils.sh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2103

[AUTOGENERATED] [rocm6.4_internal_testing] Remove --no-index and --no-deps flags

---

test/inductor/test_decompose_mem_bound_mm.py
torch/testing/_internal/common_utils.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2129

[AUTOGENERATED] [release/2.6] [release/2.5] test_decompose_mem_bound_mm.py tolerance increase for navi3x

---

related_commits

Update Related commits for apex 
upgrade matplotlib to resolve setuptools_scm error. - https://github.com/ROCm/apex/commit/86fff107d5e73043c75003c1530dbeabce8984fb
Update fused layer norm code from upstream apex repo - https://github.com/ROCm/apex/commit/d5956c435dd326fbab7240a00aaec3d8a94587b4
Fix unit tests for transformer, fused dense, mlp - https://github.com/ROCm/apex/commit/e5f4a5ec59578801aae9da7d2aa342ef1f4db7b0

[release/2.7] Update related_commits

---

related_commits

Update Related commits for apex 
upgrade matplotlib to resolve setuptools_scm error. - https://github.com/ROCm/apex/commit/6468501d7220acc1e840303f559aaac8e0527ce0 
Update fused layer norm code from upstream apex repo - https://github.com/ROCm/apex/commit/6729b2b4a66b4b9dcf3b4d62fcf4f7621a04381a
Fix unit tests for transformer, fused dense, mlp - https://github.com/ROCm/apex/commit/a31598cfa1f1d90137e1b5cdc3ab17cff2cafa30

[rocm6.5_internal_testing] Update related_commits

---

.github/scripts/amd/package_triton_wheel.sh

Fixes https://ontrack-internal.amd.com/browse/SWDEV-532730
These are failing 
Passed log:
http://rocm-ci.amd.com/job/mainline-pytorch2.6-manylinux-wheels-lw/104/ 
Failed log:
http://rocm-ci.amd.com/job/mainline-pytorch2.6-manylinux-wheels-lw/106/ 
Error Observed:
14:44:13  +++ find /opt/ -name libamdhip64.so.5
14:44:13  ++ [[ -z '' ]]
14:44:13  ++ echo 'Error: Library file libamdhip64.so.5 is not found.'
14:44:13  Error: Library file libamdhip64.so.5 is not found.
Was failing because rocm mainline became 7.0 and not 6.X. Updating the version check.

[release/2.6] Update ROCm version check for triton wheel build

---

.github/scripts/amd/package_triton_wheel.sh

http://rocm-ci.amd.com/blue/organizations/jenkins/rocm-pytorch-manylinux-wheel-builder/detail/rocm-pytorch-manylinux-wheel-builder/2009/pipeline/131/
`/pytorch/.github/scripts/amd/package_triton_wheel.sh: line 54: syntax error in conditional expression`
Validation: http://rocm-ci.amd.com/job/mainline-pytorch2.6-manylinux-wheels/79/

[release/2.6] Use -ge for numeric comparison

---

test/test_cuda.py

Updated default workspace size for gfx95 to fix test_cuda.py::TestCuda::test_cublas_workspace_explicit_allocation on MI350

Updated default workspace size for gfx95

---

test/distributed/test_c10d_nccl.py

When timing in enabled, ROCR runtime used to sleep for a small amount which ensured that the application saw the correct state. However, for perf reasons this sleep was removed and now the state is not guaranteed to be "started". That's why, I updated the test state check to be either "started" or "scheduled"
Fixes https://ontrack-internal.amd.com/browse/SWDEV-525883
Upstream PR: https://github.com/pytorch/pytorch/pull/153545

[release/2.5][ROCm] update state check for test_trace_while_active*

---

aten/src/ATen/native/cuda/Blas.cpp

A path, `gemm_and_bias` in `aten/src/ATen/native/cuda/Blas.cpp` which is controlled by the `DISABLE_ADDMM_CUDA_LT` env variable also uses hipBLASLt, which was not addressed in the previous PR https://github.com/ROCm/pytorch/pull/2053/files. 
This PR removes the gfx110x support for hipBLASLt in this path as well.

[release/2.6] Change gfx110x BLAS preferred backend (Take 2)

---

.github/scripts/amd/package_triton_wheel.sh
.github/scripts/amd/patch_triton_wheel.sh

Fixes http://rocm-ci.amd.com/job/mainline-pytorch2.6-manylinux-wheels-lw/
These are failing 
Passed log:
http://rocm-ci.amd.com/job/mainline-pytorch2.6-manylinux-wheels-lw/104/ 
Failed log:
http://rocm-ci.amd.com/job/mainline-pytorch2.6-manylinux-wheels-lw/106/ 
Error Observed:
14:44:13  +++ find /opt/ -name libamdhip64.so.5
14:44:13  ++ [[ -z '' ]]
14:44:13  ++ echo 'Error: Library file libamdhip64.so.5 is not found.'
14:44:13  Error: Library file libamdhip64.so.5 is not found.
Was failing because rocm mainline became 7.0 and not 6.X. Removing the version calls. 
Validation: http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder-lw/146/

[release/2.6] Make triton build ROCm version agnostic

---

.github/scripts/amd/package_triton_wheel.sh
.github/scripts/amd/patch_triton_wheel.sh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2130
Validation: http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder-lw/155/

[AUTOGENERATED] [release/2.7] Make triton build ROCm version agnostic

---

test/inductor/test_aot_inductor.py
torch/testing/_internal/common_utils.py

Fixes https://github.com/ROCm/frameworks-internal/issues/11952
This is @iupaikov-amd 's [PR](https://github.com/ROCm/pytorch/pull/2100/files) cherry-picked into 2.6.
For the full story why this is the best option at the moment, please follow into rabbit hole of that kanban issue.

[release/2.6] Skip sdpa UTs that use aotriton backend for Navi

---

aten/src/ATen/native/cuda/Blas.cpp

gfx110x experiences perf regression when using hipBLASLt. Defaulting to hipBLAS instead.

[rocm6.4_internal_testing] Default to hipBLAS on gfx110x

---

aten/src/ATen/native/cuda/Blas.cpp

gfx110x experiences perf regression when using hipBLASLt. Defaulting to hipBLAS instead.

[rocm6.5_internal_testing] Default to hipBLAS on gfx110x

---

aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/miopen/Handle.h
aten/src/ATen/miopen/Types.h

This PR exposes some MIOpen symbols, namely:
1. `miopenDataType_t getMiopenDataType(const at::Tensor& tensor)`
2. `miopenHandle_t getMiopenHandle()`
3. `class TensorDescriptor`
to enable adding extensions that make use of them.

[release/2.6] Exposing Some MIOpen Symbols

---

aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/miopen/Handle.h
aten/src/ATen/miopen/Types.h

Cherry-pick of https://github.com/ROCm/pytorch/pull/2176

[AUTOGENERATED] [release/2.7] [release/2.6] Exposing Some MIOpen Symbols

---

aten/src/ATen/native/Normalization.cpp

NHWC batchnorm enabled by default if ROCm>=7.0

[release/2.7] enable NHWC batchnorm by default on ROCm7.0+

---

aten/src/ATen/native/cuda/CUDALoops.cuh
aten/src/ATen/native/cuda/MemoryAccess.cuh

* Use non-temporal loads to improve the vectorized elementwise kernel performance on MI300
* Use thread_work_size of 8 or 16 for vectorized elementwise kernel
cherry-pick of https://github.com/pytorch/pytorch/pull/153634
Co-author: @amd-hhashemi

[ROCm] Improve vectorized elementwise kernel performance in MI300X

---

torch/testing/_internal/common_utils.py

Bug introduced by https://github.com/ROCm/pytorch/commit/03c7da05f61890bbf5ae41e23c8df6d5f6805bac

[release/2.7] import 'Dict' to fix common_utils.py

---

.ci/docker/common/install_rocm_magma.sh

- Changed to support new Hipblas 3.0.0 which is part of ROCm 7.0 is done.
CP of https://github.com/ROCm/pytorch/commit/ec0c539336f1afff62279d24a8c945dadd4890eb

[release/2.6] Move to magma public github repo

---

.ci/docker/common/install_rocm_magma.sh

- Changed to support new Hipblas 3.0.0 which is part of ROCm 7.0 is done.
CP of https://github.com/ROCm/pytorch/commit/ec0c539336f1afff62279d24a8c945dadd4890eb

[release/2.7] Move to magma public github repo

---

aten/src/ATen/native/Normalization.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2180

[AUTOGENERATED] [rocm6.5_internal_testing] enable NHWC batchnorm by default on ROCm7.0+

---

test/inductor/test_aot_inductor.py
torch/testing/_internal/common_utils.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2100 

[AUTOGENERATED] [rocm6.5_internal_testing] [rocm6.4_internal_testing] Replaced ROCm specific skips to generalized conditions

---

aten/src/ATen/Context.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2125

[AUTOGENERATED] [rocm6.5_internal_testing] [release/2.7] Prefer hipblaslt for gfx1200, gfx1201

---

torch/testing/_internal/distributed/distributed_test.py

Fixes #SWDEV-520036.
[Release/2.4] Fix 493250 - Fix distributed unit tests that fail on 4 GPU NAVI machine with python12, pytorch release2.4 (#1694)
Fixes #SWDEV-493250
Solving these issues in 5 different tests.
| 1 | test_ddp_apply_optim_in_backward
| 2 | test_barrier_full_group_cuda distributed/test_distributed_spawn | 3 | test_ddp_profiling_execution_trace
| 4 | test_gather_object_subgroup distributed/test_distributed_spawn | 5 | test_barrier_group_cuda distributed/test_distributed_spawn

Partial cherry-pick of distributed unit tests fix from Release/2.4.

---

test/inductor/test_cooperative_reductions.py

- Previously expected values were calculated on GPU using same dtype as result values
- Now expected values are calculated on CPU using Float32 dtype
- This fixes a test failure that was observed on Navi48 where difference between Eager mode (expected) and Inductor / Triton (result) did not meet the error tolerance when sum was evaluated on an array of Float16 values

[release/2.6] [SWDEV-529824] Fix Float16 CooperativeReduction Test Failure

---

aten/src/ATen/native/ConvUtils.h
aten/src/ATen/native/Convolution.cpp
aten/src/ATen/native/Normalization.cpp
aten/src/ATen/native/miopen/Conv_miopen.cpp

The same env vars PYTORCH_MIOPEN_SUGGEST_NHWC and PYTORCH_MIOPEN_SUGGEST_NHWC_BATCHNORM now also enable channels last 3d in addition to 2d.

[release/2.6] [SWDEV-535259] enable miopen channels last 3d for conv and batchnorm

---

aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/miopen/Handle.h
aten/src/ATen/miopen/Types.h

(Cherry-pick of https://github.com/pytorch/pytorch/pull/154545)
This PR exposes some MIOpen symbols, namely:
1. `miopenDataType_t getMiopenDataType(const at::Tensor& tensor)`
2. `miopenHandle_t getMiopenHandle()`
3. `class TensorDescriptor`
4. `class Descriptor`
5. `class FilterDescriptor`
6. `struct ConvolutionDescriptor`
7. `struct DropoutDescriptor`
8. `struct RNNDescriptor`
to enable adding extensions that make use of them.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/154545
Approved by: https://github.com/jeffdaily, https://github.com/Skylion007

[rocm6.4_internal_testing] Exposing Some MIOpen Symbols (#2176) (#154545)

---

aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/miopen/Handle.h
aten/src/ATen/miopen/Types.h

(Cherry-pick of https://github.com/pytorch/pytorch/pull/154545)
This PR exposes some MIOpen symbols, namely:
1. `miopenDataType_t getMiopenDataType(const at::Tensor& tensor)`
2. `miopenHandle_t getMiopenHandle()`
3. `class TensorDescriptor`
4. `class Descriptor`
5. `class FilterDescriptor`
6. `struct ConvolutionDescriptor`
7. `struct DropoutDescriptor`
8. `struct RNNDescriptor`
to enable adding extensions that make use of them.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/154545
Approved by: https://github.com/jeffdaily, https://github.com/Skylion007

[rocm6.5_internal_testing] Exposing Some MIOpen Symbols (#2176) (#154545)

---

aten/src/ATen/miopen/Handle.cpp

(This is a cherry-pick of https://github.com/pytorch/pytorch/pull/154549)
Get current device from Torch rather than HIP in MIOpen handle creation. The device may have already been set from torch side, otherwise device is set to 0 for handle.  Additional audits of cudnn vs miopen Handle.cpp file.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/154549
Approved by: https://github.com/jeffdaily, https://github.com/cyyever

[release/2.7] MIOpen: Get current device from Torch rather than HIP in handle creation (#154549)

---

aten/src/ATen/Context.h

Cherry-pick of https://github.com/ROCm/pytorch/pull/2053

[AUTOGENERATED] [release/2.5] Change gfx110x BLAS preferred backend

---

aten/src/ATen/miopen/Handle.cpp

(This is a cherry-pick of https://github.com/pytorch/pytorch/pull/154549)
Get current device from Torch rather than HIP in MIOpen handle creation. The device may have already been set from torch side, otherwise device is set to 0 for handle.  Additional audits of cudnn vs miopen Handle.cpp file.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/154549
Approved by: https://github.com/jeffdaily, https://github.com/cyyever

[rocm6.4_internal_testing] MIOpen: Get current device from Torch rather than HIP in handle creation (#154549)

---

aten/src/ATen/miopen/Handle.cpp

(This is a cherry-pick of https://github.com/pytorch/pytorch/pull/154549)
Get current device from Torch rather than HIP in MIOpen handle creation. The device may have already been set from torch side, otherwise device is set to 0 for handle.  Additional audits of cudnn vs miopen Handle.cpp file.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/154549
Approved by: https://github.com/jeffdaily, https://github.com/cyyever

[rocm6.5_internal_testing] MIOpen: Get current device from Torch rather than HIP in handle creation (#154549)

---

aten/src/ATen/native/cuda/SoftMax.cu
test/test_nn.py

This fixes OOB memory access for followng code
``` python
import torch
qk = torch.randn((9,1017), dtype=torch.float64, device='cuda')
smqk = torch.softmax(qk, dim=-1)
```
Upstream PR:
* https://github.com/pytorch/pytorch/pull/144009
* https://github.com/pytorch/pytorch/pull/154778

[Release/2.5] Backport softmax fixes from 2.8dev

---

test/inductor/test_cooperative_reductions.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2204

[AUTOGENERATED] [rocm6.5_internal_testing] [release/2.6] [SWDEV-529824] Fix Float16 CooperativeReduction Test Failure

---

.ci/docker/requirements-ci.txt
requirements.txt

Relates to: https://github.com/ROCm/builder/pull/82
Validation: http://rocm-ci.amd.com/job/mainline-pytorch_internal-manylinux-wheels/98/
Using `registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16180_ubuntu24.04_py3.12_pytorch_lw_rocm7.0_IT_upgrade_numpy_452f3df6`:
```
root@d92befdbb2a6:/# pip list | egrep "numpy|pandas"
numpy                   2.1.2
pandas                  2.2.3
root@d92befdbb2a6:/# python3
Python 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> import torch
>>> import numpy
>>> exit()
root@d92befdbb2a6:/data/pytorch-micro-benchmarking# HIP_VISIBLE_DEVICES=1 python3 micro_benchmarking_pytorch.py --network resnet50
INFO: running forward and backward …
```

[rocm7.0_internal_testing] upgrading numpy

---

test/distributed/test_symmetric_memory.py

This PR is created to skip test_multimem_all_gather test in test_symmetric_memory distributed tests in rocm6.5_internal_testing branch. The test_multimem_all_gather test is merged upstream and will be supported from release/2.7 onwards.

[ROCm][rocm6.5_internal_testing] skip test_multimem_all_gather test in test_symmetric_memory distributed tests

---

.ci/docker/requirements-ci.txt
requirements.txt

Relates to: https://github.com/ROCm/builder/pull/82
Validation: http://rocm-ci.amd.com/job/mainline-pytorch2.6-manylinux-wheels/120/
Ran import torch, import numpy, import pandas and the microbenchmark in image called 
_**registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16180_ubuntu24.04_py3.12_pytorch_lw_release2.6_upgrade_numpy_57e5941d**_
```
root@ubb4-rack-22:/var/lib/jenkins/pytorch-micro-benchmarking# pip list | grep pandas
pandas                  2.2.3
root@ubb4-rack-22:/var/lib/jenkins/pytorch-micro-benchmarking# pip list | grep numpy
numpy                   2.1.2
Python 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> import numpy
>>> import torch
>>> …
```

[release/2.6] Upgrade numpy

---

aten/src/ATen/cuda/tunable/GemmHipblaslt.h

Grepped for "HipBlasDataTypeFor" after changing definitions from HipBlasDataTypeFor to HipDataTypeFor and did not find any other instances of this besides the **GemmHipblaslt.h** file. 
Resolves https://ontrack-internal.amd.com/browse/SWDEV-536855
Build validated for 6.4:
http://rocm-ci.amd.com/view/Release-6.4/job/framework-pytorch-2.4-ub22-py3.10-ci_rel-6.4/61/
Build validated for mainline:
http://rocm-ci.amd.com/job/mainline-pytorch2.4-manylinux-wheels/248/

[release/2.4] hipDataType

---

test/test_cuda.py

This PR is to fix https://ontrack-internal.amd.com/browse/SWDEV-534855: test_cuda.py::TestCuda::test_hip_device_count fails on one gpu machine.
Needs to cherry-pick it to upstream as well once this PR is merged.

Added index 0 for ROCR_VISIBLE_DEVICES

---

.ci/docker/requirements-ci.txt
requirements.txt

Resolves errors such as:
```
00:12:44.248  #22 155.3 ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.61.0 Requires-Python >=3.10; 0.61.0rc1 Requires-Python >=3.10; 0.61.0rc2 Requires-Python >=3.10; 0.61.1rc1 Requires-Python >=3.10; 0.61.2 Requires-Python >=3.10; 3.3 Requires-Python >=3.10; 3.3rc0 Requires-Python >=3.10; 3.4 Requires-Python >=3.10; 3.4.1 Requires-Python >=3.10; 3.4.2 Requires-Python >=3.10; 3.4rc0 Requires-Python >=3.10; 3.5 Requires-Python >=3.11; 3.5rc0 Requires-Python >=3.11; 8.2.0 Requires-Python >=3.10; 8.2.1 Requires-Python >=3.10
00:12:44.248  #22 155.3 ERROR: Could not find a version that satisfies the requirement numba==0.61.2 (from versions: 0.1, 0.2, 0.3, …
```

[release/2.5] Use different package versions for py3.9

---

.ci/docker/requirements-ci.txt
requirements.txt

Resolves errors such as:
```
00:12:44.248  #22 155.3 ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.61.0 Requires-Python >=3.10; 0.61.0rc1 Requires-Python >=3.10; 0.61.0rc2 Requires-Python >=3.10; 0.61.1rc1 Requires-Python >=3.10; 0.61.2 Requires-Python >=3.10; 3.3 Requires-Python >=3.10; 3.3rc0 Requires-Python >=3.10; 3.4 Requires-Python >=3.10; 3.4.1 Requires-Python >=3.10; 3.4.2 Requires-Python >=3.10; 3.4rc0 Requires-Python >=3.10; 3.5 Requires-Python >=3.11; 3.5rc0 Requires-Python >=3.11; 8.2.0 Requires-Python >=3.10; 8.2.1 Requires-Python >=3.10
00:12:44.248  #22 155.3 ERROR: Could not find a version that satisfies the requirement numba==0.61.2 (from versions: 0.1, 0.2, 0.3, …
```

[release/2.7] Use different package versions for py3.9

---

.ci/docker/requirements-ci.txt
requirements.txt

Fixes SWDEV-536456
Fixes error post-https://github.com/ROCm/pytorch/pull/2256:
```
00:12:44.248  #22 155.3 ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.61.0 Requires-Python >=3.10; 0.61.0rc1 Requires-Python >=3.10; 0.61.0rc2 Requires-Python >=3.10; 0.61.1rc1 Requires-Python >=3.10; 0.61.2 Requires-Python >=3.10; 3.3 Requires-Python >=3.10; 3.3rc0 Requires-Python >=3.10; 3.4 Requires-Python >=3.10; 3.4.1 Requires-Python >=3.10; 3.4.2 Requires-Python >=3.10; 3.4rc0 Requires-Python >=3.10; 3.5 Requires-Python >=3.11; 3.5rc0 Requires-Python >=3.11; 8.2.0 Requires-Python >=3.10; 8.2.1 Requires-Python >=3.10
00:12:44.248  #22 155.3 ERROR: Could not find a version that satisfies the …
```

[rocm7.0_internal_testing] Use different package versions for py3.9

---

test/inductor/test_aot_inductor.py
test/inductor/test_torchinductor.py

Fixes this one: https://ontrack-internal.amd.com/browse/SWDEV-522391

[release/2.6] Update SDPA skip logic for Navi

---

test/dynamo/test_activation_checkpointing.py

Fixes test/dynamo/test_activation_checkpointing.py::test_pattern_matcher

Fixed typo

---

aten/src/ATen/native/cuda/Embedding.cu
aten/src/ATen/native/cuda/MultinomialKernel.cu
aten/src/ATen/native/cuda/TensorModeKernel.cu
aten/src/ATen/native/cuda/block_reduce.cuh

Fixes SWDEV-540240, SWDEV-540309, SWDEV-539989
```
#24 437.7   what():  HIP error: no ROCm-capable device is detected
#24 437.7 HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
#24 437.7 For debugging consider passing AMD_SERIALIZE_KERNEL=3
#24 437.7 Device-side assertions were explicitly omitted for this error check; the error probably arose while initializing the DSA handlers.
#24 437.7 Exception raised from c10_hip_check_implementation at /pytorch/c10/hip/HIPException.cpp:44 (most recent call first):
#24 437.7 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x88 (0x7f272de18738 in …
```

[rocm7.0_internal_testing] Prevent static initialization of at::cuda::warp_size()

---

torch/_inductor/scheduler.py

Ensure fused nodes that allocate buffers come before kernels that usethose buffers
In one example we observed:
- op8 creates buf10 which mutates buf8
- triton_poi_fused_index_put_lift_fresh_2 kernel tries to use buf8 and buf9
- op6_op7_op16 (fused node) creates buf8 and buf9
But the standard topological sort didn't ensure that the fused node creating buf8 and buf9 came before the kernel using them.
After this PR we will identify op8 performs a mutation on buf8, find the node that is responsible for creating the buffer (op6_op7_op16) and add an explicit dependency so now op8 depends on op6_op7_op16 and orders graph accordingly.
Note this issue is not seen in PT2.7, not clear as to why. We will hold back on upstreaming this until we observe a similar issue on nightly.
Reproducer code …

[SWDEV-531526] [SWDEV-527340] Allocation of buffers ordered before compute

---

test/distributed/pipelining/test_schedule_multiproc.py

Since, we no longer default to hipblaslt as the preferred backend for NAVI31, we are running into a very small accuracy issue. Updating this toleratnce for `test_schedule_with_native_zero_bubble_ScheduleClass1` in `test_schedule_multiproc.py`. From 2.6 onwards, this should be supported without any changes.

[release/2.5][SWDEV-506865] Update UT tolerance

---

aten/src/ATen/native/cuda/Embedding.cu
aten/src/ATen/native/cuda/MultinomialKernel.cu
aten/src/ATen/native/cuda/SoftMax.cu
aten/src/ATen/native/cuda/TensorModeKernel.cu
aten/src/ATen/native/cuda/TensorTopK.cu
aten/src/ATen/native/cuda/block_reduce.cuh
c10/macros/Macros.h
torch/csrc/distributed/c10d/CUDASymmetricMemory.cu
torch/csrc/distributed/c10d/CUDASymmetricMemoryOps.cu
torch/testing/_internal/common_cuda.py

Tested build locally using: `registry-sc-harbor.amd.com/rocm-ci-images/compute-rocm-dkms-component-staging-hip:2277-ubunt6u-22.04`

[release/2.5] Fix the Build and Enable FA/ME UT on gfx950 for ROCM >= 6.5

---

test/test_binary_ufuncs.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-537835
Related to https://github.com/ROCm/pytorch/commit/cf324795568f35f91a78fae9cb8f0efc8d955351
Not a Navi specific failure:
```
File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_device_type.py", line 1412, in only_fn
return fn(slf, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lib/jenkins/pytorch/test/test_binary_ufuncs.py", line 1671, in test_cuda_tensor_pow_scalar_tensor
self._test_pow(base, exp)
File "/var/lib/jenkins/pytorch/test/test_binary_ufuncs.py", line 1482, in _test_pow
self.assertEqual(actual, expected)
File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_utils.py", line 4052, in assertEqual
raise error_metas.pop()[0].to_error( …
```

[rocm7.0_internal_testing] Update test_binary_ufuncs.py

---

test/test_binary_ufuncs.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-538110
Related to https://github.com/ROCm/pytorch/commit/f30923074341adcb30ad44aa8862feeadbd70139
Not a Navi specific failure:
```
File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_device_type.py", line 1412, in only_fn
return fn(slf, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lib/jenkins/pytorch/test/test_binary_ufuncs.py", line 1671, in test_cuda_tensor_pow_scalar_tensor
self._test_pow(base, exp)
File "/var/lib/jenkins/pytorch/test/test_binary_ufuncs.py", line 1482, in _test_pow
self.assertEqual(actual, expected)
File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_utils.py", line 4052, in assertEqual
raise error_metas.pop()[0].to_error( …
```

[release/2.6] Numpy dtype change

---

.ci/docker/common/install_conda.sh
.ci/docker/requirements-ci.txt
related_commits
requirements.txt

Relates to: https://github.com/ROCm/builder/pull/82
Moves torchvision commit to unpin numpy dependency: https://github.com/ROCm/vision/commits/bbf1b41e2b24a46f69f3ceba7576d67d56459647
Validation: http://rocm-ci.amd.com/job/mainline-pytorch2.4-manylinux-wheels/272/
http://rocm-ci.amd.com/job/mainline-pytorch2.4-manylinux-wheels/282/
From: **registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16281_ubuntu22.04_py3.11_pytorch_lw_release2.4_upgrade_numpy_134c11da**

[release/2.4] upgrade numpy

---

test/distributed/test_c10d_gloo.py

In this PR, I have skipped *_stress_cuda UTs in test_c10d_gloo in release/2.5 branch. The tests are also skipped upstream.
The test was failing for Jira ticket- https://ontrack-internal.amd.com/browse/SWDEV-503871
Tested using docker image- compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-rel-6.4:114_ubuntu22.04_py3.10_pytorch_release-2.5_a1ad153

Skipped *_stress_cuda UTs in test_c10d_gloo in release/2.5 branch.

---

related_commits

1 ) [master] Added AITER as a submodule and use in fused_rope.py - https://github.com/ROCm/apex/commit/d533e3fb331be0ef496a7fc02a4e3ec611b78501
2) Not using warpSize as a constexpr in nhwc_batch_norm_kernel.h. replaces the variable use with the correct values based on the architecture we're running on. - https://github.com/ROCm/apex/commit/7f38d9d2991c3ee16912070ddfc84f841e939d20
3) [Replacing c10_warp_size with platform based warp_size values](https://github.com/ROCm/apex/commit/95c7ed20de6d512a7a1c6b1d6b72b2f20febf5de)
Fixes 
1) https://ontrack-internal.amd.com/browse/SWDEV-496182
2) https://ontrack-internal.amd.com/browse/SWDEV-541770
3) https://ontrack-internal.amd.com/browse/SWDEV-541725

[rocm7.0_internal_testing] Update related_commits

---

related_commits

updated apex commit 
[release/1.4.0] Do not use warpSize as a constexpr in nhwc_batch_norm_kernel.h - https://github.com/ROCm/apex/pull/229
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-541770

[release/2.4] Update related_commits

---

functorch/experimental/__init__.py
test/distributed/_composable/fsdp/test_fully_shard_mixed_precision.py
test/distributed/_composable/fsdp/test_fully_shard_training.py
test/distributed/elastic/test_control_plane.py
test/distributed/fsdp/test_fsdp_core.py
test/distributed/fsdp/test_fsdp_sharded_grad_scaler.py
test/distributed/optim/test_zero_redundancy_optimizer.py

I did a sweep of all the distributed failures on NAVI4x. On a high level, we were running into following issues:
- MEM_EFF_ATTENTION is not supported on NAVI4x for 2.5 causing tensors not alike issues
- Some UTs pass in future releases, skipped those
- Some had slight tolerance fixes as we use hipblas in this branch as compared to hipblaslt in future branches

[release/2.5][SWDEV-489778] NAVI4x UT parity for distributed config

---

aten/src/ATen/native/cuda/CUDALoops.cuh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2259

[AUTOGENERATED] [release/2.6] [ROCm] Set thread_work_size to 16 for vectorized elementwise kernels

---

.ci/docker/requirements-ci.txt

Cherry-pick of https://github.com/ROCm/pytorch/pull/2326

[AUTOGENERATED] [release/2.6] [rocm7.0_internal_testing] upgrade tensorboard compatible with numpy 2

---

.ci/docker/requirements-ci.txt

Cherry-pick of https://github.com/ROCm/pytorch/pull/2326

[AUTOGENERATED] [release/2.7] [rocm7.0_internal_testing] upgrade tensorboard compatible with numpy 2

---

.ci/docker/requirements-ci.txt

Cherry-pick of https://github.com/ROCm/pytorch/pull/2326 

[AUTOGENERATED] [release/2.5] [rocm7.0_internal_testing] upgrade tensorboard compatible with numpy 2

---

test/distributed/test_c10d_nccl.py
test/inductor/test_decompose_mem_bound_mm.py
torch/testing/_internal/common_utils.py

In this PR, I have added a sleep statement before collectives. We need this extra sleep for NAVI_ARCH because rccl_init inside init_process_group is happening in a separate process and it is taking longer to finish on NAVI_ARCH. Sleeping here ensures that the init is competed successfully and mem_get_info can get stable numbers.
Note that in the test the sleep statement was already there after collectives. 
Also, refactored is_navi3_arch function to is_arch that takes arch list as an argument and compares with existing arch.
Tested with docker image-
compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-rel-6.4:108_ubuntu22.04_py3.10_pytorch_rocm6.4_internal_testing_aeb5d79

[rocm6.4_internal_testing][SWDEV-535305] Fixed `test_extra_cuda_context` in `test_c10d_nccl.py` and refactored is_navi3_arch function

---

aten/src/ATen/native/cuda/layer_norm_kernel.cu
aten/src/ATen/native/sparse/cuda/SparseCUDAApplyUtils.cuh
c10/macros/Macros.h

If compiling with HIPCC (i.e `__HIPCC__` is [defined](https://rocm.docs.amd.com/projects/HIP/en/docs-develop/how-to/hip_porting_guide.html#compiler-defines-summary)):
* Define `C10_WARP_SIZE` to be non-constexpr `at::cuda::warp_size()` for host-compilation pass (as compared to `static constexpr int C10_WARP_SIZE = 1;` set in https://github.com/ROCm/pytorch/commit/538a57d13af24f96cb356b8313d47fd575c06a82)
* Define `C10_WARP_SIZE` to be constexpr `64` for `__GFX9__`, and `32` otherwise, for device-compilation pass
If not compiling with HIPCC:
* Define `C10_WARP_SIZE` to be non-constexpr `at::cuda::warp_size()` 
For host-compilation cases where we need a constexpr value of warp size (eg. launch bounds), use `C10_WARP_SIZE_STATIC`, defined as `64` (Better to err on 64 for launch bounds)
Fixes …

[release/2.6] Improve C10_WARP_SIZE compatibility

---

test/test_cuda.py

This PR fixes the unit test,
```
test/test_cuda.py::TestCuda::test_set_per_process_memory_fraction FAILED [0.1163s]
File "/var/lib/jenkins/pytorch/test/test_cuda.py", line 471, in test_set_per_process_memory_fraction
tmp_tensor = torch.empty(application, dtype=torch.int8, device="cuda")
RuntimeError: Trying to create tensor with negative dimension -5681285432: [-5681285432]
```
This error is specific to gfx1101 arch. 
This error is coming from an integer overflow when another unit test, `test/test_cuda.py::TestCuda::test_randint_generation_for_large_numel` creates a tensor with a huge numel, which overflows into a higher `torch.cuda.max_memory_reserved()` when you call `test/test_cuda.py::TestCuda::test_set_per_process_memory_fraction` afterward. To …

Clean up CUDA state between tests

---

.github/scripts/amd/package_triton_wheel.sh
.github/scripts/amd/patch_triton_wheel.sh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2130
Fixes https://ontrack-internal.amd.com/browse/SWDEV-540108?focusedId=19675066&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19675066
Validation: http://rocm-ci.amd.com/job/mainline-pytorch2.4-manylinux-wheels/310/ (failed in Pytorch build but successfully built triton wheels with version-agnostic .sos)

[release/2.4] Make triton build ROCm version agnostic

---

test/test_binary_ufuncs.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2340

[AUTOGENERATED] [release/2.7] [release/2.6] Fix dtype before comparing torch and numpy tensors

---

test/test_binary_ufuncs.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2340

[AUTOGENERATED] [rocm7.0_internal_testing] [release/2.6] Fix dtype before comparing torch and numpy tensors

---

aten/src/ATen/native/cuda/layer_norm_kernel.cu
aten/src/ATen/native/sparse/cuda/SparseCUDAApplyUtils.cuh
c10/macros/Macros.h

Cherry-pick of https://github.com/ROCm/pytorch/pull/2328

[AUTOGENERATED] [release/2.7] Improve C10_WARP_SIZE compatibility

---

aten/src/ATen/native/cuda/layer_norm_kernel.cu
aten/src/ATen/native/sparse/cuda/SparseCUDAApplyUtils.cuh
c10/macros/Macros.h

Cherry-pick of https://github.com/ROCm/pytorch/pull/2328

[AUTOGENERATED] [rocm7.0_internal_testing] Improve C10_WARP_SIZE compatibility

---

.ci/docker/requirements-ci.txt

pip installed requirements.txt and .ci/docker/requirements-ci.txt
Local validation: `Successfully installed boto3-1.35.42 botocore-1.35.99 click-8.1.8 fbscribelogger-0.1.7 mypy-1.13.0 pywavelets-1.7.0 s3transfer-0.10.4 tlparse-0.3.25`

[release/2.6] enable py3.13

---

.ci/docker/requirements-ci.txt

pip installed requirements.txt and .ci/docker/requirements-ci.txt
Local validation: `Successfully installed jinja2-3.1.6 lintrunner-0.12.7 mypy-1.14.0 onnxscript-0.2.2 sympy-1.13.3 tlparse-0.3.30 z3-solver-4.12.6.0`

[release/2.7] enable py3.13

---

.ci/docker/requirements-ci.txt

pip installed requirements.txt and .ci/docker/requirements-ci.txt
Local validation: `Successfully installed dataclasses_json-0.6.7 expecttest-0.3.0 jinja2-3.1.6 lintrunner-0.12.7 marshmallow-3.26.1 mypy-1.14.0 onnxscript-0.2.2 pyzstd-0.17.0 sympy-1.13.3 tlparse-0.3.30 typing-inspect-0.9.0 z3-solver-4.12.6.0`

[release/2.5] enable py3.13

---

test/test_torch.py

This PR is to cherry-pick test_torch.py changes from upstream [22d1359](https://github.com/pytorch/pytorch/commit/22d1359bc6b2316ee77ee134bfb258b4fa9ab643). 
This fixes the below error:
```
_____________________________________________________________________________ TestTorch.test_tensor_with_grad_to_scalar_warning ______________________________________________________________________________
File "/root/PR/pytorch/test/test_torch.py", line 10849, in test_tensor_with_grad_to_scalar_warning
self.assertEqual(len(w), 1)
File "/opt/venv/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4114, in assertEqual
raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!
Expected 1 but got 2. …
```

Fix warnings issue in test_tensor_with_grad_to_scalar_warning

---

torch/_inductor/codegen/triton_combo_kernel.py
torch/_inductor/runtime/triton_heuristics.py

Adds initial autotuning for foreach support required for https://ontrack-internal.amd.com/browse/SWDEV-539076
4x improvement for some kernels
Before:
triton_for_fused_18.kd 🔍 | 4.986 ms | 4.986 ms | 2.493 ms | 2 |  
triton_for_fused_6.kd 🔍 | 0.098 ms | 0.098 ms | 0.049 ms | 2 |  
triton_for_fused_7.kd 🔍 | 0.036 ms | 0.036 ms | 0.018 ms | 2 |  
After:
triton_for_fused_18.kd 🔍 | 1.273 ms | 1.273 ms | 0.636 ms | 2 |  
triton_for_fused_6.kd 🔍 | 0.044 ms | 0.044 ms | 0.022 ms | 2 |  
triton_for_fused_7.kd 🔍 | 0.024 ms | 0.024 ms | 0.012 ms | 2 |  

[SWDEV-539076] Initial naive foreach autotune support

---

test/test_transformers.py
torch/nn/attention/__init__.py

This PR will fix test_transformers.py and skip one test:
- Add missed lines in test_transformers.py to fix `NameError: name '_cur_sdpa_kernel_backends' is not defined`
- skip `test_transformers.py::TestAttnBias::test_causal_variants_causal_variant_CausalVariant_UPPER_LEFT_shape3_cuda` on Navi4x (tested on gfx1200 and gfx1201). Test failed on shape (1, 1, 23, 56, 15) only on Naxi4x only in release/2.5.  Test uses `hipBlas`, but switching to `hipBlasLT` doesn't help
release/2.6 has significant changes in `SDPBackend.MATH` backend and the test passes
Fixes SWDEV-522844

[release/2.5] fix and skip test_causal_variants on Navi4x

---

test/distributed/test_c10d_nccl.py
test/inductor/test_decompose_mem_bound_mm.py
torch/testing/_internal/common_utils.py

In this PR, I have added a sleep statement before collectives. We need this extra sleep for NAVI_ARCH because rccl_init inside init_process_group is happening in a separate process and it is taking longer to finish on NAVI_ARCH. Sleeping here ensures that the init is competed successfully and mem_get_info can get stable numbers.
Note that in the test the sleep statement was already there after collectives.
Also, refactored is_navi3_arch function to is_arch that takes arch list as an argument and compares with existing arch.
Tested with docker image-
registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16420_ubuntu22.04_py3.10_pytorch_lw_rocm7.0_internal_testing_2d567672

[rocm7.0_internal_testing][SWDEV-542411] Fixed test_extra_cuda_context in test_c10d_nccl.py and refactored is_navi3_arch function

---

related_commits

Fixing the C10_warpsize issue. replacing the macros with at::cuda::warp_size() - https://github.com/ROCm/apex/pull/242
[Replaced warpsize with C10_WARP_SIZE ](https://github.com/ROCm/apex/commit/dae446893a424f9a055cdf1434fb5d1e4e58187d) - https://github.com/ROCm/apex/pull/251
Fix all warp size in apex - https://github.com/ROCm/apex/pull/258
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-541725

[release/2.5] Update related_commits

---

test/dynamo/test_activation_checkpointing.py

This is to fix [SWDEV-460957](https://ontrack-internal.amd.com/browse/SWDEV-460957) in release/2.7 branch, which is same issue as [SWDEV-480138](https://ontrack-internal.amd.com/browse/SWDEV-480138) in rocm7.0_internal_testing branch.

[release/2.7] Skip UT if no flash/cudnn attention

---

test/inductor/test_cpp_wrapper_hipify.py

Same change as https://github.com/ROCm/pytorch/commit/7bb2228ffdc7d8671b7ce7030012eea96eec7353

[release/2.5] Fixed string comparison in test_cpp_wrapper_hipify

---

test/test_linalg.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2397

[AUTOGENERATED] [rocm7.0_internal_testing_gfx950][ROCm][tunableop] UT tolerance increase for matmul_small_brute_force_tunableop at FP16

---

test/distributed/test_c10d_gloo.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2317

[AUTOGENERATED] [release/2.6] [release/2.5] Skipped *_stress_cuda UTs in test_c10d_gloo

---

test/distributed/test_c10d_gloo.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2317 

[AUTOGENERATED] [release/2.7] Skipped *_stress_cuda UTs in test_c10d_gloo

---

test/inductor/test_aot_inductor.py
test/inductor/test_gpu_cpp_wrapper.py

Skip inductor tests on MI35x:
- inductor/test_gpu_cpp_wrapper.py::TestGpuWrapper::test_mm_plus_mm2_gpu_wrapper
- inductor/test_aot_inductor.py::AOTInductorTestABICompatibleGpu::test_stft_cuda
Tests cannot be skipped in the usual way with @skipIf decorator
Tests are failing on MI35x with `AssertionError` in `rocm7.0_internal_testing` branch
And with `torch.AcceleratorError: HIP error: invalid device function` in `release/2.8`
Fixes SWDEV-542678
```
python inductor/test_gpu_cpp_wrapper.py -v -k test_mm_plus_mm2_gpu_wrapper
...
OK (skipped=1)
python inductor/test_aot_inductor.py -v -k test_stft_cuda
...
OK (expected failures=1)
```

[NO CP] skip inductor tests on MI35x

---

torch/_inductor/runtime/coordinate_descent_tuner.py

Revert "[release/2.7] [SWDEV-543214] Set max_numwarps based on warp_size instead of hardcoding "

---

torch/_inductor/runtime/coordinate_descent_tuner.py

Relands https://github.com/ROCm/pytorch/pull/2416 with caching fix
Upstream equivalent https://github.com/pytorch/pytorch/pull/159146

[release/2.7] [SWDEV-543214] Reland #2416 Fix warps runtime

---

test/distributed/_tools/test_fsdp2_mem_tracker.py
test/distributed/_tools/test_sac_ilp.py
test/distributed/tensor/test_matrix_ops.py
test/distributed/test_c10d_gloo.py
test/distributed/test_c10d_nccl.py
test/distributed/test_inductor_collectives.py
test/distributed/test_symmetric_memory.py
torch/testing/_internal/distributed/distributed_test.py

Fixes https://ontrack-internal.amd.com/browse/SWDEV-541056
- Skip *_stress_cuda UTs for all archs
- Symmetric Memory is not yet supported on rocm7.0_internal_testing branch
- test_extra_cuda_context - add a barrier to ensure all nodes finish init_process_group before continuing with the test
- test_sac_ilp: skip for all rocm arch (was already skipped for MI300 and NAVI)
- test_fsdp2_mem_tracker: update tol
- test_scaled_mm - this is row-wise scaling dependent, skipped for now
- test_allreduce_inductor_cudagraph_trees: Skipped as flaky upstream as well
- test_distributed_spawn - skipped, will be fixed in next IFU

[rocm7.0_internal_testing][SWDEV-541056][MI355] Fix distributed failures

---

.ci/docker/requirements-ci.txt
test/test_linalg.py
torch/_inductor/codegen/triton_combo_kernel.py
torch/_inductor/runtime/coordinate_descent_tuner.py
torch/_inductor/runtime/triton_heuristics.py

Ensure all new cherry-picks in release/2.7 are now part of release/2.8 as well. Here' s the new commit list that were processed after https://github.com/ROCm/pytorch/pull/2389
[commits_2.8_part2.txt](https://github.com/user-attachments/files/21517848/commits_2.8_part2.txt)

[release/2.8] Sync with release/2.7 cherry-picks as of 07-30-2025

---

test/distributed/_tools/test_fsdp2_mem_tracker.py
test/distributed/_tools/test_sac_ilp.py
test/distributed/tensor/test_matrix_ops.py
test/distributed/test_c10d_gloo.py
test/distributed/test_c10d_nccl.py
test/distributed/test_inductor_collectives.py
test/distributed/test_symmetric_memory.py
torch/testing/_internal/distributed/distributed_test.py

Fix distributed failures
- Skip *_stress_cuda UTs for all archs
- Symmetric Memory is not yet supported on rocm7.0_internal_testing branch
- test_extra_cuda_context - add a barrier to ensure all nodes finish init_process_group before continuing with the test
- test_sac_ilp: skip for all rocm arch (was already skipped for MI300 and NAVI)
- test_fsdp2_mem_tracker: update tol
- test_scaled_mm - this is row-wise scaling dependent, skipped for now
- test_allreduce_inductor_cudagraph_trees: Skipped as flaky upstream as well
- test_distributed_spawn - skipped, will be fixed in next IFU
Also fixes: https://ontrack-internal.amd.com/browse/SWDEV-544875
Cherry-pick of https://github.com/ROCm/pytorch/pull/2425

[AUTOGENERATED] [release/2.7] [rocm7.0_internal_testing][SWDEV-541056][MI355] Fix distributed failures

---

test/test_matmul_cuda.py

fp8 rowwise scaling is not supported on ROCm 7.0,
works on mainline.
Skip the test for now.

[rocm7.0_internal_testing]fp8: skip rowwise tests

---

aten/src/ATen/native/miopen/Conv_miopen.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2405

[AUTOGENERATED] [release/2.6] [rocm7.0_internal_testing] remove extra transposes in NHWC convolutions on MIOpen

---

aten/src/ATen/native/miopen/Conv_miopen.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2405

[AUTOGENERATED] [release/2.7] [rocm7.0_internal_testing] remove extra transposes in NHWC convolutions on MIOpen

---

test/test_matmul_cuda.py

Issue is tracked by SWDEV-535267
This PR skips two test methods (test_blockwise_mxfp8_nvfp4_error_messages and test_blockwise_nvfp4_compile) when running on ROCm platform to address an issue tracked by SWDEV-535267.
- Adds @skipIfRocm decorators to skip tests that are failing on ROCm 7.0 internal testing
- Targets specific matrix multiplication tests related to MX float formats

[rocm7.0_internal_testing] mx fpx: Skip test_blockwise_mxfloatx

---

aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/native/miopen/RNN_miopen.cpp
test/test_nn.py

This PR has fixes for P1 Jira https://ontrack-internal.amd.com/browse/SWDEV-542659.
In this Jira, there are 3 test files with failing tests.
1) distributed.test_distributed_spawn
2) test_binary_ufuncs
3) test_nn 
The test files **distributed.test_distributed_spawn** & **test_binary_ufuncs** are passing with latest mainline build-
**registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16426_ubuntu22.04_py3.10_pytorch_lw_release-2.7_fe3d37a9**.
The test file **test_nn** has 2 failing tests- **test_batchnorm_3D_train_NCHW_vs_native_mixed_float16** & **test_RNN_dropout_state**. 
The **test_batchnorm_3D_train_NCHW_vs_native_mixed_float16** test is skipped from PR https://github.com/ROCm/pytorch/pull/2370.
The **test_RNN_dropout_state** is fixed by cherry picking upstream …

[release/2.7] Fix test_rnn_check_device tests for P1 Jira SWDEV-542659

---

torch/_inductor/runtime/coordinate_descent_tuner.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2442

[AUTOGENERATED] [release/2.8] [release/2.7] [SWDEV-543214] Reland #2416 Fix warps runtime part 2

---

test/inductor/test_torchinductor.py
test/inductor/test_torchinductor_codegen_dynamic_shapes.py
torch/_inductor/decomposition.py

Cherry-pick of: https://github.com/pytorch/pytorch/pull/159294

Fix rand_like decomposition to preserve strides

---

aten/src/ATen/native/cuda/Reduce.cuh

In the current implementation of reductions in three dimensions for AMD GPUs the number of values per thread is unbounded and can end up being in the hundreds of thousands for certain tensors. This of course is bad for performance. This patch fixes this issue by increasing the parallelism and thus lowering the number of value per thread to reasonable limits i.e. less than 2048 values per thread. The performance gains can be between 10x-17x for certain examples where the number of values per thread was originally very high.
cherry-pick of https://github.com/pytorch/pytorch/pull/159652

[ROCm] Limit number of values per thread for reductions on three dimensions

---

torch/csrc/jit/codegen/fuser/cuda/resource_strings.h

This PR fixes the errors like below:
`[rank7]: RuntimeError: /tmp/comgr-c3c81b/input/CompileSourceejOPx6:34:8: error: unknown type name 'uint64_t'; did you mean '__hip_internal::uint64_t'?
[rank7]:    34 |   if(((uint64_t) t0.data) % (4 * sizeof(half)) != 0) flag_vec4 = false;`
Earlier uint64_t was defined in HIP headers in std namespace. Now it is moved to __hip_internal namespace in hip headers. This change is made in ROCm 7.0.
Fixes https://ontrack-internal.amd.com/browse/SWDEV-543698

Define datatypes when ROCM_VERSION >= 70000

---

aten/src/ATen/native/cuda/Reduce.cuh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2460

[AUTOGENERATED] [release/2.8] [ROCm] Limit number of values per thread for reductions on three dimensions

---

torch/csrc/jit/codegen/fuser/cuda/resource_strings.h

Fixes SWDEV-543698
Cherry-picked from https://github.com/ROCm/pytorch/pull/2468
This PR fixes the errors like below:
[rank7]: RuntimeError: /tmp/comgr-c3c81b/input/CompileSourceejOPx6:34:8: error: unknown type name 'uint64_t'; did you mean '__hip_internal::uint64_t'? [rank7]: 34 | if(((uint64_t) t0.data) % (4 * sizeof(half)) != 0) flag_vec4 = false;
Earlier uint64_t was defined in HIP headers in std namespace. Now it is moved to __hip_internal namespace in hip headers. This change is made in ROCm 7.0.
Fixes https://ontrack-internal.amd.com/browse/SWDEV-543698

[release/2.6] Define datatypes when ROCM_VERSION >= 70000

---

test/distributed/tensor/parallel/test_tp_examples.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2385

[AUTOGENERATED] [release/2.7] [rocm7.0_internal_testing] skip test_transformer_req_grad on Navi32/Navi4x

---

requirements.txt

docker image used: registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16480_ubuntu22.04_py3.10_pytorch_lw_release-2.7_6c845c6c
lowering requirement for cmake as it is compatible with cmake<4

[release/2.7] repin requirements.txt

---

test/test_matmul_cuda.py
torch/testing/_internal/common_utils.py

fp8 rowwise scaling is not supported on ROCm 7.0 w/ gfx950, works on mainline.
Skip the test for now.

[release/2.8] fp8: skip rowwise tests

---

test/test_matmul_cuda.py
torch/testing/_internal/common_utils.py

Skip based on ROCm version and gfx type.

[rocm7.0_internal_testing]fp8: optimize skip rowwise tests

---

related_commits

update the param_id calculation so that it works on both CPX and SPX modes - https://github.com/ROCm/apex/pull/271
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-548434

[rocm7.1_internal_testing] Update related_commits

---

aten/src/ATen/native/miopen/Conv_miopen.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2405

[AUTOGENERATED] [release/2.8] remove extra transposes in NHWC convolutions on MIOpen

---

aten/src/ATen/native/cuda/Reduce.cuh

Cherry-pick of https://github.com/ROCm/pytorch/pull/2492

[AUTOGENERATED] [release/2.8] [ROCm] Improve reduction sum performance

---

test/distributed/test_c10d_nccl.py

Cherry-pick of https://github.com/ROCm/pytorch/pull/2447

[release/2.8] Using c10d.barrier() in test_extra_cuda_context test in test_c10d_nccl.py

---

aten/src/ATen/miopen/Descriptors.h
aten/src/ATen/native/miopen/RNN_miopen.cpp

Cherry-pick of https://github.com/ROCm/pytorch/pull/2440

[rocm7.0_internal_testing] Fix test_rnn_check_device tests for P1 Jira SWDEV-542659

---

test/distributed/test_c10d_functional_native.py

These UTs are working in future releases (rocm7.1_internal_testing)
Fixes SWDEV-535015

[release/2.7] Skip CompileTest in `test_c10d_functional_native.py`

---

.github/scripts/build_triton_wheel.py

Relates to https://github.com/ROCm/builder/pull/91
Release 7.0: http://rocm-ci.amd.com/job/pytorch2.6-manylinux-wheels_rel-7.0/40/
`pytorch_triton_rocm-3.2.0+rocm7.0.0.git20943800-cp313-cp313-linux_x86_64.whl pushed to http://compute-artifactory.amd.com/artifactory/compute-pytorch-rocm/compute-rocm-rel-7.0/6/triton_main_conditionalize/pytorch_triton_rocm-3.2.0+rocm7.0.0.git20943800-cp313-cp313-linux_x86_64.whl`
Mainline: http://rocm-ci.amd.com/job/mainline-pytorch2.6-manylinux-wheels/244/
`triton-3.2.0+rocm7.1.0.git20943800-cp313-cp313-linux_x86_64.whl pushed to http://compute-artifactory.amd.com/artifactory/compute-pytorch-rocm/compute-rocm-dkms-no-npi-hipclang/16516/triton_main_conditionalize/triton-3.2.0+rocm7.1.0.git20943800-cp313-cp313-linux_x86_64.whl`

[release/2.6] Change triton package name depending on rocm version

---

requirements-build.txt
requirements.txt

Tested locally successfully 
```
root@rocm-framework-47:/var/lib/jenkins/pytorch# pip install -r requirements.txt
Ignoring numpy: markers 'python_version == "3.9"' don't match your environment
Requirement already satisfied: setuptools<80.0,>=70.1.0 in /opt/venv/lib/python3.10/site-packages (from -r /var/lib/jenkins/pytorch/requirements-build.txt (line 2)) (79.0.1)
Requirement already satisfied: cmake>=3.31.4 in /opt/venv/lib/python3.10/site-packages (from -r /var/lib/jenkins/pytorch/requirements-build.txt (line 3)) (4.0.0)
Requirement already satisfied: ninja==1.11.1.3 in /opt/venv/lib/python3.10/site-packages (from -r /var/lib/jenkins/pytorch/requirements-build.txt (line 4)) (1.11.1.3)
Requirement already satisfied: numpy==2.1.2 in /opt/venv/lib/python3.10/site-packages (from -r …
```

[rocm7.1_internal_testing] Pin requirements

---

torch/csrc/jit/codegen/fuser/cuda/resource_strings.h

Fixes SWDEV-543698 (https://ontrack-internal.amd.com/browse/SWDEV-543698)
Cherry-picked from https://github.com/ROCm/pytorch/pull/2502
This PR fixes the errors like below:
```
[rank3]: RuntimeError: The following operation failed in the TorchScript interpreter.
[rank3]: Traceback of TorchScript (most recent call last):
[rank3]: RuntimeError: /tmp/comgr-28f951/input/CompileSourceACC062:67:7: error: unknown type name 'uint32_t'; did you mean '__hip_internal::uint32_t'?
[rank3]:    67 |       uint32_t int32;
[rank3]:       |       ^~~~~~~~
[rank3]:       |       __hip_internal::uint32_t
```
Earlier uint32_t was defined in HIP headers in std namespace. Now it is moved to __hip_internal namespace in hip headers. This change is made in ROCm 7.0.

[rocm7.1_internal_testing] Define uint32 t when ROCM_VERSION >= 70000

---

torch/csrc/jit/codegen/fuser/cuda/resource_strings.h

Fixes SWDEV-543698 (https://ontrack-internal.amd.com/browse/SWDEV-543698)
Cherry-picked from https://github.com/ROCm/pytorch/pull/2502
This PR fixes the errors like below:
```
[rank3]: RuntimeError: The following operation failed in the TorchScript interpreter.
[rank3]: Traceback of TorchScript (most recent call last):
[rank3]: RuntimeError: /tmp/comgr-28f951/input/CompileSourceACC062:67:7: error: unknown type name 'uint32_t'; did you mean '__hip_internal::uint32_t'?
[rank3]:    67 |       uint32_t int32;
[rank3]:       |       ^~~~~~~~
[rank3]:       |       __hip_internal::uint32_t
```
Earlier uint32_t was defined in HIP headers in std namespace. Now it is moved to __hip_internal namespace in hip headers. This change is made in ROCm 7.0.

[release/2.7] Define uint32 t when ROCM_VERSION >= 70000

---

torch/testing/_internal/common_utils.py

Fixes test/distributed/tensor/test_matrix_ops.py by defining missing constant value

[release/2.7] Added missing MI350_ARCH constant value

---

test/distributed/_composable/fsdp/test_fully_shard_clip_grad_norm_.py
test/distributed/fsdp/test_fsdp_overlap.py
test/distributed/test_c10d_ops_nccl.py

- test_fully_shard_clip_grad_norm_.py: increase tol same order of magnitude as before
- test_c10d_ops_nccl.py: skip test_allreduce_in_cudagraph
- test_fsdp_overlap.py: skipped as this UT doesn't run on upstream
Fixes SWDEV-544875

[release/2.7][SWDEV-544875] Fix MI350 Distributed UTs

---

.ci/docker/requirements-ci.txt

Fixes https://ontrack-internal.amd.com/browse/SWDEV-541809
test runs:
```
root@rocm-framework-47:/var/lib/jenkins/pytorch/test# python test_monitor.py -m 'not serial' --shard-id=1 --num-shards=1 -v -vv -rfEX -p no:xdist --use-pytest -x --import-slow-tests --import-disabled-tests
/opt/venv/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py:1221: UserWarning: disabled test file provided but not found: .pytorch-disabled-tests.json
warnings.warn(f'disabled test file provided but not found: {DISABLED_TESTS_FILE}')
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.10.12, pytest-7.3.2, …
```

[release/2.6] Remove tb-nightly

---

aten/src/ATen/native/cuda/Reduce.cuh

cherry-pick of https://github.com/pytorch/pytorch/pull/160979
Less-performant fix until https://github.com/pytorch/pytorch/pull/161180 is finalized
* The global reduction path in reduction kernel currently has two threadfence operation
* The first threadfence is executed by all threads in all the blocks, whereas the second threadfence is only run by threads in a single block
* For AMD gpus, threadfence is a heavy weight operation, esp. when run by all the threads in the system (due to cross-XCD synchronizations)
* So using fine-grain fence gives significant performance boost for AMD gpus.
* We do a release fence when threads write to reduce buffer in global memory; and then do a acquire fence when threads read from the reduce buffer
Co-author: @amd-hhashemi, @jeffdaily 
**Reproducer**: …

[ROCm] Use fine-grain fence in reduction

---

aten/src/ATen/native/cuda/Reduce.cuh

cherry-pick of https://github.com/pytorch/pytorch/pull/161181
Fixes SWDEV-545710

[ROCm] Unroll loads in global_reduce

---

.github/scripts/build_triton_wheel.py

[rocm7.1_internal_testing] Add triton_kernels wheel generation

---

aten/src/ATen/native/cuda/SortStable.cu
test/quantization/core/test_quantized_op.py
test/test_matmul_cuda.py
test/test_scatter_gather_ops.py
test/test_sort_and_select.py
test/test_transformers.py
torch/_tensor_str.py
torch/cuda/__init__.py

Fixes SWDEV-546357
torch.cuda.is_tf32_supported Is NOT public - Fixed by adding is_tf32_supported  to \_\_all\_\_[]
```
test_public_bindings.py::TestPublicBindings::test_correct_module_names
```
AssertionError: Tensor-likes are not close! - Fixed by expecting AssertionError if ROCm
```
test_matmul_cuda.py::TestFP8MatmulCudaCUDA::test_float8_basics_cuda
```
RuntimeError: "index_cuda" not implemented for 'Float8_e8m0fnu' - fixed by converting to float16 for str(tensor) (like other fp8's)
```
test_quantization.py::TestFloat8DtypeCUDA::test_to_string_cuda_float8_e8m0fnu
```
OverflowError: Python integer 128 out of bounds for int8 - Fixed by skipping if numpy >=2.1
```
test_quantization.py::TestDynamicQuantizedOps::test_qlinear
test_quantization.py::TestDynamicQuantizedOps::test_qlinear_legacy …
```

[release/2.6] unittest fixes

---

aten/src/ATen/native/cuda/SortStable.cu
test/test_sort_and_select.py

Currently std::min -> ::min did not work as expected on ROCm when input values >= 2147483648
Replace std::min to ternary statement
Also std::min can be replaced by explicit typing std::min<int64_t>
fixes on ROCm:
test_sort_and_select.py::TestSortAndSelectCUDA::test_sort_large_cuda_float16
error:
RuntimeError: Cannot sort dimension of length 8192
Combines upstream PRs:
- https://github.com/pytorch/pytorch/pull/161054 to fix std::min on ROCm
- https://github.com/pytorch/pytorch/pull/155546 fix python test
- https://github.com/pytorch/pytorch/pull/159939 change test dtype from int8 to float16
Fixes: SWDEV-526432

[rocm7.1_internal_testing] fix large tensor sort on ROCm

---

aten/src/ATen/native/cuda/KernelUtils.cuh
aten/src/ATen/native/cuda/Reduce.cuh

This change removes need for fences in global_reduce by converting the stores to reduce_buffer[] into atomics+return. This is crucial for perf in architectures with split caches (e.g. MI300), where fences are inherently costly.
cherry-pick of https://github.com/pytorch/pytorch/pull/161180

[ROCm] No-fence global reduce

---

test/dynamo/test_logging.py

PR to fix
- dynamo/test_logging.py::LoggingTests::test_logs_out
Test compares a console log with the dynamo output log file.
It failed due to unrelated python UserWarning messages in the console log:
```
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/redis/connection.py:77: UserWarning: redis-py works best with hiredis. Please consider installing
warnings.warn(msg)
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/z3/z3core.py:5: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
import pkg_resources
```
This PR adds the environment variable `PYTHONWARNINGS="ignore"` when starting the test …

[release/2.6] Suppress Python UserWarnings to fix compiler logs test

---

.gitmodules

This PR:
Fixes SWDEV-534327
Reverted rocprof-sdk from rocm/kineto to pytorch/kineto; pointing pytorch/kineto commit (https://github.com/pytorch/kineto/tree/5fa4bd8c8fb581a621f72957d0cb11431cc4714f) from https://github.com/ROCm/pytorch/tree/7886773808bda86ee7d47c4eaa39c98c43744872/third_party, which (78867738) is the commit right before rocprof-sdk change in rocm7.0_internal_testing branch.

Reverted of rocprof-sdk integration

---

test/test_nn.py

After PR: https://github.com/pytorch/pytorch/pull/156600, this test was failing internally on large tensors because the differences were greater than tolerances on some cuda devices.
We now raise the tolerances for larger tensors.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/156699 Approved by: https://github.com/eqy, https://github.com/ngimel
(cherry picked from commit 36dd598bdac5c665e46f05d00a38d6863a99615f)
Fixes SWDEV-547998

[release/2.8] layernorm tests: Tweak test thresholds for comparing tensors
